
-- Insert Amazonas municipalities (2)
INSERT INTO municipalities (name, department_id) VALUES
('Leticia', (SELECT id FROM departments WHERE name = 'Amazonas')),
('Puerto Nariño', (SELECT id FROM departments WHERE name = 'Amazonas'))
ON CONFLICT DO NOTHING;

-- Insert Antioquia municipalities (125)
INSERT INTO municipalities (name, department_id) VALUES
('Abejorral', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Abriaquí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Alejandría', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Amagá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Amalfi', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Andes', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Angelópolis', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Angostura', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Anorí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Anzá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Apartadó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Arboletes', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Argelia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Armenia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Barbosa', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Bello', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Belmira', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Betania', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Betulia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Briceño', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Buriticá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Cáceres', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Caicedo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Caldas', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Campamento', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Cañasgordas', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Caracolí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Caramanta', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Carepa', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Carolina del Príncipe', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Caucasia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Chigorodó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Cisneros', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Ciudad Bolívar', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Cocorná', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Concepción', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Concordia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Copacabana', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Dabeiba', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Donmatías', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Ebéjico', (SELECT id FROM departments WHERE name = 'Antioquia')),
('El Bagre', (SELECT id FROM departments WHERE name = 'Antioquia')),
('El Carmen de Viboral', (SELECT id FROM departments WHERE name = 'Antioquia')),
('El Peñol', (SELECT id FROM departments WHERE name = 'Antioquia')),
('El Retiro', (SELECT id FROM departments WHERE name = 'Antioquia')),
('El Santuario', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Entrerríos', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Envigado', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Fredonia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Frontino', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Giraldo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Girardota', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Gómez Plata', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Granada', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Guadalupe', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Guarne', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Guatapé', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Heliconia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Hispania', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Itagüí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Ituango', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Jardín', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Jericó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('La Ceja', (SELECT id FROM departments WHERE name = 'Antioquia')),
('La Estrella', (SELECT id FROM departments WHERE name = 'Antioquia')),
('La Pintada', (SELECT id FROM departments WHERE name = 'Antioquia')),
('La Unión', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Liborina', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Maceo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Marinilla', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Medellín', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Montebello', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Murindó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Mutatá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Nariño', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Nechí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Necoclí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Olaya', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Peque', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Pueblorrico', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Puerto Berrío', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Puerto Nare', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Puerto Triunfo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Remedios', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Rionegro', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Sabanalarga', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Sabaneta', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Salgar', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Andrés de Cuerquia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Carlos', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Francisco', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Jerónimo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San José de la Montaña', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Juan de Urabá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Luis', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Pedro de Urabá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Pedro de los Milagros', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Rafael', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Roque', (SELECT id FROM departments WHERE name = 'Antioquia')),
('San Vicente', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Santa Bárbara', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Santa Fe de Antioquia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Santa Rosa de Osos', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Santo Domingo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Segovia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Sonsón', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Sopetrán', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Támesis', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Tarazá', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Tarso', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Titiribí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Toledo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Turbo', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Uramita', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Urrao', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Valdivia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Valparaíso', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Vegachí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Venecia', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Vigía del Fuerte', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Yalí', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Yarumal', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Yolombó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Yondó', (SELECT id FROM departments WHERE name = 'Antioquia')),
('Zaragoza', (SELECT id FROM departments WHERE name = 'Antioquia'))
ON CONFLICT DO NOTHING;

-- Insert Arauca municipalities (7)
INSERT INTO municipalities (name, department_id) VALUES
('Arauca', (SELECT id FROM departments WHERE name = 'Arauca')),
('Arauquita', (SELECT id FROM departments WHERE name = 'Arauca')),
('Cravo Norte', (SELECT id FROM departments WHERE name = 'Arauca')),
('Fortul', (SELECT id FROM departments WHERE name = 'Arauca')),
('Puerto Rondón', (SELECT id FROM departments WHERE name = 'Arauca')),
('Saravena', (SELECT id FROM departments WHERE name = 'Arauca')),
('Tame', (SELECT id FROM departments WHERE name = 'Arauca'))
ON CONFLICT DO NOTHING;

-- Insert Atlántico municipalities (23)
INSERT INTO municipalities (name, department_id) VALUES
('Baranoa', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Barranquilla', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Campo de la Cruz', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Candelaria', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Galapa', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Juan de Acosta', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Luruaco', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Malambo', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Manatí', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Palmar de Varela', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Piojó', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Polonuevo', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Ponedera', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Puerto Colombia', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Repelón', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Sabanagrande', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Sabanalarga', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Santa Lucía', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Santo Tomás', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Soledad', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Suán', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Tubará', (SELECT id FROM departments WHERE name = 'Atlántico')),
('Usiacurí', (SELECT id FROM departments WHERE name = 'Atlántico'))
ON CONFLICT DO NOTHING;

-- Insert Bolívar municipalities (47)
INSERT INTO municipalities (name, department_id) VALUES
('Achí', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Altos del Rosario', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Arenal', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Arjona', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Arroyohondo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Barranco de Loba', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Brazuelo de Papayal', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Calamar', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Cantagallo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Cartagena de Indias', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Cicuco', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Clemencia', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Córdoba', (SELECT id FROM departments WHERE name = 'Bolívar')),
('El Carmen de Bolívar', (SELECT id FROM departments WHERE name = 'Bolívar')),
('El Guamo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('El Peñón', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Hatillo de Loba', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Magangué', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Mahates', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Margarita', (SELECT id FROM departments WHERE name = 'Bolívar')),
('María la Baja', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Mompós', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Montecristo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Morales', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Norosí', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Pinillos', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Regidor', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Río Viejo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Cristóbal', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Estanislao', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Fernando', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Jacinto del Cauca', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Jacinto', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Juan Nepomuceno', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Martín de Loba', (SELECT id FROM departments WHERE name = 'Bolívar')),
('San Pablo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Santa Catalina', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Santa Rosa', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Santa Rosa del Sur', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Simití', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Soplaviento', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Talaigua Nuevo', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Tiquisio', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Turbaco', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Turbaná', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Villanueva', (SELECT id FROM departments WHERE name = 'Bolívar')),
('Zambrano', (SELECT id FROM departments WHERE name = 'Bolívar'))
ON CONFLICT DO NOTHING;

-- Insert Boyacá municipalities (123)
INSERT INTO municipalities (name, department_id) VALUES
('Almeida', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Aquitania', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Arcabuco', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Belén', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Berbeo', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Betéitiva', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Boavita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Boyacá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Briceño', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Buenavista', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Busbanzá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Caldas', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Campohermoso', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Cerinza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chinavita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chiquinquirá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chíquiza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chiscas', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chitaraque', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chivatá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Chivor', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Ciénega', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Cómbita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Coper', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Corrales', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Covarachía', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Cubará', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Cucaita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Cuítiva', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Duitama', (SELECT id FROM departments WHERE name = 'Boyacá')),
('El Cocuy', (SELECT id FROM departments WHERE name = 'Boyacá')),
('El Espino', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Firavitoba', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Floresta', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Gachantivá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Gámeza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Garagoa', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Guacamayas', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Guateque', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Guayatá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Güicán', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Iza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Jenesano', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Jericó', (SELECT id FROM departments WHERE name = 'Boyacá')),
('La Capilla', (SELECT id FROM departments WHERE name = 'Boyacá')),
('La Uvita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('La Victoria', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Labranzagrande', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Macanal', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Maripí', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Miraflores', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Mongua', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Monguí', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Moniquirá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Motavita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Muzo', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Nobsa', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Nuevo Colón', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Oicatá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Otanche', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Pachavita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Páez', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Paipa', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Pajarito', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Panqueba', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Pauna', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Paya', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Paz del Río', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Pesca', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Pisba', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Puerto Boyacá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Quípama', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Ramiriquí', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Ráquira', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Rondón', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Saboyá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sáchica', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Samacá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San Eduardo', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San José de Pare', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San Luis de Gaceno', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San Mateo', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San Miguel de Sema', (SELECT id FROM departments WHERE name = 'Boyacá')),
('San Pablo de Borbur', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Santa María', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Santa Rosa de Viterbo', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Santa Sofía', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Santana', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sativanorte', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sativasur', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Siachoque', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Soatá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Socha', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Socotá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sogamoso', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Somondoco', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sora', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Soracá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sotaquirá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Susacón', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sutamarchán', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Sutatenza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tasco', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tenza', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tibaná', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tibasosa', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tinjacá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tipacoque', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Toca', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Togüí', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tópaga', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tota', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tunja', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tununguá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Turmequé', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tuta', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Tutazá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Úmbita', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Ventaquemada', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Villa de Leyva', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Viracachá', (SELECT id FROM departments WHERE name = 'Boyacá')),
('Zetaquira', (SELECT id FROM departments WHERE name = 'Boyacá'))
ON CONFLICT DO NOTHING;

-- Insert Caldas municipalities (27)
INSERT INTO municipalities (name, department_id) VALUES
('Aguadas', (SELECT id FROM departments WHERE name = 'Caldas')),
('Anserma', (SELECT id FROM departments WHERE name = 'Caldas')),
('Aranzazu', (SELECT id FROM departments WHERE name = 'Caldas')),
('Belalcázar', (SELECT id FROM departments WHERE name = 'Caldas')),
('Chinchiná', (SELECT id FROM departments WHERE name = 'Caldas')),
('Filadelfia', (SELECT id FROM departments WHERE name = 'Caldas')),
('La Dorada', (SELECT id FROM departments WHERE name = 'Caldas')),
('La Merced', (SELECT id FROM departments WHERE name = 'Caldas')),
('Manizales', (SELECT id FROM departments WHERE name = 'Caldas')),
('Manzanares', (SELECT id FROM departments WHERE name = 'Caldas')),
('Marmato', (SELECT id FROM departments WHERE name = 'Caldas')),
('Marquetalia', (SELECT id FROM departments WHERE name = 'Caldas')),
('Marulanda', (SELECT id FROM departments WHERE name = 'Caldas')),
('Neira', (SELECT id FROM departments WHERE name = 'Caldas')),
('Norcasia', (SELECT id FROM departments WHERE name = 'Caldas')),
('Pácora', (SELECT id FROM departments WHERE name = 'Caldas')),
('Palestina', (SELECT id FROM departments WHERE name = 'Caldas')),
('Pensilvania', (SELECT id FROM departments WHERE name = 'Caldas')),
('Riosucio', (SELECT id FROM departments WHERE name = 'Caldas')),
('Risaralda', (SELECT id FROM departments WHERE name = 'Caldas')),
('Salamina', (SELECT id FROM departments WHERE name = 'Caldas')),
('Samaná', (SELECT id FROM departments WHERE name = 'Caldas')),
('San José', (SELECT id FROM departments WHERE name = 'Caldas')),
('Supía', (SELECT id FROM departments WHERE name = 'Caldas')),
('Victoria', (SELECT id FROM departments WHERE name = 'Caldas')),
('Villamaría', (SELECT id FROM departments WHERE name = 'Caldas')),
('Viterbo', (SELECT id FROM departments WHERE name = 'Caldas'))
ON CONFLICT DO NOTHING;

-- Insert Caquetá municipalities (16)
INSERT INTO municipalities (name, department_id) VALUES
('Albania', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Belén de los Andaquíes', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Cartagena del Chairá', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Curillo', (SELECT id FROM departments WHERE name = 'Caquetá')),
('El Doncello', (SELECT id FROM departments WHERE name = 'Caquetá')),
('El Paujil', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Florencia', (SELECT id FROM departments WHERE name = 'Caquetá')),
('La Montañita', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Milán', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Morelia', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Puerto Rico', (SELECT id FROM departments WHERE name = 'Caquetá')),
('San José del Fragua', (SELECT id FROM departments WHERE name = 'Caquetá')),
('San Vicente del Caguán', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Solano', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Solita', (SELECT id FROM departments WHERE name = 'Caquetá')),
('Valparaíso', (SELECT id FROM departments WHERE name = 'Caquetá'))
ON CONFLICT DO NOTHING;

-- Insert Casanare municipalities (19)
INSERT INTO municipalities (name, department_id) VALUES
('Aguazul', (SELECT id FROM departments WHERE name = 'Casanare')),
('Chámeza', (SELECT id FROM departments WHERE name = 'Casanare')),
('Hato Corozal', (SELECT id FROM departments WHERE name = 'Casanare')),
('La Salina', (SELECT id FROM departments WHERE name = 'Casanare')),
('Maní', (SELECT id FROM departments WHERE name = 'Casanare')),
('Monterrey', (SELECT id FROM departments WHERE name = 'Casanare')),
('Nunchía', (SELECT id FROM departments WHERE name = 'Casanare')),
('Orocué', (SELECT id FROM departments WHERE name = 'Casanare')),
('Paz de Ariporo', (SELECT id FROM departments WHERE name = 'Casanare')),
('Pore', (SELECT id FROM departments WHERE name = 'Casanare')),
('Recetor', (SELECT id FROM departments WHERE name = 'Casanare')),
('Sabanalarga', (SELECT id FROM departments WHERE name = 'Casanare')),
('Sácama', (SELECT id FROM departments WHERE name = 'Casanare')),
('San Luis de Palenque', (SELECT id FROM departments WHERE name = 'Casanare')),
('Támara', (SELECT id FROM departments WHERE name = 'Casanare')),
('Tauramena', (SELECT id FROM departments WHERE name = 'Casanare')),
('Trinidad', (SELECT id FROM departments WHERE name = 'Casanare')),
('Villanueva', (SELECT id FROM departments WHERE name = 'Casanare')),
('Yopal', (SELECT id FROM departments WHERE name = 'Casanare'))
ON CONFLICT DO NOTHING;

-- Insert Cauca municipalities (42)
INSERT INTO municipalities (name, department_id) VALUES
('Almaguer', (SELECT id FROM departments WHERE name = 'Cauca')),
('Argelia', (SELECT id FROM departments WHERE name = 'Cauca')),
('Balboa', (SELECT id FROM departments WHERE name = 'Cauca')),
('Bolívar', (SELECT id FROM departments WHERE name = 'Cauca')),
('Buenos Aires', (SELECT id FROM departments WHERE name = 'Cauca')),
('Cajibío', (SELECT id FROM departments WHERE name = 'Cauca')),
('Caldono', (SELECT id FROM departments WHERE name = 'Cauca')),
('Caloto', (SELECT id FROM departments WHERE name = 'Cauca')),
('Corinto', (SELECT id FROM departments WHERE name = 'Cauca')),
('El Tambo', (SELECT id FROM departments WHERE name = 'Cauca')),
('Florencia', (SELECT id FROM departments WHERE name = 'Cauca')),
('Guachené', (SELECT id FROM departments WHERE name = 'Cauca')),
('Guapí', (SELECT id FROM departments WHERE name = 'Cauca')),
('Inzá', (SELECT id FROM departments WHERE name = 'Cauca')),
('Jambaló', (SELECT id FROM departments WHERE name = 'Cauca')),
('La Sierra', (SELECT id FROM departments WHERE name = 'Cauca')),
('La Vega', (SELECT id FROM departments WHERE name = 'Cauca')),
('López de Micay', (SELECT id FROM departments WHERE name = 'Cauca')),
('Mercaderes', (SELECT id FROM departments WHERE name = 'Cauca')),
('Miranda', (SELECT id FROM departments WHERE name = 'Cauca')),
('Morales', (SELECT id FROM departments WHERE name = 'Cauca')),
('Padilla', (SELECT id FROM departments WHERE name = 'Cauca')),
('Páez', (SELECT id FROM departments WHERE name = 'Cauca')),
('Patía', (SELECT id FROM departments WHERE name = 'Cauca')),
('Piamonte', (SELECT id FROM departments WHERE name = 'Cauca')),
('Piendamó', (SELECT id FROM departments WHERE name = 'Cauca')),
('Popayán', (SELECT id FROM departments WHERE name = 'Cauca')),
('Puerto Tejada', (SELECT id FROM departments WHERE name = 'Cauca')),
('Puracé', (SELECT id FROM departments WHERE name = 'Cauca')),
('Rosas', (SELECT id FROM departments WHERE name = 'Cauca')),
('San Sebastián', (SELECT id FROM departments WHERE name = 'Cauca')),
('Santa Rosa', (SELECT id FROM departments WHERE name = 'Cauca')),
('Santander de Quilichao', (SELECT id FROM departments WHERE name = 'Cauca')),
('Silvia', (SELECT id FROM departments WHERE name = 'Cauca')),
('Sotará', (SELECT id FROM departments WHERE name = 'Cauca')),
('Suárez', (SELECT id FROM departments WHERE name = 'Cauca')),
('Sucre', (SELECT id FROM departments WHERE name = 'Cauca')),
('Timbío', (SELECT id FROM departments WHERE name = 'Cauca')),
('Timbiquí', (SELECT id FROM departments WHERE name = 'Cauca')),
('Toribío', (SELECT id FROM departments WHERE name = 'Cauca')),
('Totoró', (SELECT id FROM departments WHERE name = 'Cauca')),
('Villa Rica', (SELECT id FROM departments WHERE name = 'Cauca'))
ON CONFLICT DO NOTHING;

-- Insert Cesar municipalities (25)
INSERT INTO municipalities (name, department_id) VALUES
('Aguachica', (SELECT id FROM departments WHERE name = 'Cesar')),
('Agustín Codazzi', (SELECT id FROM departments WHERE name = 'Cesar')),
('Astrea', (SELECT id FROM departments WHERE name = 'Cesar')),
('Becerril', (SELECT id FROM departments WHERE name = 'Cesar')),
('Bosconia', (SELECT id FROM departments WHERE name = 'Cesar')),
('Chimichagua', (SELECT id FROM departments WHERE name = 'Cesar')),
('Chiriguaná', (SELECT id FROM departments WHERE name = 'Cesar')),
('Curumaní', (SELECT id FROM departments WHERE name = 'Cesar')),
('El Copey', (SELECT id FROM departments WHERE name = 'Cesar')),
('El Paso', (SELECT id FROM departments WHERE name = 'Cesar')),
('Gamarra', (SELECT id FROM departments WHERE name = 'Cesar')),
('González', (SELECT id FROM departments WHERE name = 'Cesar')),
('La Gloria (Cesar)', (SELECT id FROM departments WHERE name = 'Cesar')),
('La Jagua de Ibirico', (SELECT id FROM departments WHERE name = 'Cesar')),
('La Paz', (SELECT id FROM departments WHERE name = 'Cesar')),
('Manaure Balcón del Cesar', (SELECT id FROM departments WHERE name = 'Cesar')),
('Pailitas', (SELECT id FROM departments WHERE name = 'Cesar')),
('Pelaya', (SELECT id FROM departments WHERE name = 'Cesar')),
('Pueblo Bello', (SELECT id FROM departments WHERE name = 'Cesar')),
('Río de Oro', (SELECT id FROM departments WHERE name = 'Cesar')),
('San Alberto', (SELECT id FROM departments WHERE name = 'Cesar')),
('San Diego', (SELECT id FROM departments WHERE name = 'Cesar')),
('San Martín', (SELECT id FROM departments WHERE name = 'Cesar')),
('Tamalameque', (SELECT id FROM departments WHERE name = 'Cesar')),
('Valledupar', (SELECT id FROM departments WHERE name = 'Cesar'))
ON CONFLICT DO NOTHING;

-- Insert Chocó municipalities (30)
INSERT INTO municipalities (name, department_id) VALUES
('Acandí', (SELECT id FROM departments WHERE name = 'Chocó')),
('Alto Baudó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Bagadó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Bahía Solano', (SELECT id FROM departments WHERE name = 'Chocó')),
('Bajo Baudó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Bojayá', (SELECT id FROM departments WHERE name = 'Chocó')),
('Cantón de San Pablo', (SELECT id FROM departments WHERE name = 'Chocó')),
('Cértegui', (SELECT id FROM departments WHERE name = 'Chocó')),
('Condoto', (SELECT id FROM departments WHERE name = 'Chocó')),
('El Atrato', (SELECT id FROM departments WHERE name = 'Chocó')),
('El Carmen de Atrato', (SELECT id FROM departments WHERE name = 'Chocó')),
('El Carmen del Darién', (SELECT id FROM departments WHERE name = 'Chocó')),
('Istmina', (SELECT id FROM departments WHERE name = 'Chocó')),
('Juradó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Litoral de San Juan', (SELECT id FROM departments WHERE name = 'Chocó')),
('Lloró', (SELECT id FROM departments WHERE name = 'Chocó')),
('Medio Atrato', (SELECT id FROM departments WHERE name = 'Chocó')),
('Medio Baudó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Medio San Juan', (SELECT id FROM departments WHERE name = 'Chocó')),
('Nóvita', (SELECT id FROM departments WHERE name = 'Chocó')),
('Nuquí', (SELECT id FROM departments WHERE name = 'Chocó')),
('Quibdó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Río Iró', (SELECT id FROM departments WHERE name = 'Chocó')),
('Río Quito', (SELECT id FROM departments WHERE name = 'Chocó')),
('Riosucio', (SELECT id FROM departments WHERE name = 'Chocó')),
('San José del Palmar', (SELECT id FROM departments WHERE name = 'Chocó')),
('Sipí', (SELECT id FROM departments WHERE name = 'Chocó')),
('Tadó', (SELECT id FROM departments WHERE name = 'Chocó')),
('Unión Panamericana', (SELECT id FROM departments WHERE name = 'Chocó')),
('Unguía', (SELECT id FROM departments WHERE name = 'Chocó'))
ON CONFLICT DO NOTHING;

-- Insert Cundinamarca municipalities (117)
INSERT INTO municipalities (name, department_id) VALUES
('Agua de Dios', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Albán', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Anapoima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Anolaima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Apulo', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Arbeláez', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Beltrán', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Bituima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Bogotá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Bojacá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cabrera', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cachipay', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cajicá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Caparrapí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cáqueza', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Carmen de Carupa', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Chaguaní', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Chía', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Chipaque', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Choachí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Chocontá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cogua', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cota', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Cucunubá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('El Colegio', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('El Peñón', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('El Rosal', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Facatativá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Fómeque', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Fosca', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Funza', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Fúquene', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Fusagasugá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Gachalá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Gachancipá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Gachetá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Gama', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Girardot', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Granada', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guachetá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guaduas', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guasca', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guataquí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guatavita', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guayabal de Síquima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Guayabetal', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Gutiérrez', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Jerusalén', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Junín', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('La Calera', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('La Mesa', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('La Palma', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('La Peña', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('La Vega', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Lenguazaque', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Machetá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Madrid', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Manta', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Medina', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Mosquera', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Nariño', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Nemocón', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Nilo', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Nimaima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Nocaima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Pacho', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Paime', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Pandi', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Paratebueno', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Pasca', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Puerto Salgar', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Pulí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Quebradanegra', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Quetame', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Quipile', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Ricaurte', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('San Antonio del Tequendama', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('San Bernardo', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('San Cayetano', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('San Francisco', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('San Juan de Rioseco', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Sasaima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Sesquilé', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Sibaté', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Silvania', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Simijaca', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Soacha', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Sopó', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Subachoque', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Suesca', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Supatá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Susa', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Sutatausa', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tabio', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tausa', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tena', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tenjo', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tibacuy', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tibirita', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tocaima', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Tocancipá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Topaipí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Ubalá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Ubaque', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Ubaté', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Une', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Útica', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Venecia', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Vergara', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Vianí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Villagómez', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Villapinzón', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Villeta', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Viotá', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Yacopí', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Zipacón', (SELECT id FROM departments WHERE name = 'Cundinamarca')),
('Zipaquirá', (SELECT id FROM departments WHERE name = 'Cundinamarca'))
ON CONFLICT DO NOTHING;

-- Insert Córdoba municipalities (30)
INSERT INTO municipalities (name, department_id) VALUES
('Ayapel', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Buenavista', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Canalete', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Cereté', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Chimá', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Chinú', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Ciénaga de Oro', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Cotorra', (SELECT id FROM departments WHERE name = 'Córdoba')),
('La Apartada', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Lorica', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Los Córdobas', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Momil', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Montelíbano', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Montería', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Moñitos', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Planeta Rica', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Pueblo Nuevo', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Puerto Escondido', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Puerto Libertador', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Purísima', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Sahagún', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San Andrés de Sotavento', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San Antero', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San Bernardo del Viento', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San Carlos', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San José de Uré', (SELECT id FROM departments WHERE name = 'Córdoba')),
('San Pelayo', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Tierralta', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Tuchín', (SELECT id FROM departments WHERE name = 'Córdoba')),
('Valencia', (SELECT id FROM departments WHERE name = 'Córdoba'))
ON CONFLICT DO NOTHING;

-- Insert Guainía municipalities (1)
INSERT INTO municipalities (name, department_id) VALUES
('Inírida', (SELECT id FROM departments WHERE name = 'Guainía'))
ON CONFLICT DO NOTHING;

-- Insert Guaviare municipalities (4)
INSERT INTO municipalities (name, department_id) VALUES
('Calamar', (SELECT id FROM departments WHERE name = 'Guaviare')),
('El Retorno', (SELECT id FROM departments WHERE name = 'Guaviare')),
('Miraflores', (SELECT id FROM departments WHERE name = 'Guaviare')),
('San José del Guaviare', (SELECT id FROM departments WHERE name = 'Guaviare'))
ON CONFLICT DO NOTHING;

-- Insert Huila municipalities (37)
INSERT INTO municipalities (name, department_id) VALUES
('Acevedo', (SELECT id FROM departments WHERE name = 'Huila')),
('Agrado', (SELECT id FROM departments WHERE name = 'Huila')),
('Aipe', (SELECT id FROM departments WHERE name = 'Huila')),
('Algeciras', (SELECT id FROM departments WHERE name = 'Huila')),
('Altamira', (SELECT id FROM departments WHERE name = 'Huila')),
('Baraya', (SELECT id FROM departments WHERE name = 'Huila')),
('Campoalegre', (SELECT id FROM departments WHERE name = 'Huila')),
('Colombia', (SELECT id FROM departments WHERE name = 'Huila')),
('El Pital', (SELECT id FROM departments WHERE name = 'Huila')),
('Elías', (SELECT id FROM departments WHERE name = 'Huila')),
('Garzón', (SELECT id FROM departments WHERE name = 'Huila')),
('Gigante', (SELECT id FROM departments WHERE name = 'Huila')),
('Guadalupe', (SELECT id FROM departments WHERE name = 'Huila')),
('Hobo', (SELECT id FROM departments WHERE name = 'Huila')),
('Íquira', (SELECT id FROM departments WHERE name = 'Huila')),
('Isnos', (SELECT id FROM departments WHERE name = 'Huila')),
('La Argentina', (SELECT id FROM departments WHERE name = 'Huila')),
('La Plata', (SELECT id FROM departments WHERE name = 'Huila')),
('Nátaga', (SELECT id FROM departments WHERE name = 'Huila')),
('Neiva', (SELECT id FROM departments WHERE name = 'Huila')),
('Oporapa', (SELECT id FROM departments WHERE name = 'Huila')),
('Paicol', (SELECT id FROM departments WHERE name = 'Huila')),
('Palermo', (SELECT id FROM departments WHERE name = 'Huila')),
('Palestina', (SELECT id FROM departments WHERE name = 'Huila')),
('Pitalito', (SELECT id FROM departments WHERE name = 'Huila')),
('Rivera', (SELECT id FROM departments WHERE name = 'Huila')),
('Saladoblanco', (SELECT id FROM departments WHERE name = 'Huila')),
('San Agustín', (SELECT id FROM departments WHERE name = 'Huila')),
('Santa María', (SELECT id FROM departments WHERE name = 'Huila')),
('Suaza', (SELECT id FROM departments WHERE name = 'Huila')),
('Tarqui', (SELECT id FROM departments WHERE name = 'Huila')),
('Tello', (SELECT id FROM departments WHERE name = 'Huila')),
('Teruel', (SELECT id FROM departments WHERE name = 'Huila')),
('Tesalia', (SELECT id FROM departments WHERE name = 'Huila')),
('Timaná', (SELECT id FROM departments WHERE name = 'Huila')),
('Villavieja', (SELECT id FROM departments WHERE name = 'Huila')),
('Yaguará', (SELECT id FROM departments WHERE name = 'Huila'))
ON CONFLICT DO NOTHING;

-- Insert La Guajira municipalities (15)
INSERT INTO municipalities (name, department_id) VALUES
('Albania', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Barrancas', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Dibulla', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Distracción', (SELECT id FROM departments WHERE name = 'La Guajira')),
('El Molino', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Fonseca', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Hatonuevo', (SELECT id FROM departments WHERE name = 'La Guajira')),
('La Jagua del Pilar', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Maicao', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Manaure', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Riohacha', (SELECT id FROM departments WHERE name = 'La Guajira')),
('San Juan del Cesar', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Uribia', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Urumita', (SELECT id FROM departments WHERE name = 'La Guajira')),
('Villanueva', (SELECT id FROM departments WHERE name = 'La Guajira'))
ON CONFLICT DO NOTHING;

-- Insert Magdalena municipalities (31)
INSERT INTO municipalities (name, department_id) VALUES
('Algarrobo', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Aracataca', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Ariguaní', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Cerro de San Antonio', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Chibolo', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Chibolo', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Ciénaga', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Concordia', (SELECT id FROM departments WHERE name = 'Magdalena')),
('El Banco', (SELECT id FROM departments WHERE name = 'Magdalena')),
('El Piñón', (SELECT id FROM departments WHERE name = 'Magdalena')),
('El Retén', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Fundación', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Guamal', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Nueva Granada', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Pedraza', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Pijiño del Carmen', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Pivijay', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Plato', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Pueblo Viejo', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Remolino', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Sabanas de San Ángel', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Salamina', (SELECT id FROM departments WHERE name = 'Magdalena')),
('San Sebastián de Buenavista', (SELECT id FROM departments WHERE name = 'Magdalena')),
('San Zenón', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Santa Ana', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Santa Bárbara de Pinto', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Santa Marta', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Sitionuevo', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Tenerife', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Zapayán', (SELECT id FROM departments WHERE name = 'Magdalena')),
('Zona Bananera', (SELECT id FROM departments WHERE name = 'Magdalena'))
ON CONFLICT DO NOTHING;

-- Insert Meta municipalities (29)
INSERT INTO municipalities (name, department_id) VALUES
('Acacías', (SELECT id FROM departments WHERE name = 'Meta')),
('Barranca de Upía', (SELECT id FROM departments WHERE name = 'Meta')),
('Cabuyaro', (SELECT id FROM departments WHERE name = 'Meta')),
('Castilla la Nueva', (SELECT id FROM departments WHERE name = 'Meta')),
('Cubarral', (SELECT id FROM departments WHERE name = 'Meta')),
('Cumaral', (SELECT id FROM departments WHERE name = 'Meta')),
('El Calvario', (SELECT id FROM departments WHERE name = 'Meta')),
('El Castillo', (SELECT id FROM departments WHERE name = 'Meta')),
('El Dorado', (SELECT id FROM departments WHERE name = 'Meta')),
('Fuente de Oro', (SELECT id FROM departments WHERE name = 'Meta')),
('Granada', (SELECT id FROM departments WHERE name = 'Meta')),
('Guamal', (SELECT id FROM departments WHERE name = 'Meta')),
('La Macarena', (SELECT id FROM departments WHERE name = 'Meta')),
('La Uribe', (SELECT id FROM departments WHERE name = 'Meta')),
('Lejanías', (SELECT id FROM departments WHERE name = 'Meta')),
('Mapiripán', (SELECT id FROM departments WHERE name = 'Meta')),
('Mesetas', (SELECT id FROM departments WHERE name = 'Meta')),
('Puerto Concordia', (SELECT id FROM departments WHERE name = 'Meta')),
('Puerto Gaitán', (SELECT id FROM departments WHERE name = 'Meta')),
('Puerto Lleras', (SELECT id FROM departments WHERE name = 'Meta')),
('Puerto López', (SELECT id FROM departments WHERE name = 'Meta')),
('Puerto Rico', (SELECT id FROM departments WHERE name = 'Meta')),
('Restrepo', (SELECT id FROM departments WHERE name = 'Meta')),
('San Carlos de Guaroa', (SELECT id FROM departments WHERE name = 'Meta')),
('San Juan de Arama', (SELECT id FROM departments WHERE name = 'Meta')),
('San Juanito', (SELECT id FROM departments WHERE name = 'Meta')),
('San Martín', (SELECT id FROM departments WHERE name = 'Meta')),
('Villavicencio', (SELECT id FROM departments WHERE name = 'Meta')),
('Vista Hermosa', (SELECT id FROM departments WHERE name = 'Meta'))
ON CONFLICT DO NOTHING;

-- Insert Nariño municipalities (64)
INSERT INTO municipalities (name, department_id) VALUES
('Aldana', (SELECT id FROM departments WHERE name = 'Nariño')),
('Ancuyá', (SELECT id FROM departments WHERE name = 'Nariño')),
('Arboleda', (SELECT id FROM departments WHERE name = 'Nariño')),
('Barbacoas', (SELECT id FROM departments WHERE name = 'Nariño')),
('Belén', (SELECT id FROM departments WHERE name = 'Nariño')),
('Buesaco', (SELECT id FROM departments WHERE name = 'Nariño')),
('Chachagüí', (SELECT id FROM departments WHERE name = 'Nariño')),
('Colón', (SELECT id FROM departments WHERE name = 'Nariño')),
('Consacá', (SELECT id FROM departments WHERE name = 'Nariño')),
('Contadero', (SELECT id FROM departments WHERE name = 'Nariño')),
('Córdoba', (SELECT id FROM departments WHERE name = 'Nariño')),
('Cuaspud', (SELECT id FROM departments WHERE name = 'Nariño')),
('Cumbal', (SELECT id FROM departments WHERE name = 'Nariño')),
('Cumbitara', (SELECT id FROM departments WHERE name = 'Nariño')),
('El Charco', (SELECT id FROM departments WHERE name = 'Nariño')),
('El Peñol', (SELECT id FROM departments WHERE name = 'Nariño')),
('El Rosario', (SELECT id FROM departments WHERE name = 'Nariño')),
('El Tablón', (SELECT id FROM departments WHERE name = 'Nariño')),
('El Tambo', (SELECT id FROM departments WHERE name = 'Nariño')),
('Francisco Pizarro', (SELECT id FROM departments WHERE name = 'Nariño')),
('Funes', (SELECT id FROM departments WHERE name = 'Nariño')),
('Guachucal', (SELECT id FROM departments WHERE name = 'Nariño')),
('Guaitarilla', (SELECT id FROM departments WHERE name = 'Nariño')),
('Gualmatán', (SELECT id FROM departments WHERE name = 'Nariño')),
('Iles', (SELECT id FROM departments WHERE name = 'Nariño')),
('Imués', (SELECT id FROM departments WHERE name = 'Nariño')),
('Ipiales', (SELECT id FROM departments WHERE name = 'Nariño')),
('La Cruz', (SELECT id FROM departments WHERE name = 'Nariño')),
('La Florida', (SELECT id FROM departments WHERE name = 'Nariño')),
('La Llanada', (SELECT id FROM departments WHERE name = 'Nariño')),
('La Tola', (SELECT id FROM departments WHERE name = 'Nariño')),
('La Unión', (SELECT id FROM departments WHERE name = 'Nariño')),
('Leiva', (SELECT id FROM departments WHERE name = 'Nariño')),
('Linares', (SELECT id FROM departments WHERE name = 'Nariño')),
('Los Andes', (SELECT id FROM departments WHERE name = 'Nariño')),
('Magüí Payán', (SELECT id FROM departments WHERE name = 'Nariño')),
('Mallama', (SELECT id FROM departments WHERE name = 'Nariño')),
('Mosquera', (SELECT id FROM departments WHERE name = 'Nariño')),
('Nariño', (SELECT id FROM departments WHERE name = 'Nariño')),
('Olaya Herrera', (SELECT id FROM departments WHERE name = 'Nariño')),
('Ospina', (SELECT id FROM departments WHERE name = 'Nariño')),
('Pasto', (SELECT id FROM departments WHERE name = 'Nariño')),
('Policarpa', (SELECT id FROM departments WHERE name = 'Nariño')),
('Potosí', (SELECT id FROM departments WHERE name = 'Nariño')),
('Providencia', (SELECT id FROM departments WHERE name = 'Nariño')),
('Puerres', (SELECT id FROM departments WHERE name = 'Nariño')),
('Pupiales', (SELECT id FROM departments WHERE name = 'Nariño')),
('Ricaurte', (SELECT id FROM departments WHERE name = 'Nariño')),
('Roberto Payán', (SELECT id FROM departments WHERE name = 'Nariño')),
('Samaniego', (SELECT id FROM departments WHERE name = 'Nariño')),
('San Bernardo', (SELECT id FROM departments WHERE name = 'Nariño')),
('San José de Albán', (SELECT id FROM departments WHERE name = 'Nariño')),
('San Lorenzo', (SELECT id FROM departments WHERE name = 'Nariño')),
('San Pablo', (SELECT id FROM departments WHERE name = 'Nariño')),
('San Pedro de Cartago', (SELECT id FROM departments WHERE name = 'Nariño')),
('Sandoná', (SELECT id FROM departments WHERE name = 'Nariño')),
('Santa Bárbara', (SELECT id FROM departments WHERE name = 'Nariño')),
('Santacruz', (SELECT id FROM departments WHERE name = 'Nariño')),
('Sapuyes', (SELECT id FROM departments WHERE name = 'Nariño')),
('Taminango', (SELECT id FROM departments WHERE name = 'Nariño')),
('Tangua', (SELECT id FROM departments WHERE name = 'Nariño')),
('Tumaco', (SELECT id FROM departments WHERE name = 'Nariño')),
('Túquerres', (SELECT id FROM departments WHERE name = 'Nariño')),
('Yacuanquer', (SELECT id FROM departments WHERE name = 'Nariño'))
ON CONFLICT DO NOTHING;

-- Insert Norte de Santander municipalities (40)
INSERT INTO municipalities (name, department_id) VALUES
('Ábrego', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Arboledas', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Bochalema', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Bucarasica', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Cáchira', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Cácota', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Chinácota', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Chitagá', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Convención', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Cúcuta', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Cucutilla', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Duranía', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('El Carmen', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('El Tarra', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('El Zulia', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Gramalote', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Hacarí', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Herrán', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('La Esperanza', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('La Playa de Belén', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Labateca', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Los Patios', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Lourdes', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Mutiscua', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Ocaña', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Pamplona', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Pamplonita', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Puerto Santander', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Ragonvalia', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Salazar de Las Palmas', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('San Calixto', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('San Cayetano', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Santiago', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Santo Domingo de Silos', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Sardinata', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Teorama', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Tibú', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Toledo', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Villa Caro', (SELECT id FROM departments WHERE name = 'Norte de Santander')),
('Villa del Rosario', (SELECT id FROM departments WHERE name = 'Norte de Santander'))
ON CONFLICT DO NOTHING;

-- Insert Putumayo municipalities (13)
INSERT INTO municipalities (name, department_id) VALUES
('Colón', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Mocoa', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Orito', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Puerto Asís', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Puerto Caicedo', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Puerto Guzmán', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Puerto Leguízamo', (SELECT id FROM departments WHERE name = 'Putumayo')),
('San Francisco', (SELECT id FROM departments WHERE name = 'Putumayo')),
('San Miguel', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Santiago', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Sibundoy', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Valle del Guamuez', (SELECT id FROM departments WHERE name = 'Putumayo')),
('Villagarzón', (SELECT id FROM departments WHERE name = 'Putumayo'))
ON CONFLICT DO NOTHING;

-- Insert Quindío municipalities (12)
INSERT INTO municipalities (name, department_id) VALUES
('Armenia', (SELECT id FROM departments WHERE name = 'Quindío')),
('Buenavista', (SELECT id FROM departments WHERE name = 'Quindío')),
('Calarcá', (SELECT id FROM departments WHERE name = 'Quindío')),
('Circasia', (SELECT id FROM departments WHERE name = 'Quindío')),
('Córdoba', (SELECT id FROM departments WHERE name = 'Quindío')),
('Filandia', (SELECT id FROM departments WHERE name = 'Quindío')),
('Génova', (SELECT id FROM departments WHERE name = 'Quindío')),
('La Tebaida', (SELECT id FROM departments WHERE name = 'Quindío')),
('Montenegro', (SELECT id FROM departments WHERE name = 'Quindío')),
('Pijao', (SELECT id FROM departments WHERE name = 'Quindío')),
('Quimbaya', (SELECT id FROM departments WHERE name = 'Quindío')),
('Salento', (SELECT id FROM departments WHERE name = 'Quindío'))
ON CONFLICT DO NOTHING;

-- Insert Risaralda municipalities (14)
INSERT INTO municipalities (name, department_id) VALUES
('Apía', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Balboa', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Belén de Umbría', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Dosquebradas', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Guática', (SELECT id FROM departments WHERE name = 'Risaralda')),
('La Celia', (SELECT id FROM departments WHERE name = 'Risaralda')),
('La Virginia', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Marsella', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Mistrató', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Pereira', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Pueblo Rico', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Quinchía', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Santa Rosa de Cabal', (SELECT id FROM departments WHERE name = 'Risaralda')),
('Santuario', (SELECT id FROM departments WHERE name = 'Risaralda'))
ON CONFLICT DO NOTHING;

-- Insert San Andrés y Providencia municipalities (2)
INSERT INTO municipalities (name, department_id) VALUES
('Providencia y Santa Catalina Islas', (SELECT id FROM departments WHERE name = 'San Andrés y Providencia')),
('San Andrés', (SELECT id FROM departments WHERE name = 'San Andrés y Providencia'))
ON CONFLICT DO NOTHING;

-- Insert Santander municipalities (87)
INSERT INTO municipalities (name, department_id) VALUES
('Aguada', (SELECT id FROM departments WHERE name = 'Santander')),
('Albania', (SELECT id FROM departments WHERE name = 'Santander')),
('Aratoca', (SELECT id FROM departments WHERE name = 'Santander')),
('Barbosa', (SELECT id FROM departments WHERE name = 'Santander')),
('Barichara', (SELECT id FROM departments WHERE name = 'Santander')),
('Barrancabermeja', (SELECT id FROM departments WHERE name = 'Santander')),
('Betulia', (SELECT id FROM departments WHERE name = 'Santander')),
('Bolívar', (SELECT id FROM departments WHERE name = 'Santander')),
('Bucaramanga', (SELECT id FROM departments WHERE name = 'Santander')),
('Cabrera', (SELECT id FROM departments WHERE name = 'Santander')),
('California', (SELECT id FROM departments WHERE name = 'Santander')),
('Capitanejo', (SELECT id FROM departments WHERE name = 'Santander')),
('Carcasí', (SELECT id FROM departments WHERE name = 'Santander')),
('Cepitá', (SELECT id FROM departments WHERE name = 'Santander')),
('Cerrito', (SELECT id FROM departments WHERE name = 'Santander')),
('Charalá', (SELECT id FROM departments WHERE name = 'Santander')),
('Charta', (SELECT id FROM departments WHERE name = 'Santander')),
('Chima', (SELECT id FROM departments WHERE name = 'Santander')),
('Chipatá', (SELECT id FROM departments WHERE name = 'Santander')),
('Cimitarra', (SELECT id FROM departments WHERE name = 'Santander')),
('Concepción', (SELECT id FROM departments WHERE name = 'Santander')),
('Confines', (SELECT id FROM departments WHERE name = 'Santander')),
('Contratación', (SELECT id FROM departments WHERE name = 'Santander')),
('Coromoro', (SELECT id FROM departments WHERE name = 'Santander')),
('Curití', (SELECT id FROM departments WHERE name = 'Santander')),
('El Carmen de Chucurí', (SELECT id FROM departments WHERE name = 'Santander')),
('El Guacamayo', (SELECT id FROM departments WHERE name = 'Santander')),
('El Peñón', (SELECT id FROM departments WHERE name = 'Santander')),
('El Playón', (SELECT id FROM departments WHERE name = 'Santander')),
('El Socorro', (SELECT id FROM departments WHERE name = 'Santander')),
('Encino', (SELECT id FROM departments WHERE name = 'Santander')),
('Enciso', (SELECT id FROM departments WHERE name = 'Santander')),
('Florián', (SELECT id FROM departments WHERE name = 'Santander')),
('Floridablanca', (SELECT id FROM departments WHERE name = 'Santander')),
('Galán', (SELECT id FROM departments WHERE name = 'Santander')),
('Gámbita', (SELECT id FROM departments WHERE name = 'Santander')),
('Girón', (SELECT id FROM departments WHERE name = 'Santander')),
('Guaca', (SELECT id FROM departments WHERE name = 'Santander')),
('Guadalupe', (SELECT id FROM departments WHERE name = 'Santander')),
('Guapotá', (SELECT id FROM departments WHERE name = 'Santander')),
('Guavatá', (SELECT id FROM departments WHERE name = 'Santander')),
('Güepsa', (SELECT id FROM departments WHERE name = 'Santander')),
('Hato', (SELECT id FROM departments WHERE name = 'Santander')),
('Jesús María', (SELECT id FROM departments WHERE name = 'Santander')),
('Jordán', (SELECT id FROM departments WHERE name = 'Santander')),
('La Belleza', (SELECT id FROM departments WHERE name = 'Santander')),
('La Paz', (SELECT id FROM departments WHERE name = 'Santander')),
('Landázuri', (SELECT id FROM departments WHERE name = 'Santander')),
('Lebrija', (SELECT id FROM departments WHERE name = 'Santander')),
('Los Santos', (SELECT id FROM departments WHERE name = 'Santander')),
('Macaravita', (SELECT id FROM departments WHERE name = 'Santander')),
('Málaga', (SELECT id FROM departments WHERE name = 'Santander')),
('Matanza', (SELECT id FROM departments WHERE name = 'Santander')),
('Mogotes', (SELECT id FROM departments WHERE name = 'Santander')),
('Molagavita', (SELECT id FROM departments WHERE name = 'Santander')),
('Ocamonte', (SELECT id FROM departments WHERE name = 'Santander')),
('Oiba', (SELECT id FROM departments WHERE name = 'Santander')),
('Onzaga', (SELECT id FROM departments WHERE name = 'Santander')),
('Palmar', (SELECT id FROM departments WHERE name = 'Santander')),
('Palmas del Socorro', (SELECT id FROM departments WHERE name = 'Santander')),
('Páramo', (SELECT id FROM departments WHERE name = 'Santander')),
('Piedecuesta', (SELECT id FROM departments WHERE name = 'Santander')),
('Pinchote', (SELECT id FROM departments WHERE name = 'Santander')),
('Puente Nacional', (SELECT id FROM departments WHERE name = 'Santander')),
('Puerto Parra', (SELECT id FROM departments WHERE name = 'Santander')),
('Puerto Wilches', (SELECT id FROM departments WHERE name = 'Santander')),
('Rionegro', (SELECT id FROM departments WHERE name = 'Santander')),
('Sabana de Torres', (SELECT id FROM departments WHERE name = 'Santander')),
('San Andrés', (SELECT id FROM departments WHERE name = 'Santander')),
('San Benito', (SELECT id FROM departments WHERE name = 'Santander')),
('San Gil', (SELECT id FROM departments WHERE name = 'Santander')),
('San Joaquín', (SELECT id FROM departments WHERE name = 'Santander')),
('San José de Miranda', (SELECT id FROM departments WHERE name = 'Santander')),
('San Miguel', (SELECT id FROM departments WHERE name = 'Santander')),
('San Vicente de Chucurí', (SELECT id FROM departments WHERE name = 'Santander')),
('Santa Bárbara', (SELECT id FROM departments WHERE name = 'Santander')),
('Santa Helena del Opón', (SELECT id FROM departments WHERE name = 'Santander')),
('Simacota', (SELECT id FROM departments WHERE name = 'Santander')),
('Suaita', (SELECT id FROM departments WHERE name = 'Santander')),
('Sucre', (SELECT id FROM departments WHERE name = 'Santander')),
('Suratá', (SELECT id FROM departments WHERE name = 'Santander')),
('Tona', (SELECT id FROM departments WHERE name = 'Santander')),
('Valle de San José', (SELECT id FROM departments WHERE name = 'Santander')),
('Vélez', (SELECT id FROM departments WHERE name = 'Santander')),
('Vetas', (SELECT id FROM departments WHERE name = 'Santander')),
('Villanueva', (SELECT id FROM departments WHERE name = 'Santander')),
('Zapatoca', (SELECT id FROM departments WHERE name = 'Santander'))
ON CONFLICT DO NOTHING;

-- Insert Sucre municipalities (26)
INSERT INTO municipalities (name, department_id) VALUES
('Buenavista', (SELECT id FROM departments WHERE name = 'Sucre')),
('Caimito', (SELECT id FROM departments WHERE name = 'Sucre')),
('Chalán', (SELECT id FROM departments WHERE name = 'Sucre')),
('Colosó', (SELECT id FROM departments WHERE name = 'Sucre')),
('Corozal', (SELECT id FROM departments WHERE name = 'Sucre')),
('Coveñas', (SELECT id FROM departments WHERE name = 'Sucre')),
('El Roble', (SELECT id FROM departments WHERE name = 'Sucre')),
('Galeras', (SELECT id FROM departments WHERE name = 'Sucre')),
('Guaranda', (SELECT id FROM departments WHERE name = 'Sucre')),
('La Unión', (SELECT id FROM departments WHERE name = 'Sucre')),
('Los Palmitos', (SELECT id FROM departments WHERE name = 'Sucre')),
('Majagual', (SELECT id FROM departments WHERE name = 'Sucre')),
('Morroa', (SELECT id FROM departments WHERE name = 'Sucre')),
('Ovejas', (SELECT id FROM departments WHERE name = 'Sucre')),
('Sampués', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Antonio de Palmito', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Benito Abad', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Juan de Betulia', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Marcos', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Onofre', (SELECT id FROM departments WHERE name = 'Sucre')),
('San Pedro', (SELECT id FROM departments WHERE name = 'Sucre')),
('Sincé', (SELECT id FROM departments WHERE name = 'Sucre')),
('Sincelejo', (SELECT id FROM departments WHERE name = 'Sucre')),
('Sucre', (SELECT id FROM departments WHERE name = 'Sucre')),
('Tolú', (SELECT id FROM departments WHERE name = 'Sucre')),
('Tolú Viejo', (SELECT id FROM departments WHERE name = 'Sucre'))
ON CONFLICT DO NOTHING;

-- Insert Tolima municipalities (47)
INSERT INTO municipalities (name, department_id) VALUES
('Alpujarra', (SELECT id FROM departments WHERE name = 'Tolima')),
('Alvarado', (SELECT id FROM departments WHERE name = 'Tolima')),
('Ambalema', (SELECT id FROM departments WHERE name = 'Tolima')),
('Anzoátegui', (SELECT id FROM departments WHERE name = 'Tolima')),
('Armero', (SELECT id FROM departments WHERE name = 'Tolima')),
('Ataco', (SELECT id FROM departments WHERE name = 'Tolima')),
('Cajamarca', (SELECT id FROM departments WHERE name = 'Tolima')),
('Carmen de Apicalá', (SELECT id FROM departments WHERE name = 'Tolima')),
('Casabianca', (SELECT id FROM departments WHERE name = 'Tolima')),
('Chaparral', (SELECT id FROM departments WHERE name = 'Tolima')),
('Coello', (SELECT id FROM departments WHERE name = 'Tolima')),
('Coyaima', (SELECT id FROM departments WHERE name = 'Tolima')),
('Cunday', (SELECT id FROM departments WHERE name = 'Tolima')),
('Dolores', (SELECT id FROM departments WHERE name = 'Tolima')),
('El Espinal', (SELECT id FROM departments WHERE name = 'Tolima')),
('Falán', (SELECT id FROM departments WHERE name = 'Tolima')),
('Flandes', (SELECT id FROM departments WHERE name = 'Tolima')),
('Fresno', (SELECT id FROM departments WHERE name = 'Tolima')),
('Guamo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Herveo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Honda', (SELECT id FROM departments WHERE name = 'Tolima')),
('Ibagué', (SELECT id FROM departments WHERE name = 'Tolima')),
('Icononzo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Lérida', (SELECT id FROM departments WHERE name = 'Tolima')),
('Líbano', (SELECT id FROM departments WHERE name = 'Tolima')),
('Mariquita', (SELECT id FROM departments WHERE name = 'Tolima')),
('Melgar', (SELECT id FROM departments WHERE name = 'Tolima')),
('Murillo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Natagaima', (SELECT id FROM departments WHERE name = 'Tolima')),
('Ortega', (SELECT id FROM departments WHERE name = 'Tolima')),
('Palocabildo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Piedras', (SELECT id FROM departments WHERE name = 'Tolima')),
('Planadas', (SELECT id FROM departments WHERE name = 'Tolima')),
('Prado', (SELECT id FROM departments WHERE name = 'Tolima')),
('Purificación', (SELECT id FROM departments WHERE name = 'Tolima')),
('Rioblanco', (SELECT id FROM departments WHERE name = 'Tolima')),
('Roncesvalles', (SELECT id FROM departments WHERE name = 'Tolima')),
('Rovira', (SELECT id FROM departments WHERE name = 'Tolima')),
('Saldaña', (SELECT id FROM departments WHERE name = 'Tolima')),
('San Antonio', (SELECT id FROM departments WHERE name = 'Tolima')),
('San Luis', (SELECT id FROM departments WHERE name = 'Tolima')),
('Santa Isabel', (SELECT id FROM departments WHERE name = 'Tolima')),
('Suárez', (SELECT id FROM departments WHERE name = 'Tolima')),
('Valle de San Juan', (SELECT id FROM departments WHERE name = 'Tolima')),
('Venadillo', (SELECT id FROM departments WHERE name = 'Tolima')),
('Villahermosa', (SELECT id FROM departments WHERE name = 'Tolima')),
('Villarrica', (SELECT id FROM departments WHERE name = 'Tolima'))
ON CONFLICT DO NOTHING;

-- Insert Valle del Cauca municipalities (42)
INSERT INTO municipalities (name, department_id) VALUES
('Alcalá', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Andalucía', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Ansermanuevo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Argelia', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Bolívar', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Buenaventura', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Buga', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Bugalagrande', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Caicedonia', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Cali', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Calima', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Candelaria', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Cartago', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Dagua', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('El Águila', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('El Cairo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('El Cerrito', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('El Dovio', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Florida', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Ginebra', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Guacarí', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Jamundí', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('La Cumbre', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('La Unión', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('La Victoria', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Obando', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Palmira', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Pradera', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Restrepo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Riofrío', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Roldanillo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('San Pedro', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Sevilla', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Toro', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Trujillo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Tuluá', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Ulloa', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Versalles', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Vijes', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Yotoco', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Yumbo', (SELECT id FROM departments WHERE name = 'Valle del Cauca')),
('Zarzal', (SELECT id FROM departments WHERE name = 'Valle del Cauca'))
ON CONFLICT DO NOTHING;

-- Insert Vaupés municipalities (3)
INSERT INTO municipalities (name, department_id) VALUES
('Carurú', (SELECT id FROM departments WHERE name = 'Vaupés')),
('Mitú', (SELECT id FROM departments WHERE name = 'Vaupés')),
('Taraira', (SELECT id FROM departments WHERE name = 'Vaupés'))
ON CONFLICT DO NOTHING;

-- Insert Vichada municipalities (4)
INSERT INTO municipalities (name, department_id) VALUES
('Cumaribo', (SELECT id FROM departments WHERE name = 'Vichada')),
('La Primavera', (SELECT id FROM departments WHERE name = 'Vichada')),
('Puerto Carreño', (SELECT id FROM departments WHERE name = 'Vichada')),
('Santa Rosalía', (SELECT id FROM departments WHERE name = 'Vichada'))
ON CONFLICT DO NOTHING;
