-- UPDATE de criterios desde Excel Resolucion 3100-2019
-- Solo los 68 criterios con nombre truncado a 255 chars

UPDATE evaluation_criteria SET name = '1. El talento humano en salud y otros profesionales que se relacionan con la atención o resultados en salud de los usuarios, cuentan con los titulos, según aplique, de educación superior o certificados de aptitud ocupacional, expedidos por la entidad educativa competente. En el caso de títulos o certificados obtenidos en el extranjero, copia de la resolución de convalidación expedida por el Ministerio de Educación Nacional' WHERE code = 'TSTH-001';
UPDATE evaluation_criteria SET name = '3. El prestador de servicios de salud determina la cantidad necesaria de talento humano requerido para cada uno de los servicios ofertados y prestados, de acuerdo con la capacidad instalada, la relación entre la oferta y demanda, la oportunidad en la prestación, tiempo de la atención y el riesgo en la atención. Este criterio no aplica para profesionales independientes de salud' WHERE code = 'TSTH-003';
UPDATE evaluation_criteria SET name = '4.3. Estudio de la capacidad instalada en el cual se dtermine el número máximo de estudiantes que simultaneamente puedan acceder por programa de formación y por jornada, para cada uno de los servicios que se utilicen como escenarios de práctica formativa en el área de la salud, estudio que debe ser elaborado teniendo en cuenta los "lineamientos de referencia para la asignación de cupos de estudiantes en escenarios clinicos" publicados por el Ministerio de Salud y Protección Social' WHERE code = 'TSTH-007';
UPDATE evaluation_criteria SET name = '5. En los servicios de salud diferentes a los servicios de consulta externa especializada de dolor y cuidado paliativo, donde se atienden pacientes con enfermedades terminales, crónicas, degenerativas e irreversibles, a los cuales se les decida como conducta médica: como parte del plan integral de cuidado que gestiona el equipo de salud, o por solicitud del paciente; el manejo de dolor y cuidado paliativo, el profesional en medicina tratante cuenta con constancia de asistencia en las acciones de formación continua en el manejo de dolor y cuidado paliativo, cuando no sea especialista en dolor y cuidado paliativo' WHERE code = 'TSTH-008';
UPDATE evaluation_criteria SET name = '7. En los servicios de salud donde se realicen imagenes diagnósticas por ultrasonido, cuenta con médico especialista en radiologia e imagenes diagnósticas también podrán realizar imagenes diagnósticas aquellos médicos especialistas, quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnetico, del ultrasonido especialmente, así como de la radiaciones ionizantes para establecer el diagnóstico o el tratamiento de las enfermedades inherentes a su especialidad, para lo cual deberá acreditar el respectivo certificado.' WHERE code = 'TSTH-010';
UPDATE evaluation_criteria SET name = '8. Los profesionales de la medicina de los servicios de hospitalización de baja, mediana y alta complejidad, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediátricos y adultos; urgencias, y servicios del grupo quirurgico en modalidad intramural,cuentan con certificación vigente de aprobación de la evaluación de competencias esenciales para el cuidado de la donante expedida por el Instituto Nacional de Salud.' WHERE code = 'TSTH-011';
UPDATE evaluation_criteria SET name = '10. El talento humano en salud de los servicios de salud de los grupos de consulta externa, internación y el servicio de urgencias, cuentan con constancia de asistencia en las acciones de formación continua en la atención integral en salud de las personas victimas de violencia sexual.' WHERE code = 'TSTH-013';
UPDATE evaluation_criteria SET name = '11. El talento humano en salud de los servicios de transporte asistencial, atención prehospitalaria y urgencias, cuentasn con constancia de asistencia en las acciones de formación continua en la atención a personas víctimas de ataques con agentes químicos.' WHERE code = 'TSTH-014';
UPDATE evaluation_criteria SET name = '12. Cuando en un servicio de salud se realicen "pruebas en punto de atención del paciente - (point of care testing - POCT)", el talento humano en salud qeu las realice, a excepción del profesional en bacteriologia cuenta con constancia de asistencia en las acciones de formación continua en la atención a personas víctimas de ataques con agentes químicos.' WHERE code = 'TSTH-015';
UPDATE evaluation_criteria SET name = '13.1.1. Profesional en la medicina especialista en anestesiologia, o profesional de la medicina o profesional en odontologia, según aplique, el cual será el encargado de administrar el medicamento y realizar el monitoreo continuo del paciente (registro de signos vitales y la respuesta a la sedación)' WHERE code = 'TSTH-018';
UPDATE evaluation_criteria SET name = '13.2. Cuando fuera de las salas de cirugia, se realicen procedimientos bajo sedación grado III, adicional al profesional de salud que realiza el procedimiento, cuenta con profesional de la medicina con especialidad médico - quirúrgica, quién será el responsable de administrar la sedación' WHERE code = 'TSTH-021';
UPDATE evaluation_criteria SET name = '13.3. Cuando fuera de las salas de cirugía, se realicen procedimientos bajo sedación grado IV, adicional al profesional de  salud que realiza el procedimiento, cuenta con profesional de la medicina especialisa en anestesiologia, quién será el responsable de administrar la sedación' WHERE code = 'TSTH-022';
UPDATE evaluation_criteria SET name = '13.4 Cuenta con profesional de la medicina especialista en anestesiologia cuando la atención de trate de pacientes con caracteristicas particulares: poco colaboradores; edades extremas; con enfermedades severas:cardíacas, pulmonares, hepáticas, renales o del sistema nervioso central;cualquier alteración del grado de consciencia, con obesidad mórbida, con apnea del sueño, embarazadas, o quienes abusan del alcohol o de las drogas; antecedentes de sedación fallida o que presentaron efectos adversos a algún medicamento utilizado en la sedación, por tener un elevado riesgo de desarrollar complicaciones relacionadas con la sedación analgesia' WHERE code = 'TSTH-023';
UPDATE evaluation_criteria SET name = '14. Adicional a los criterios del estándar de talento humano enunciados que le aplique, el talento humano en salud que preste directamente un servicio de salud bajo la modalidad telemedicina cuentan con constancia de asistencia en las acciones de formación continua en el manejo de tecnología utilizada por el prestador, los procesos y herramientas inherentes a la prestación de servicios bajo esta modalidad' WHERE code = 'TSTH-025';
UPDATE evaluation_criteria SET name = '3. Cuando en una edificación de uso exclusivo de salud funcione más de un prestador de servicios de salud con servicios de los grupos de consulta externa y apoyo diagnóstico y complementación terapeutica, cada prestador cuenta con infraestructura separada delimitada fisicamente. Se pueden compartir los siguientes ambientes y áreas: aseo, salas de espera y unidades sanitarias.' WHERE code = 'TSINF-004';
UPDATE evaluation_criteria SET name = '4. Las edificaciones donde se presten servicios de salud de urgencias y del grupo de internación, cuentan con tanque de almacenamientode agua para el consumo humano que garantice como mínimo una reserva de 24 horas de servicio continuo, calculando con base en el consumo de 600 lt por cama/camilla al día.' WHERE code = 'TSINF-005';
UPDATE evaluation_criteria SET name = '5. Cuando el prestador de servicios de salud cuente con mas de una infraestructura y estas se puedan vincular funcionalmente entre si, lo harán mediante tunel o puente cubierto, o muro(s) colindante(s) que cuenten con acceso (s) que intercomuniquen las infraestructuras, de uso exclusivo del prestador y adicionalmente cumplen con las siguientes caracteristicas:' WHERE code = 'TSINF-006';
UPDATE evaluation_criteria SET name = '7. En edificaciones de uso mixto pueden funsionar los prestadores de servicios de salud que oferten y presten servicios de los grupos de consulta externa. de apoyo diagnóstico y complementación terapeutica y los servicios del grupo quirurgico que realicen exclusivamente procedimientos de cirugia ambulatoria.' WHERE code = 'TSINF-013';
UPDATE evaluation_criteria SET name = '8. Los prestadores de servicios de salud ubicados en edificaciones de hasta tres (3) pisos o niveles contados a partir del nivel más bajo construido, y que funcione en segundo o tercer nivel o piso, cuentan con ascensor o rampa o sistema alternativo de elevación. El sistema alternativo de elevación no puede ser utilizado cuando se presten servicios hospitalarios, cirugía, urgencias o de atención del parto.' WHERE code = 'TSINF-015';
UPDATE evaluation_criteria SET name = '11. En edificaciones donde se presten servicios de los grupos de internación, atención del parto, quirurgicos o urgencias para la movilización de pacientes en camilla, la cabina de los ascensores debe tener las dimensiones interiores mínimas de 2.20 de profundidad y de 1.20 ancho, que garanticen el traslado seguro de los pacientes. Las dimensiones de la cabina podrán ser variables en el o los ascensores que el prestador determine para la movilización de usuarios a pie o en silla de ruedas.' WHERE code = 'TSINF-022';
UPDATE evaluation_criteria SET name = '14. En edificaciones donde se presten servicios de cirugía, atención del parto, laboratorio clínico, urgencias, gestión pre transfusional, dialisis, hospitalarios, imagénes diagnósticas, vacunación, servicio farmaceutico y los que requieran cadena de frio, cuentan con planta electrica.' WHERE code = 'TSINF-025';
UPDATE evaluation_criteria SET name = '17. Cada prestador de servicios de salud debe contar con el respectivo concepto sanitario que dé cumplimiento a lo establecido en la normatividad sanitaria vigente en aspectos tales como agua para consumo humano, gestión de residuos, control de vectores, orden y aseo, condiciones locativas, entre otros. Este concepto será emitido por las autoridades sanitarias correspondientes, en el marco de sus competencias, y debe considerar los servicios de apoyo como lavanderia y servicio de alimentación.

Cuando estos servicios de apoyo son contratados con terceros dichos proveedores deben contar con el concepto sanitario correspondiente a la actividad de bienes y servicios que presta.' WHERE code = 'TSINF-028';
UPDATE evaluation_criteria SET name = '21.En los servicios del grupo quirurgico, los ambientes y áreas clasificados como no restringidos, semirestringidos, deben señalizarse mediante la demarcación permanente en piso con material lavable y resistente al tráfico pesado, utilizando los siguientes colores' WHERE code = 'TSINF-033';
UPDATE evaluation_criteria SET name = '23. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre-transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios habilitados, tiene disponibilidad de un área con iluminación y ventilación natural o artificial, para la ubicación de la dotación requerida de acuerdo con los componentes sanguíneos a transfundir.' WHERE code = 'TSINF-038';
UPDATE evaluation_criteria SET name = '24. Cuando un prestador de servicios de salud realice procedimientos bajo sedación fuera de salas de cirugía, tiene disponibilidad de área o ambiente para la recuperación de pacientes que puede ser la misma área o ambiente donde se realiza el procedimiento, garantizando la privacidad del usuario.' WHERE code = 'TSINF-039';
UPDATE evaluation_criteria SET name = '39. Bateria sanitaria, ambiente que cuenta con sanitarios en serie y lavamanos, discriminadas por sexo, serán separadas con barreras físicas fijas o divisiones en materiales resistentes, inoxidables e impermeables, con espacios libres que faciliten la ventilación y las labores de aseo. Se instalará adicionalmente un orinal para sexomasculino. Como mínimo uno de los sanitarios de la bateria debe ser apto para personas com movilidad reducida discriminado por sexo.' WHERE code = 'TSINF-145';
UPDATE evaluation_criteria SET name = '42. En las edificaciones destinadas a la prestación de servicios de salud, los pisos deben ser resistentes a factores ambientales, deben ser continuos, antideslizantes, impermeables, lavables, sólidos, resistentes a procesos de lavado y desinfección. Cuando se tengan dilataciones y juntas, estas deben ser selladas de manera que ofrezcan continuidad de la superficie.' WHERE code = 'TSINF-151';
UPDATE evaluation_criteria SET name = '44. En los servicios de cirugía, atención del parto, ambiente TPR, salas de procedimientos, consultorios donde se realicen procedimientos, servicios de internación en cuidado básico, intermedio e intensivo, urgencias, diálisis, hemodinámia e intervencionismo, laboratorios, gestión pre transfunsional, quimioterapia, consulta odontológica y los ambientes o áreas donde se requieran procesos de limpieza y asepsia más profundos, adicional al criterio anterior, la unión entre paredes o muros y el piso debe ser en media caña evitando la formación de aristas o de esquinas.' WHERE code = 'TSINF-153';
UPDATE evaluation_criteria SET name = '45. En los servicios de cirugía, atención del parto, ambiente TPR y el ambiente de esterilización, la unión entre cielo raso o techo y la pared o muro y la unión entre paredes o muros, debe contar con media caña, evitando la formación de aristas o de esquinas.' WHERE code = 'TSINF-154';
UPDATE evaluation_criteria SET name = '51.2. Plataformas tecnológicas que garanticen la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicios de salud, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividad o lineamientos que regulen la materia.' WHERE code = 'TSINF-182';
UPDATE evaluation_criteria SET name = '52.2. Plataformas tecnológicas que garanticen la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicio de salud, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividado lineamientos que regulen la materia.' WHERE code = 'TSINF-188';
UPDATE evaluation_criteria SET name = '53.1. Ambiente exclusivo para la realización de la atención a distancia que garantiza la privacidad y la confidencialidad durante la atención, la seguridad de los equipos frente a la extracciónno autorizada y condiciones ambientales para su correcto funcionamiento,libre de interferencias visuales y sonoras.' WHERE code = 'TSINF-193';
UPDATE evaluation_criteria SET name = '53.3. Plataformas tecnológicas que garantizan la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicios, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividad que regule la materia.' WHERE code = 'TSINF-195';
UPDATE evaluation_criteria SET name = '2.1. Programa de mantenimiento preventivo de los equipos biomédicos, que incluya el cumplimiento de las recomendaciones establecidas por el fabricante o de acuerdo con el protocolo de mantenimiento que tenga definido el prestador, éste último cuando no esté definido por el fabricante.' WHERE code = 'TSDOT-009';
UPDATE evaluation_criteria SET name = '6. El mantenimiento de los equipos biomédicos es ejecutado por el talento humano profesional, tecnólogo o técnico en áreas relacionadas. Este mantenimiento puede ser realizado directamente por el prestador de servicios de salud o mediante contrato o convenio con un tercero.' WHERE code = 'TSDOT-014';
UPDATE evaluation_criteria SET name = '9. Las instituciones prestadoras de servicios de salud con servicios de hospitalización, hospitalización paciente crónico con y sin ventilador, cuidado intensivo neonatal, pediátrico y adulto, urgencias y del grupo quirúrgico, en la modalidad intramural, cuentan con equipos de telecomunicaciones de doble via y conectividad para notificar a la Red de Donación y Trasplantes sobre la existencia de un posible donante.' WHERE code = 'TSDOT-027';
UPDATE evaluation_criteria SET name = '10. Las instituciones prestadoras de servicios de salud con servicios de cuidado intensivo pediátrico y adulto que adicionalmente  habiliten el servicio quirúrgico de neurocirugía, cuentan con equipo biomédico para  realizar pruebas auxiliares en el diagnóstico de muerte encefálica, según lo documentado en el estándar de procesos prioritarios.' WHERE code = 'TSDOT-028';
UPDATE evaluation_criteria SET name = '13.1. Nevera o depósito fria para el almacenamiento de sangre o de sus componentes con sistema de control de temperatura entre 1ºC y 6ºC y alarma audible o sistema de monitoreo que alerte cambios próximos al límite en que la sangre o sus componentes puedan deteriorarse.' WHERE code = 'TSDOT-032';
UPDATE evaluation_criteria SET name = '13.3 Congelador para la conservación de plasma o crioprecipitados con registro y control de temperatura por debajo de -18ºC y sistema de alarma audible que alerte cambios próximos al límite en que el componente almacenado pueda deteriorarse, cuando se requiera.' WHERE code = 'TSDOT-034';
UPDATE evaluation_criteria SET name = '15. En los servicios de los grupos quirúrgico, internación y el servicio de urgencias, el prestador de servicios de salud cuenta con accesorios para garantizar empaque cerrado y transporte de los elementos sucios y limplos, como compreseros, vehículos para ta recolección interna de residuos, carros de comida, instrumental, entre otros.' WHERE code = 'TSDOT-038';
UPDATE evaluation_criteria SET name = '17.1.1.4. Si el prestador de servicios  de salud realiza consulta dermatológica en la modalidad de telemedicina cuenta con cámara digital de alta resolución que permita un fácil enfoque de las lesiones de piel y revisión de las imágenes capturadas previo a la transmisión al dermatólogo.' WHERE code = 'TSDOT-053';
UPDATE evaluation_criteria SET name = '17.1.2.2. El software utilizado se adapta al cambio en la disponibilidad del ancho de banda sin perder conexión. En el caso que la videoconferencia sea grabada se deberán contemplar todos criterios de seguridad informática, que permita resguardar adecuadamente la confidencialidad y privacidad del paciente.' WHERE code = 'TSDOT-056';
UPDATE evaluation_criteria SET name = '17.2.2. Las pantallas o monitores grado médico utilizados para el despliegue de imágenes cuentan con una distancia máxima de 0.19 milímetros entre pixeles (dot pitch), resolución mínima de 1024 x 768 pixeles, como mínimo un ratio de contraste de 500:1 y mínimo de luminancia (brillo) de 250 cd/m2 que permita garantizar la interpretación adecuada de la información recibida.' WHERE code = 'TSDOT-063';
UPDATE evaluation_criteria SET name = '4.10. Dispensación' WHERE code = 'TSMD-038';
UPDATE evaluation_criteria SET name = '4.11. Devolución' WHERE code = 'TSMD-039';
UPDATE evaluation_criteria SET name = '4.12. Disposición final' WHERE code = 'TSMD-040';
UPDATE evaluation_criteria SET name = '4.13. Seguimiento al uso de medicamentos, homeopáticos, fitoterapéuticos, medicamentos biológicos, componentes anatómicos, dispositivos médicos (incluso los sobre medida, elementos de rayos X y de uso odontológico), reactivos de diagnóstico in vitro; así como de los demás insumos asistenciales que se utilicen incluidos los que se encuentran en los depósitos o almacenes del prestador de servicios de salud y en la modalidad extramural.' WHERE code = 'TSMD-041';
UPDATE evaluation_criteria SET name = '7. El prestador de servicios de salud que cuente con reservas de medicamentos, homeopáticos, fititerapéuticos, medicamentos biológicos, componentes anatómicos, dispositivos médicos (incluidos los sobre medida), reactivos de diagnóstico in vitro, y demás insumos asistenciales, debe garantizar que se almacenen en condiciones apropiadas de temperatura, humedad, ventilación segregación y seguridad de acuerdo con las condiciones definidas por el fabricante o el banco del componente anatómico, según aplique, y contar con instrumento para medir humedad reltiva y temperatura y evidencia su registro, control y gestión.' WHERE code = 'TSMD-044';
UPDATE evaluation_criteria SET name = '8. Para la aplicación del protocolo de lavado de manos o higienización, los servicios de salud cuentan con los insumos de aseo, limpieza y secado que garanticen su cumplimiento.' WHERE code = 'TSMD-045';
UPDATE evaluation_criteria SET name = '10. El prestador de servicios de salud cuenta con paquete para el manejo de derrames y rupturas de medicamentos, ubicado en un lugar de fácil acceso, visible y con adecuada señalización, disponible para su uso en los servicios y ambientes donde se requieran. El prestador de servicios de salud define su contenido de acuerdo con los medicamentos utilizados y lo sugerido por el fabricante en las fichas técnicas.' WHERE code = 'TSMD-047';
UPDATE evaluation_criteria SET name = '3. El prestador de servicios de salud cuenta con un comité o instancia que orienta y promueve la política de seguridad del paciente, el control de infecciones y ta optimización del uso de antibióticos, cuando tos prescriba o administre. En el caso de profesionales independientes de salud podrá ser el mismo prestador.' WHERE code = 'TSPP-003';
UPDATE evaluation_criteria SET name = '6. El prestador de servicios de salud cuenta con información documentada de las actividades y procedimientos que se realizan en el servicio acordes con su objeto, alcance y enfoque diferencial, mediante guías de práctica clínica- GPC, procedimientos de atención, protocolos de atención y otros documentos que el prestador de servicios de salud determine, dicha  información  incluye talento humano, equipos biomédicos, medicamentos y dispositivos médicos e insumos requeridos.' WHERE code = 'TSPP-019';
UPDATE evaluation_criteria SET name = '8. Las guías de práctica clínica y protocolos a adoptar son en primera medida los que disponga el Ministerio de Salud y Protección Social. En caso de no estar disponibles, o si existe nueva evidencia científica que actualice alguna o algunas de las recomendaciones de las guías de práctica clínica o requerimientos de los protocolos, el prestador de servicios de salud adopta, adapta o desarrolla guías de práctica clínica o protocolos basados en evidencia científica, publicados nacional o internacionalmente.' WHERE code = 'TSPP-021';
UPDATE evaluation_criteria SET name = '14. Cuando un prestador de servicios de salud contrate el proceso de esterilización con un tercero, cuenta con un contrato, convenio o acuerdo escrito entre las partes, el cual debe incluir como mínimo las características de calidad de los productos, la supervisión del estado de las instalaciones y la aplicación de los procedimientos del tercero para realizar el proceso. No obstante, el prestador de servicios de salud que requiere el proceso de esterilización es el responsable de garantizar la esterilidad y el desempeño del producto final.' WHERE code = 'TSPP-044';
UPDATE evaluation_criteria SET name = '16. Hasta tanto el Ministerio de Salud y Protección Social regule la materia, el prestador de servicios de salud podrá reusar dispositivos médicos, siempre y cuando el fabricante de dichos dispositivos autorice su reúso. En tal caso, el prestador de servicios de salud cuenta con información documentada que defina:' WHERE code = 'TSPP-046';
UPDATE evaluation_criteria SET name = '16.2. Acciones de seguimiento a través de los comités de infecciones, de seguridad del paciente y del programa de tecnovigilancia, que garanticen que el dispositivo no ha perdido la eficacia y desempeño para el cual fue diseñado, ni exponga al riesgo de infecciones o complicaciones al usuario.' WHERE code = 'TSPP-048';
UPDATE evaluation_criteria SET name = '21. El Profesional Independiente de Salud y las Entidades con Objeto Social Diferente que oferten y presten servicios de salud de los grupos de consulta externa y los prestadores de servicios de salud de Transporte Especial de Pacientes cuentan con documento del proceso que orienta la atención en salud de las víctimas de violencias sexuales.' WHERE code = 'TSPP-080';
UPDATE evaluation_criteria SET name = '23. Los prestadores de servicios de salud cuentan con información documentada de las condiciones de almacenamiento, conservación, control de fechas de vencimiento, uso y custodia de los medicamentos, dispositivos médicos e insumos contenidos en los kits de derrames de medicamentos, ataque con agentes químicos y de violencias sexuales, según su contenido.' WHERE code = 'TSPP-082';
UPDATE evaluation_criteria SET name = '24. Las Instituciones Prestadoras de Servicios de  Salud con servicios de hospitalización, hospitalización de paciente crónico con y sin ventilador, cuidado intensivo neonatal, pediátrico y adulto, urgencias y del grupo quirúrgico, en la modalidad intramural, cuentan con la siguiente Información documentada:' WHERE code = 'TSPP-083';
UPDATE evaluation_criteria SET name = '25. Las Instituciones Prestadoras de Servicios de Salud, con servicios de cuidado intensivo pediátrico y adulto que cuenten con servicios quirúrgicos de neurocirugía de alta complejidad, cuentan con información documentada del procedimiento para el diagnóstico de muerte encefálica y muerte en asistolia.' WHERE code = 'TSPP-088';
UPDATE evaluation_criteria SET name = '31.4. El método de comunicación que se utiliza (sincrónico o asincrónico) para la atención y los criterios para la identificación de los casos en los cuales se debe transferir y recibir la información en tiempo real (sincrónico) o mediante almacenamiento - envio (asincrónico).' WHERE code = 'TSPP-104';
UPDATE evaluation_criteria SET name = '32. Adicional a los criterios solicitados para el prestador remisor, cuenta con información documentada de las actividades y procedimientos de los servicios que oferte, acordes con su objeto, alcance y enfoque diferencial, mediante guías de práctica clínica- GPC, procedimientos de atención, protocolos de atención y otros documentos que el prestador de servicios de salud determine, dicha información incluye talento humano, equipos biomédicos, medicamentos y dispositivos médicos e insumos  requeridos.' WHERE code = 'TSPP-109';
UPDATE evaluation_criteria SET name = '2. El prestador de servicios de salud cuenta con procedimientos para utilizar una historia única y para el registro de entrada y salida de historias del archivo físico. Ello implica que el prestador de servicios de salud cuente con un mecanismo para unificar la información de cada paciente y su disponibilidad para el equipo de salud.' WHERE code = 'TSHCR-002';
UPDATE evaluation_criteria SET name = '3. Los medios electrónicos para la gestión de la historia clínica garantizan la confidencialidad y seguridad, así como el carácter permanente de registrar en ésta y en otros registros asistenciales, sin que se puedan modificar los datos una vez se guarden los registros.' WHERE code = 'TSHCR-003';
UPDATE evaluation_criteria SET name = '9. El prestador de servicios de salud cuenta con un procedimiento de consentimiento informado que incluye mecanismos para verificar su aplicación, para que el paciente o su responsable, aprueben o no documentalmente, el procedimiento e intervención en salud a que va a ser sometido, previa información de los beneficios, riesgos, alternativas e implicaciones del acto asistencial' WHERE code = 'TSHCR-009';
UPDATE evaluation_criteria SET name = '10. Cuando el prestador de servicios de salud utilice mecanismos electrónicos, ópticos o similares para generar, recibir, almacenar, o disponer datos de la historia clínica y para conservarlos, debe avalar que el mecanismo utilizado cumple con características de: autenticidad, fiabilidad, integridad y disponibilidad del documento, de acuerdo con lo establecido en la normatividad vigente expedida por el Archivo General de la Nación, la Superintendencia de Industria y Comercio y el Ministerio de Tecnologías de información y Comunicaciones, para lo cual, el prestador presentará un documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, certificando que el mecanismo usado por el prestador cumple con la normatividad mencionada' WHERE code = 'TSHCR-010';
UPDATE evaluation_criteria SET name = '13. Las instituciones prestadoras de servicios de salud con servicios en la modalidad intramural para hospitalización, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediatricos y adultos, urgencias y servicios del grupo quirurgico, cuentan con:' WHERE code = 'TSHCR-027';
UPDATE evaluation_criteria SET name = '15.1. Los mecanismos que garanticen la custodia, seguridad confidencialidad y conservación integral, durante la transmisión y almacenamiento de la información contenida en la historia clínica y demás registros asistenciales y la reproducibilidad de la información de acuerdo con la legislación vigente' WHERE code = 'TSHCR-049';

-- Total actualizados: 68