-- Migración: 512 criterios oficiales Resolución 3100/2019
BEGIN;
DELETE FROM questionnaire_criteria;
DELETE FROM evaluation_criteria;

-- TSTH: Talento Humano (25 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSTH' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSTH-001', '1', '1. El talento humano en salud y otros profesionales que se relacionan con la atención o resultados en salud de los usuarios, cuentan con los titulos, según aplique, de educación superior o certificados de aptitud ocupacional, expedidos por la entidad educativa competente. En el caso de títulos o certificados obtenidos en el extranjero, copia de la resolución de convalidación expedida por el Ministerio de Educación Nacional', 'medium'),
  ('TSTH-002', '2', '2. El talento humano en salud cuenta con copia de la resolución de autorización del ejercicio expedido por la autoridad competente  o inscripción e en el ReTHUS', 'medium'),
  ('TSTH-003', '3', '3. El prestador de servicios de salud determina la cantidad necesaria de talento humano requerido para cada uno de los servicios ofertados y prestados, de acuerdo con la capacidad instalada, la relación entre la oferta y demanda, la oportunidad en la prestación, tiempo de la atención y el riesgo en la atención. Este criterio no aplica para profesionales independientes de salud', 'medium'),
  ('TSTH-004', '4', '4. El prestador de servicios de salud que actúe como escenario de práctica formativa en el área de la salud, cuenta con:', 'simple'),
  ('TSTH-005', '5', '4.1. Convenio vigente con la institución educativa autorizada por la entidad competente', 'simple'),
  ('TSTH-006', '6', '4.2. Información documentada de los mecanismos de supervisión permanente del personal en entrnamiento', 'simple'),
  ('TSTH-007', '7', '4.3. Estudio de la capacidad instalada en el cual se dtermine el número máximo de estudiantes que simultaneamente puedan acceder por programa de formación y por jornada, para cada uno de los servicios que se utilicen como escenarios de práctica formativa en el área de la salud, estudio que debe ser elaborado teniendo en cuenta los "lineamientos de referencia para la asignación de cupos de estudiantes en escenarios clinicos" publicados por el Ministerio de Salud y Protección Social', 'complex'),
  ('TSTH-008', '8', '5. En los servicios de salud diferentes a los servicios de consulta externa especializada de dolor y cuidado paliativo, donde se atienden pacientes con enfermedades terminales, crónicas, degenerativas e irreversibles, a los cuales se les decida como conducta médica: como parte del plan integral de cuidado que gestiona el equipo de salud, o por solicitud del paciente; el manejo de dolor y cuidado paliativo, el profesional en medicina tratante cuenta con constancia de asistencia en las acciones de formación continua en el manejo de dolor y cuidado paliativo, cuando no sea especialista en dolor y cuidado paliativo', 'complex'),
  ('TSTH-009', '9', '6. El talento humano en salud de los servicios de atención del parto, cuidado intensivo y cuidado intermedio neonatal, pediátrico y adultos, cuentan con constancia de asistencia en las acciones de formación continua para la gestión del duelo', 'complex'),
  ('TSTH-010', '10', '7. En los servicios de salud donde se realicen imagenes diagnósticas por ultrasonido, cuenta con médico especialista en radiologia e imagenes diagnósticas también podrán realizar imagenes diagnósticas aquellos médicos especialistas, quienes en su pensum o formación académica hayan adquirido los conocimientos del manejo e interpretación del espectro electromagnetico, del ultrasonido especialmente, así como de la radiaciones ionizantes para establecer el diagnóstico o el tratamiento de las enfermedades inherentes a su especialidad, para lo cual deberá acreditar el respectivo certificado.', 'medium'),
  ('TSTH-011', '11', '8. Los profesionales de la medicina de los servicios de hospitalización de baja, mediana y alta complejidad, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediátricos y adultos; urgencias, y servicios del grupo quirurgico en modalidad intramural,cuentan con certificación vigente de aprobación de la evaluación de competencias esenciales para el cuidado de la donante expedida por el Instituto Nacional de Salud.', 'medium'),
  ('TSTH-012', '12', '9. Las instituciones prestadoras de servicios de salud con servicios de cuidado intensivo pediatrico y adulto que adicionalmente habiliten servicio quirurgico de neurocirugía, tienen disponibilidad de coordinador operativo de trasplantes.', 'medium'),
  ('TSTH-013', '13', '10. El talento humano en salud de los servicios de salud de los grupos de consulta externa, internación y el servicio de urgencias, cuentan con constancia de asistencia en las acciones de formación continua en la atención integral en salud de las personas victimas de violencia sexual.', 'medium'),
  ('TSTH-014', '14', '11. El talento humano en salud de los servicios de transporte asistencial, atención prehospitalaria y urgencias, cuentasn con constancia de asistencia en las acciones de formación continua en la atención a personas víctimas de ataques con agentes químicos.', 'medium'),
  ('TSTH-015', '15', '12. Cuando en un servicio de salud se realicen "pruebas en punto de atención del paciente - (point of care testing - POCT)", el talento humano en salud qeu las realice, a excepción del profesional en bacteriologia cuenta con constancia de asistencia en las acciones de formación continua en la atención a personas víctimas de ataques con agentes químicos.', 'medium'),
  ('TSTH-016', '16', '13. Procedimientos bajo sedación:', 'simple'),
  ('TSTH-017', '17', '13.1 Cuando fuera de salas de cirugía, se realicen procedimientos bajo sedación Grado I y II, adicional al profesional de salud que realiza el procedimiento, cuenta con:', 'medium'),
  ('TSTH-018', '18', '13.1.1. Profesional en la medicina especialista en anestesiologia, o profesional de la medicina o profesional en odontologia, según aplique, el cual será el encargado de administrar el medicamento y realizar el monitoreo continuo del paciente (registro de signos vitales y la respuesta a la sedación)', 'medium'),
  ('TSTH-019', '19', '13.1.2. Todos los profesionales, a excepción del profesional de la medicina especialista en anestesiologia, deben demostrar constancia de asistencia a curso de formación continua en soporte vital básico y sedación', 'medium'),
  ('TSTH-020', '20', '13.1.3 Para sedacción con óxido nitroso en odontologia, el profesional de la odontología cuenta con constancia de asistencia en las acciones de formación continua para uso clínico y práctico de este gas.', 'medium'),
  ('TSTH-021', '21', '13.2. Cuando fuera de las salas de cirugia, se realicen procedimientos bajo sedación grado III, adicional al profesional de salud que realiza el procedimiento, cuenta con profesional de la medicina con especialidad médico - quirúrgica, quién será el responsable de administrar la sedación', 'medium'),
  ('TSTH-022', '22', '13.3. Cuando fuera de las salas de cirugía, se realicen procedimientos bajo sedación grado IV, adicional al profesional de  salud que realiza el procedimiento, cuenta con profesional de la medicina especialisa en anestesiologia, quién será el responsable de administrar la sedación', 'medium'),
  ('TSTH-023', '23', '13.4 Cuenta con profesional de la medicina especialista en anestesiologia cuando la atención de trate de pacientes con caracteristicas particulares: poco colaboradores; edades extremas; con enfermedades severas:cardíacas, pulmonares, hepáticas, renales o del sistema nervioso central;cualquier alteración del grado de consciencia, con obesidad mórbida, con apnea del sueño, embarazadas, o quienes abusan del alcohol o de las drogas; antecedentes de sedación fallida o que presentaron efectos adversos a algún medicamento utilizado en la sedación, por tener un elevado riesgo de desarrollar complicaciones relacionadas con la sedación analgesia', 'medium'),
  ('TSTH-024', '24', 'Modalidad de telemedicina prestador remisor - prestador de referencia', 'simple'),
  ('TSTH-025', '25', '14. Adicional a los criterios del estándar de talento humano enunciados que le aplique, el talento humano en salud que preste directamente un servicio de salud bajo la modalidad telemedicina cuentan con constancia de asistencia en las acciones de formación continua en el manejo de tecnología utilizada por el prestador, los procesos y herramientas inherentes a la prestación de servicios bajo esta modalidad', 'complex')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSINF: Infraestructura (197 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSINF' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSINF-001', '1', 'Edificaciones de uso exclusivo en salud', 'simple'),
  ('TSINF-002', '2', '1. Los servicios de salud de urgencias, de atención del parto, hospitalarios y de cirugía que realicen procedimientos quirúrgicos no ambulatorios, solo se pueden prestar en edificaciones de uso exclusivo de salud.', 'medium'),
  ('TSINF-003', '3', '2. Los servicios de salud de: urgencias, cirugía y del grupo de internación, así como en los servicios de salud donde se realice el proceso de esterilización, deben contar con ambiente de aseo de uso exclusivo', 'complex'),
  ('TSINF-004', '4', '3. Cuando en una edificación de uso exclusivo de salud funcione más de un prestador de servicios de salud con servicios de los grupos de consulta externa y apoyo diagnóstico y complementación terapeutica, cada prestador cuenta con infraestructura separada delimitada fisicamente. Se pueden compartir los siguientes ambientes y áreas: aseo, salas de espera y unidades sanitarias.', 'medium'),
  ('TSINF-005', '5', '4. Las edificaciones donde se presten servicios de salud de urgencias y del grupo de internación, cuentan con tanque de almacenamientode agua para el consumo humano que garantice como mínimo una reserva de 24 horas de servicio continuo, calculando con base en el consumo de 600 lt por cama/camilla al día.', 'medium'),
  ('TSINF-006', '6', '5. Cuando el prestador de servicios de salud cuente con mas de una infraestructura y estas se puedan vincular funcionalmente entre si, lo harán mediante tunel o puente cubierto, o muro(s) colindante(s) que cuenten con acceso (s) que intercomuniquen las infraestructuras, de uso exclusivo del prestador y adicionalmente cumplen con las siguientes caracteristicas:', 'medium'),
  ('TSINF-007', '7', '5.1. Ancho que permita la movilización de camas, camillas, sillas de ruedas, equipos biomédicos  y personal para el traslado de los pacientes  en condiciones seguras.', 'medium'),
  ('TSINF-008', '8', '5.2. El piso del túnel o puente debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos d a ambos lados y con protecciones laterales hacia espacios libres.', 'medium'),
  ('TSINF-009', '9', '5.3. Lo anterior siempre y cuando la norma urbanística de la jurisdicción donde se localizan las sedes hayan aprobado esta forma de vinculación funcional entre las mismas.', 'medium'),
  ('TSINF-010', '10', '5.4. Esta edificación se podrá habilitar como una o varias sedes, de acuerdo con lo que determine el prestador de servicios de salud', 'medium'),
  ('TSINF-011', '11', 'Edificaciones de uso mixto', 'simple'),
  ('TSINF-012', '12', '6. Cuando en una edificación de uso mixto funcione más de un prestador de servicios de salud, cada uno cuenta con infraestructura separada y delimitada físicamente. Se pueden compartir las salas de espera y las unidades sanitarias.', 'medium'),
  ('TSINF-013', '13', '7. En edificaciones de uso mixto pueden funsionar los prestadores de servicios de salud que oferten y presten servicios de los grupos de consulta externa. de apoyo diagnóstico y complementación terapeutica y los servicios del grupo quirurgico que realicen exclusivamente procedimientos de cirugia ambulatoria.', 'medium'),
  ('TSINF-014', '14', 'Edificaciones de uso exclusivo en salud y edificaciones de uso mixto', 'simple'),
  ('TSINF-015', '15', '8. Los prestadores de servicios de salud ubicados en edificaciones de hasta tres (3) pisos o niveles contados a partir del nivel más bajo construido, y que funcione en segundo o tercer nivel o piso, cuentan con ascensor o rampa o sistema alternativo de elevación. El sistema alternativo de elevación no puede ser utilizado cuando se presten servicios hospitalarios, cirugía, urgencias o de atención del parto.', 'medium'),
  ('TSINF-016', '16', '9. Los sistemas alternativos de elevación deben cumplir con las siguientes condiciones:', 'simple'),
  ('TSINF-017', '17', '9.1. Su ubicación no interfiera con el acceso y evacuación de los usuarios por las escaleras', 'simple'),
  ('TSINF-018', '18', '9.2. Estén disponibles tanto para el acceso como para la evacuación de los usuarios', 'simple'),
  ('TSINF-019', '19', '9.3. Su manejo sea autonomo', 'simple'),
  ('TSINF-020', '20', '9.4. Garanticen seguridad durante su uso', 'simple'),
  ('TSINF-021', '21', '10. Las edificaciones con más de tres (3) pisos o niveles, contados a partir del nivel más bajo construido, cuentan con ascensor.', 'medium'),
  ('TSINF-022', '22', '11. En edificaciones donde se presten servicios de los grupos de internación, atención del parto, quirurgicos o urgencias para la movilización de pacientes en camilla, la cabina de los ascensores debe tener las dimensiones interiores mínimas de 2.20 de profundidad y de 1.20 ancho, que garanticen el traslado seguro de los pacientes. Las dimensiones de la cabina podrán ser variables en el o los ascensores que el prestador determine para la movilización de usuarios a pie o en silla de ruedas.', 'medium'),
  ('TSINF-023', '23', '12. Si se tienen escaleras o rampas, el piso debe ser uniforme y de material antideslizante o con elementos que garanticen esta propiedad en todo su recorrido, con pasamanos de preferencia a ambos lados y con protecciones laterales hacia espacios libres.', 'medium'),
  ('TSINF-024', '24', '13. Las edificaciones donde se presten servicios de salud cuentan con suministro de agua, energia eléctrica, conexión a la red de alcantarillado y sistemas de comunicaciones.', 'medium'),
  ('TSINF-025', '25', '14. En edificaciones donde se presten servicios de cirugía, atención del parto, laboratorio clínico, urgencias, gestión pre transfusional, dialisis, hospitalarios, imagénes diagnósticas, vacunación, servicio farmaceutico y los que requieran cadena de frio, cuentan con planta electrica.', 'complex'),
  ('TSINF-026', '26', '15. El prestador de servicios de salud que utilice equipos generadores de radiaciones ionizantes cuenta con licencia de práctica médica vigente expedida por la entidad competente.', 'medium'),
  ('TSINF-027', '27', '16. El prestador de servicios de salud que utilice fuentes radiactivas cuenta con autorización vigente de empleo de material radiactivo, expedida por la entidad reguladora competente', 'medium'),
  ('TSINF-028', '28', '17. Cada prestador de servicios de salud debe contar con el respectivo concepto sanitario que dé cumplimiento a lo establecido en la normatividad sanitaria vigente en aspectos tales como agua para consumo humano, gestión de residuos, control de vectores, orden y aseo, condiciones locativas, entre otros. Este concepto será emitido por las autoridades sanitarias correspondientes, en el marco de sus competencias, y debe considerar los servicios de apoyo como lavanderia y servicio de alimentación.

Cuando estos servicios de apoyo son contratados con terceros dichos proveedores deben contar con el concepto sanitario correspondiente a la actividad de bienes y servicios que presta.', 'complex'),
  ('TSINF-029', '29', 'Generalidades de los ambientes y las áreas de los servicios y sus características', 'simple'),
  ('TSINF-030', '30', '18. Las áreas y ambientes de todos los servicios de salud cuentan con ventilación natural o artificial.', 'simple'),
  ('TSINF-031', '31', '19. Las áreas de circulación están libres de obstáculos de manera que permitan la movilización de pacientes, talento humano, usuarios y equipos biomédicos', 'medium'),
  ('TSINF-032', '32', '20. Los ambientes y áreas que hagan parte de cualquier servicio de salud, deben permitir la instalación y movilización de equipos biomedicos y personal necesarios para la atención del paciente en condiciones de rutina o de emergencia.', 'medium'),
  ('TSINF-033', '33', '21.En los servicios del grupo quirurgico, los ambientes y áreas clasificados como no restringidos, semirestringidos, deben señalizarse mediante la demarcación permanente en piso con material lavable y resistente al tráfico pesado, utilizando los siguientes colores', 'medium'),
  ('TSINF-034', '34', '21.1. Verde: Ambientes o áreas no restringidas', 'simple'),
  ('TSINF-035', '35', '21.2. Amarillo: Ambientes o áreas semi-restringidas', 'simple'),
  ('TSINF-036', '36', '21.3. Roja: Ambientes o áreas restringidas', 'simple'),
  ('TSINF-037', '37', '22. Cada uno de los pisos o niveles de la edificación cuenta con señalización y planos indicativos de las rutas de evacuación, salidas de emergencia y puntos de encuentro, visible al público en general.', 'medium'),
  ('TSINF-038', '38', '23. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre-transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios habilitados, tiene disponibilidad de un área con iluminación y ventilación natural o artificial, para la ubicación de la dotación requerida de acuerdo con los componentes sanguíneos a transfundir.', 'complex'),
  ('TSINF-039', '39', '24. Cuando un prestador de servicios de salud realice procedimientos bajo sedación fuera de salas de cirugía, tiene disponibilidad de área o ambiente para la recuperación de pacientes que puede ser la misma área o ambiente donde se realiza el procedimiento, garantizando la privacidad del usuario.', 'medium'),
  ('TSINF-040', '40', '25. El prestador de servicios de salud que realice el proceso de esterilización, cuenta con:', 'complex'),
  ('TSINF-041', '41', '25.1. Ambiente o área de recibo de material contaminado.', 'simple'),
  ('TSINF-042', '42', '25.2. Ambiente o área de lavado', 'simple'),
  ('TSINF-043', '43', '25.3. Ambiente o área de secado', 'simple'),
  ('TSINF-044', '44', '25.4. Ambiente o área de empaque.', 'simple'),
  ('TSINF-045', '45', '25.5. Ambiente o área de esterilización', 'simple'),
  ('TSINF-046', '46', '25.6. Ambiente o área para almacenamiento de material esteril', 'simple'),
  ('TSINF-047', '47', '25.7. Mesón de trabajo con poceta', 'simple'),
  ('TSINF-048', '48', '25.8. Lavamanos, cuando el proceso se realice fuera del servicio de salud', 'complex'),
  ('TSINF-049', '49', '26. El prestador de servicios de salud que contrate el proceso de esterilización, dentro de su infraestructura cuenta con:', 'complex'),
  ('TSINF-050', '50', '26.1. Ambiente o área para lavado, limpieza y desinfección y entrega de material limpio al proveedor', 'simple'),
  ('TSINF-051', '51', '26.2.  Ambiente o área para la recepción y almacenamiento del material esteril', 'simple'),
  ('TSINF-052', '52', '27. El prestador de servicios de salud que realice el proceso de esterilización en una cetral de esterilización cuenta con los siguientes ambientes y áreas señalizadas unidireccionales y de circulación restringida.', 'complex'),
  ('TSINF-053', '53', '27.1. Ambiente de recibo y lavado de material contaminado', 'simple'),
  ('TSINF-054', '54', '27.2. Ambiente limpio con las siguientes áreas:', 'simple'),
  ('TSINF-055', '55', '27.2.1. Área de secado', 'simple'),
  ('TSINF-056', '56', '27.2.2. Área de empaque', 'simple'),
  ('TSINF-057', '57', '27.2.3. Área de esterilización', 'simple'),
  ('TSINF-058', '58', '27.3. Ambiente para almacenamiento de material esteril', 'simple'),
  ('TSINF-059', '59', 'Caracteristicas de los ambientes y áreas que pueden ser requeridos en varios servicios de salud', 'simple'),
  ('TSINF-060', '60', '28. Consultorio: para efectos del presente manual se definen los siguientes tipos de consultorios de acuerdo con la oferta de servicios:', 'medium'),
  ('TSINF-061', '61', '28.1. Consultorio donde se realiza examen fisico: ambiente con mínimo 10 mt2 (sin incluir la unidad sanitaria) que cuenta con_', 'medium'),
  ('TSINF-062', '62', '28.1.1. área para entrevista', 'simple'),
  ('TSINF-063', '63', '28.1.2. área de examen', 'simple'),
  ('TSINF-064', '64', '28.1.3. Lavamanos. No se exige adicional si el consultorio cuenta con unidad sanitaria', 'simple'),
  ('TSINF-065', '65', '28.1.4. Las áreas están separadas entre si por barrera física fija o móvil, con excepción de los consultorios del servicio de urgencias, optometría y oftalmologia, donde no se requiere.', 'medium'),
  ('TSINF-066', '66', '28.2. Consultorio donde se realizan procedimientos: ambiente mínimo de 10 m2 (sin incluir la unidad sanitaria) que cuenta con:', 'medium'),
  ('TSINF-067', '67', '28.2.1. Área para entrevista.', 'simple'),
  ('TSINF-068', '68', '28.2.2. Área de procedimientos.', 'simple'),
  ('TSINF-069', '69', '28.2.3. Las áreas están separadas entre sí por barrera física fija.', 'simple'),
  ('TSINF-070', '70', '28.2.4. Mesón de trabajo.', 'simple'),
  ('TSINF-071', '71', '28.2.5. Poceta, cuando la requiera, según los procedimientos que el prestrador documente en el estándar de procesos prioritarios.', 'complex'),
  ('TSINF-072', '72', '28.2.6. Lavamanos. No se exige adiocnal si el consultorio cuenta con una unidad sanitaria.', 'simple'),
  ('TSINF-073', '73', '28.3 Consultorio odontológico con una unidad odontológica: Ambiente con mínimo 10 m2 (sin incluir la unidad sanitaria) cuenta con:', 'medium'),
  ('TSINF-074', '74', '28.3.1. Área para entrevista, si la requiere', 'simple'),
  ('TSINF-075', '75', '28.3.2. Área para unidad odontológica.', 'simple'),
  ('TSINF-076', '76', '28.3.3. Lavamanos. No se exige adicional si el consultorio cuenta con unidad sanitaria.', 'simple'),
  ('TSINF-077', '77', '28.3.4. Área con mesón de trabajo con poceta.', 'simple'),
  ('TSINF-078', '78', '28.4. Consultorio odontológico con más de una unidad odontológica: Ambiente con mínimo 10 m2 (sin incluir la unidad sanitaria) que cuenta con:', 'medium'),
  ('TSINF-079', '79', '28.4.1. Área adicional por cada unidad odontológica que permita la instalación y movilización de talento humano, pacientes, usuarios y equipos biomédicos.', 'medium'),
  ('TSINF-080', '80', '28.4.2. Barrera física fija o móvil entre las unidades odontológicas.', 'simple'),
  ('TSINF-081', '81', '28.4.3. Mínimo un lavamanos por cada tres unidades odontológicas o fracción.', 'simple'),
  ('TSINF-082', '82', '28.4.5. A partir de tres unidades odontológicas, adicional a lo mencionado en los numerales 28.4.1, 28.4.2 y 28.4.3, tiene disponibilidad de un ambiente con mesón de trabajo y poceta.', 'medium'),
  ('TSINF-083', '83', '29. Consultorio donde se realiza únicamente entrevista, no se realiza examen físico ni procedimientos: Ambiente con mínimo 4 m2 (sin incluir la unidad sanitaria), cuenta con:', 'medium'),
  ('TSINF-084', '84', '29.1. Área para entrevista, según el tipo de consulta.', 'simple'),
  ('TSINF-085', '85', '29.2. Lavamanos. No se exige adicional si el consultorio cuenta con unidad sanitaria.', 'simple'),
  ('TSINF-086', '86', '30. Sala de procedimientos: Es el ambiente donde se realizan procedimientos derivados de los servicios de salud. Para efectos del presente manual, se definen los siguientes tipos de sala:', 'medium'),
  ('TSINF-087', '87', '30.1. Sala de procedimientos o curaciones. 
Ambiente con mínimo 8 m2, que cuenta con:', 'simple'),
  ('TSINF-088', '88', '30.1.1. Mesón de trabajo', 'simple'),
  ('TSINF-089', '89', '30.1.2. Poceta, cuando la requiera, según los procedimientos que el prestador documente en el estándar de procedimientos prioritarios.', 'medium'),
  ('TSINF-090', '90', '30.1.3. Lavamanos', 'simple'),
  ('TSINF-091', '91', '30.2. Sala de procedimientos de Litotricia: 
Ambiente con dimensión variable acirde con la tecnólogía utilizada, que cuenta con mesón de trabajo con poceta y disponibilidad de:', 'medium'),
  ('TSINF-092', '92', '30.2.1. Vestidor para pacientes con área para casilleros.', 'simple'),
  ('TSINF-093', '93', '30.2.2. Área de recuperación.', 'simple'),
  ('TSINF-094', '94', '30.2.3. Unidad sanitaria.', 'simple'),
  ('TSINF-095', '95', '30.3. Sala de procedimientos endoscópicos:
Ambiente con dimensión variable acorde con el tipo de tecnología utilizada y los procedimientos que se realicen, cuenta con:', 'medium'),
  ('TSINF-096', '96', '30.3.1. Área de procedimientos endoscópicos.', 'simple'),
  ('TSINF-097', '97', '30.3.2. Área de recuperación, que puede ser la misma área donde se realice el procedimiento endoscópico.', 'simple'),
  ('TSINF-098', '98', '30.3.3 Lavamanos.
Disponibilidad de:', 'simple'),
  ('TSINF-099', '99', '30.3.4. Unidad sanitaria', 'simple'),
  ('TSINF-100', '100', '30.3.5. Vestidr para pacientes con área para casilleros que puede ser la misma unidad sanitaria con casilleros.', 'simple'),
  ('TSINF-101', '101', '30.3.6. Ambiente o área para almacenar materiales e insumos.', 'simple'),
  ('TSINF-102', '102', '30.3.7. Área de limpieza y desinfección de endoscopis con mesón de trabajo con poceta.', 'simple'),
  ('TSINF-103', '103', '30.3.8. Ambiente o área para almacenamiento de equipos biomédicos.', 'simple'),
  ('TSINF-104', '104', '30.4. Si se realiza procedimiento de monitorización electroencefalográfica con vídeo y radio, cuenta con:', 'simple'),
  ('TSINF-105', '105', '30.4.1. Ambiente con dimensión variable acorde con el tipo de tecnología utilizada.
Disponibilidad de:', 'simple'),
  ('TSINF-106', '106', '30.4.2. Unidad sanitaria', 'simple'),
  ('TSINF-107', '107', '30.5. Si se realiza procedimientos terapéuticos con láser de argón o yag láser, cuenta con ambiente con dimensión variable acorde con el tipo de tecnología utilizada:', 'medium'),
  ('TSINF-108', '108', '31. Sistema de alarma cuando se cuente con red de distribución de gases medicinales.', 'complex'),
  ('TSINF-109', '109', '32. Puesto de enfermería
Área con dimensión variable que, de acuerdo con las necesidades de cada servicio, cumplen con las siguientes características:', 'medium'),
  ('TSINF-110', '110', '32.1. Superficie de trabajo', 'simple'),
  ('TSINF-111', '111', '32.2. Permitela monitprización permanente de los pacientes o sistemas alternativos para su visualización.', 'simple'),
  ('TSINF-112', '112', '32.3. Cuenta con alarma o sistema de llamado de enfermería, donde se requiera.', 'complex'),
  ('TSINF-113', '113', '33. Ambiente o área de trabajo limpio, que cuenta con:', 'simple'),
  ('TSINF-114', '114', '33.1. Mesón de trabajo.', 'simple'),
  ('TSINF-115', '115', '33.2. Área para el almacenamiento y aislamiento de medicamentos.', 'simple'),
  ('TSINF-116', '116', '33.3. Lavamanos.', 'simple'),
  ('TSINF-117', '117', '34. Ambuiente de trabajo sucio, que cuenta con:', 'simple'),
  ('TSINF-118', '118', '34.1. Mesón de trabajo con poceta.', 'simple'),
  ('TSINF-119', '119', '34.2. Lavamanos.', 'simple'),
  ('TSINF-120', '120', '35. Estación de enfermería, que cuenta con:', 'simple'),
  ('TSINF-121', '121', '35.1. Puesto de enfermería.', 'simple'),
  ('TSINF-122', '122', '35.2. Ambiente o área de trabajo limpio.', 'simple'),
  ('TSINF-123', '123', '35.3. Ambiente de trabajo socio.
Disponibilidad de los siguientes ambientes o áreas:', 'simple'),
  ('TSINF-124', '124', '35.4. Área o ambiente para el depósito de equipos biomédicos con dimensión variable de acuerdo con las necesidades del servicio.', 'medium'),
  ('TSINF-125', '125', '35.5. Área o ambiente para depósito de ropa limpia de dimensión variable de acuerdo con las necesidades del servicio.', 'simple'),
  ('TSINF-126', '126', '35.6. Ambiente para depósito de ropa sucia, con dimensión variable de acuerdo con las necesidades del servicio.', 'simple'),
  ('TSINF-127', '127', '35.7. Lavapatos cuando el servicio de salud lo requiera.', 'simple'),
  ('TSINF-128', '128', '35.8. Unidad sanitaria.', 'simple'),
  ('TSINF-129', '129', '36. Baño, ambiente que cuenta con:', 'simple'),
  ('TSINF-130', '130', '36.1. Sanitario.', 'simple'),
  ('TSINF-131', '131', '36.2. Lavamanos.', 'simple'),
  ('TSINF-132', '132', '36.3. Ducha.', 'simple'),
  ('TSINF-133', '133', '36.4. Alarma o sistema de llamado, donde se requiera.', 'complex'),
  ('TSINF-134', '134', '36.5. Puertas corredizas o con apertura hacia el exterior.', 'simple'),
  ('TSINF-135', '135', '37. Unidad sanitaria, ambiente que cuenta con:', 'simple'),
  ('TSINF-136', '136', '37.1. Sanitario.', 'simple'),
  ('TSINF-137', '137', '37.2. Lavamanos.', 'simple'),
  ('TSINF-138', '138', '38. La unidad sanitara adaptada para personas con movilidad reducida cuenta con:', 'simple'),
  ('TSINF-139', '139', '38.1. Sanitario', 'simple'),
  ('TSINF-140', '140', '38.2 Lavamanos.', 'simple'),
  ('TSINF-141', '141', '38.3. Dimensiones que permita el desplazamiento del paciente y maniobra en su interior, las puertas tienen un ancho que permite el fácil acceso de pacientes en sillas de ruedas.', 'medium'),
  ('TSINF-142', '142', '38.4. Puertas corredizas o con apertura hacia el exterior.', 'simple'),
  ('TSINF-143', '143', '38.5. Accesorios que facilite la accesibilidad, movilidad y seguridad del usuario.', 'simple'),
  ('TSINF-144', '144', '38.6. Alarma o sistema de llamado.', 'complex'),
  ('TSINF-145', '145', '39. Bateria sanitaria, ambiente que cuenta con sanitarios en serie y lavamanos, discriminadas por sexo, serán separadas con barreras físicas fijas o divisiones en materiales resistentes, inoxidables e impermeables, con espacios libres que faciliten la ventilación y las labores de aseo. Se instalará adicionalmente un orinal para sexomasculino. Como mínimo uno de los sanitarios de la bateria debe ser apto para personas com movilidad reducida discriminado por sexo.', 'medium'),
  ('TSINF-146', '146', '40. Sala de espera:', 'simple'),
  ('TSINF-147', '147', '40.1. Ambiente o área con dimensión variable de acuerdo al servicio o servicios, independiente de las áreas de circulación, que cuenta con ventilación e iluminación natural y/o artificial.', 'medium'),
  ('TSINF-148', '148', '40.2. Disponibilidad de unidades sanitarias discriminadas por sexo o baterias sanitarias.', 'simple'),
  ('TSINF-149', '149', 'Generalidades de las condiciones de orden, aseo, limpieza y desinfecciones', 'simple'),
  ('TSINF-150', '150', '41. Las condiciones de orde, aseo, limpieza y desinfección son evidentes y responde a un proceso dinámico de acuerdo con los servicios prestados.', 'complex'),
  ('TSINF-151', '151', '42. En las edificaciones destinadas a la prestación de servicios de salud, los pisos deben ser resistentes a factores ambientales, deben ser continuos, antideslizantes, impermeables, lavables, sólidos, resistentes a procesos de lavado y desinfección. Cuando se tengan dilataciones y juntas, estas deben ser selladas de manera que ofrezcan continuidad de la superficie.', 'complex'),
  ('TSINF-152', '152', '43. Los cielo rasos o techos y paredes o muros deben ser impoermeables, lavables, sólidos, resistentes a fctores ambientales e incombustibles y de superficie lisa y continua.', 'medium'),
  ('TSINF-153', '153', '44. En los servicios de cirugía, atención del parto, ambiente TPR, salas de procedimientos, consultorios donde se realicen procedimientos, servicios de internación en cuidado básico, intermedio e intensivo, urgencias, diálisis, hemodinámia e intervencionismo, laboratorios, gestión pre transfunsional, quimioterapia, consulta odontológica y los ambientes o áreas donde se requieran procesos de limpieza y asepsia más profundos, adicional al criterio anterior, la unión entre paredes o muros y el piso debe ser en media caña evitando la formación de aristas o de esquinas.', 'complex'),
  ('TSINF-154', '154', '45. En los servicios de cirugía, atención del parto, ambiente TPR y el ambiente de esterilización, la unión entre cielo raso o techo y la pared o muro y la unión entre paredes o muros, debe contar con media caña, evitando la formación de aristas o de esquinas.', 'medium'),
  ('TSINF-155', '155', 'Criterios de la infraestructura para las modalidades extramural y telemedicina', 'simple'),
  ('TSINF-156', '156', 'Modalidad extramural unidad móvil, jornada de salud y domiciliaria', 'simple'),
  ('TSINF-157', '157', '46. Cuando un prestador de servicios de salud preste sus servicios exclusivamente en la modalidad extramural, la sede cuenta con:', 'medium'),
  ('TSINF-158', '158', '46.1. Ambiente o área para el almacenamiento de medicamentos o dispositivos médicos e isumos, cuando se requiera.', 'simple'),
  ('TSINF-159', '159', '46.2. Ambiente o área para el almacenamiento de equipos biomédicos.', 'simple'),
  ('TSINF-160', '160', '46.3. Ambiente o área para el archivo de las historias clínicas y registros.', 'simple'),
  ('TSINF-161', '161', '47. Disponibilidad de ambiente o área para las labores de aseo, limpieza y desinfección para las unidades móviles.', 'simple'),
  ('TSINF-162', '162', 'Movilidad extramural domiciliaria.', 'simple'),
  ('TSINF-163', '163', '48. El domicilio del paciente cumple con las siguientes condiciones:', 'simple'),
  ('TSINF-164', '164', '48.1. Servicios públicos domiciliarios: Acueducto, alcantarillado, energía eléctrica y sistema de comunicación.', 'complex'),
  ('TSINF-165', '165', '48.2. Unidad sanitaria o baño.', 'simple'),
  ('TSINF-166', '166', 'Modalidad extramural Unidad móvil, terrestre y acuática.', 'simple'),
  ('TSINF-167', '167', '49. Las condiciones de orden, aseo, limpieza y desinfección son evidentes y responden a un proceso dinámico de acuerdo con los servicios prestados.', 'complex'),
  ('TSINF-168', '168', '50. La unidad móvil cuenta con:', 'simple'),
  ('TSINF-169', '169', '50.1. De acuerdo con los servicios a prestar, los ambientes y áreas cumplen', 'simple'),
  ('TSINF-170', '170', '50.2. Suministro de agua potable de manera permanente.', 'simple'),
  ('TSINF-171', '171', '50.3. Tanque para el almacenamiento de aguas residuales. Las aguas residuales no se vierten en la vía pública o en el cauce fluvial.', 'medium'),
  ('TSINF-172', '172', '50.4. Identificación visual como unidad móvil terrestre o acuática según aplique.', 'simple'),
  ('TSINF-173', '173', '50.5. Acceso al servicio de energía eléctrica o fuente de energía alternativa.', 'simple'),
  ('TSINF-174', '174', '50.6. Señalización y condiciones que garanticen la seguridad durante el abordaje, incluyendo el ingreso de personas con discapacidad.', 'medium'),
  ('TSINF-175', '175', '50.7. Estructuras firmes para el ingreso y salida de pacientes y usuarios, con protecciones laterales a espacios libres.', 'simple'),
  ('TSINF-176', '176', '50.8. Señalización de áreas restringidas al interior de la unidad móvil.', 'simple'),
  ('TSINF-177', '177', '50.9. Barreras o mecanismos que impidan el ingres de usuarios a las áreas restringidas.', 'simple'),
  ('TSINF-178', '178', '50.10. Para unidades móviles marítimas o fluviales, las uniones con tierra firme son continuas, sin desniveles y permiten el flujo de camillas y sillas de ruedas.', 'medium'),
  ('TSINF-179', '179', 'Modalidad telemedicina - Prestador remisor', 'simple'),
  ('TSINF-180', '180', '51. Adicional a los criterios del estándar de infraestructura enunciados que le aplique, el prestador de servicios de salud cuenta con:', 'medium'),
  ('TSINF-181', '181', '51.1. Conectividad que garantice la prestación de servicios de salud con integridad y continuidad de acuerdo con el método de transferencia de información que utilice (sincrónico o asincrónico).', 'medium'),
  ('TSINF-182', '182', '51.2. Plataformas tecnológicas que garanticen la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicios de salud, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividad o lineamientos que regulen la materia.', 'medium'),
  ('TSINF-183', '183', '51.3. Suministro de energía eléctrica o baterias que permitan el uso de los instrumentos de comunicación y de los equipos biomédicos necesarios.', 'medium'),
  ('TSINF-184', '184', '51.4. Nivel de iluminación homogénea con luz fluorescente blanca fría y no mezclar tipos de iluminación cálida con fría.', 'simple'),
  ('TSINF-185', '185', 'Modalidad telemedicina - Prestador referencia.', 'simple'),
  ('TSINF-186', '186', '52. Adicional a los criterios del estándar de infraestructura enunciados que le aplique, el prestador de servicios de salud cuenta con:', 'medium'),
  ('TSINF-187', '187', '52.1. Conectividad que garactice la pestación de servicios de salud con integridad y continuidad de acuerdo con el método de transferencia de información que utilice (sincrónico o asincrónico).', 'medium'),
  ('TSINF-188', '188', '52.2. Plataformas tecnológicas que garanticen la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicio de salud, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividado lineamientos que regulen la materia.', 'medium'),
  ('TSINF-189', '189', '52.3. Suministro de energía eléctrica o baterias que permitan el uso de los instrumentos de comunicación y de los equipos biompedicos necesarios.', 'medium'),
  ('TSINF-190', '190', '52.4. Nivel de iluminación homogénea.', 'simple'),
  ('TSINF-191', '191', 'Modalidad telemedicina - Prestador de referencia exclusivo.', 'simple'),
  ('TSINF-192', '192', '53. Cuando el prestador de servicios de salud preste sus servicios exclusivamente en la modalidad de telemedicina como prestador de referencia, cuenta con:', 'medium'),
  ('TSINF-193', '193', '53.1. Ambiente exclusivo para la realización de la atención a distancia que garantiza la privacidad y la confidencialidad durante la atención, la seguridad de los equipos frente a la extracciónno autorizada y condiciones ambientales para su correcto funcionamiento,libre de interferencias visuales y sonoras.', 'medium'),
  ('TSINF-194', '194', '53.2. Conectividad que garantice la prestación de servicios de salud con integridad y continuidad de acuerdo con el método de transferencia de información que utilice (sincrónico o asincrónico)', 'medium'),
  ('TSINF-195', '195', '53.3. Plataformas tecnológicas que garantizan la seguridad y privacidad de la información y la disponibilidad permanente para prestar los servicios, cumpliendo con los criterios de seguridad, privacidad y protección de datos personales establecidos en la normatividad que regule la materia.', 'medium'),
  ('TSINF-196', '196', '53.4. Suministro de energía eléctrica o baterias que permitan el uso de los instrumentos de comunicación y de los equipos biomédicos cuando aplique.', 'medium'),
  ('TSINF-197', '197', '53.5. Nivel de iluminación homogénea.', 'simple')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSDOT: Dotación (63 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSDOT' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSDOT-001', '1', '1. El prestador de servicios de salud cuenta con el registro de la relación de los equipos biomédicos requeridos para la prestación de servicios de salud, este registro cuenta como mínimo con la siguiente información:', 'medium'),
  ('TSDOT-002', '2', '1.1. Nombre del equipo biomédico.', 'simple'),
  ('TSDOT-003', '3', '1.2. Marca.', 'simple'),
  ('TSDOT-004', '4', '1.3. Modelo.', 'simple'),
  ('TSDOT-005', '5', '1.4. Serie.', 'simple'),
  ('TSDOT-006', '6', '1.5. Registro sanitario para dispositivos médicos o permiso de comercialización para equipos biomédicos de tecnología controlada, cuando lo requiera.', 'medium'),
  ('TSDOT-007', '7', '1.6. Clasificación por riesgo, cuando el equipo lo requiera.', 'simple'),
  ('TSDOT-008', '8', '2. El prestador de servicios de salud garantiza las condiciones técnicas de calidad de los equipos biomédicos, para lo cual cuenta con:', 'medium'),
  ('TSDOT-009', '9', '2.1. Programa de mantenimiento preventivo de los equipos biomédicos, que incluya el cumplimiento de las recomendaciones establecidas por el fabricante o de acuerdo con el protocolo de mantenimiento que tenga definido el prestador, éste último cuando no esté definido por el fabricante.', 'complex'),
  ('TSDOT-010', '10', '2.2. Hoja(s) de vida del(los) equipo(s) biomédico(s), con los registros de los mantenimientos preventivos y correctivos, según corresponda.', 'medium'),
  ('TSDOT-011', '11', '3. El prestador de servicios de salud cuenta con un programa de capacitación en el uso de dispositivos médicos cuando éstos lo requieran, el cual puede ser desarrollado por el fabricante, importador o por el mismo prestador.', 'complex'),
  ('TSDOT-012', '12', '4. La dotación de los servicios de salud está en concordancia con lo definido por el prestador en el estándar de procesos prioritarios.', 'complex'),
  ('TSDOT-013', '13', '5. La suficiencia de equipos biomédicos está relacionada con la frecuencia de uso de los mismo, incluyendo los tiempos del proceso de esterilización, cuando aplique.', 'complex'),
  ('TSDOT-014', '14', '6. El mantenimiento de los equipos biomédicos es ejecutado por el talento humano profesional, tecnólogo o técnico en áreas relacionadas. Este mantenimiento puede ser realizado directamente por el prestador de servicios de salud o mediante contrato o convenio con un tercero.', 'medium'),
  ('TSDOT-015', '15', '7. Los prestadores que oferten servicios de salud en modalidad extramural no pueden elaborar ni adaptar dispositivos médicos sobre medida.', 'medium'),
  ('TSDOT-016', '16', '8. Los servicios de salud que requieren carro de paro, cuenta con la siguiente dotación:', 'simple'),
  ('TSDOT-017', '17', '8.1. Desfibrilador bifásico con sistema de visualización integrado, capacidad de cardioversión, marcapasos transcutáneo y paletas para adultos y pediátricas según aplique.', 'complex'),
  ('TSDOT-018', '18', '8.2. Resucitador  pulmonar  manual.', 'simple'),
  ('TSDOT-019', '19', '8.3. Aspirador o sistema de vacío.', 'complex'),
  ('TSDOT-020', '20', '8.4. Monitor de signos vitales con accesorios que cuenta como mínimo con:', 'simple'),
  ('TSDOT-021', '21', '8.4.1. Trazado electrocardiográfico si no está incorporado en el desfibrilador', 'simple'),
  ('TSDOT-022', '22', '8.4.2.Presión no invasiva', 'simple'),
  ('TSDOT-023', '23', '8.4.3. Saturación de oxígeno que puede estar integrado en el monitor o externo', 'simple'),
  ('TSDOT-024', '24', '8.4.4. Batería', 'simple'),
  ('TSDOT-025', '25', '8.5. Laringoscopio con hojas rectas y curvas para adultos y pediátricas, según aplique', 'simple'),
  ('TSDOT-026', '26', '8.6. Medicamentos, dispositivos médicos e insumos, definidos por el prestador.', 'simple'),
  ('TSDOT-027', '27', '9. Las instituciones prestadoras de servicios de salud con servicios de hospitalización, hospitalización paciente crónico con y sin ventilador, cuidado intensivo neonatal, pediátrico y adulto, urgencias y del grupo quirúrgico, en la modalidad intramural, cuentan con equipos de telecomunicaciones de doble via y conectividad para notificar a la Red de Donación y Trasplantes sobre la existencia de un posible donante.', 'medium'),
  ('TSDOT-028', '28', '10. Las instituciones prestadoras de servicios de salud con servicios de cuidado intensivo pediátrico y adulto que adicionalmente  habiliten el servicio quirúrgico de neurocirugía, cuentan con equipo biomédico para  realizar pruebas auxiliares en el diagnóstico de muerte encefálica, según lo documentado en el estándar de procesos prioritarios.', 'complex'),
  ('TSDOT-029', '29', '11. En los sistemas centralizados de gases medicinales, se realiza el mantenimiento a los componentes del sistema por el personal capacitado por el fabricante.', 'medium'),
  ('TSDOT-030', '30', '12. El prestador de servicios de salud que realice el proceso de esterilización en un área o ambiente dentro o fuera del servicio de salud cuenta con los equipos biomédicos y la dotación de acuerdo con el método utilizado.', 'complex'),
  ('TSDOT-031', '31', '13. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios habilitados cuenta con:', 'complex'),
  ('TSDOT-032', '32', '13.1. Nevera o depósito fria para el almacenamiento de sangre o de sus componentes con sistema de control de temperatura entre 1ºC y 6ºC y alarma audible o sistema de monitoreo que alerte cambios próximos al límite en que la sangre o sus componentes puedan deteriorarse.', 'complex'),
  ('TSDOT-033', '33', '13.2. Equipo para descongelar plasma, cuando se requiera, con sistema de control de temperatura.', 'complex'),
  ('TSDOT-034', '34', '13.3 Congelador para la conservación de plasma o crioprecipitados con registro y control de temperatura por debajo de -18ºC y sistema de alarma audible que alerte cambios próximos al límite en que el componente almacenado pueda deteriorarse, cuando se requiera.', 'complex'),
  ('TSDOT-035', '35', '13.4. Agitador  o rotador de plaquetas con sistema de control de temperatura  entre 20ºC y 24ºC cuando se requiera.', 'complex'),
  ('TSDOT-036', '36', '13.5. Nevera para transporte de componentes sanguíneos, donde se garantice la cadena de frío.', 'simple'),
  ('TSDOT-037', '37', '14. Los servicios de salud donde se realicen procedimientos  bajo sedación fuera de salas de cirugía y monitorización electroencefalográfica con video y radio cuentan con carro de paro.', 'medium'),
  ('TSDOT-038', '38', '15. En los servicios de los grupos quirúrgico, internación y el servicio de urgencias, el prestador de servicios de salud cuenta con accesorios para garantizar empaque cerrado y transporte de los elementos sucios y limplos, como compreseros, vehículos para ta recolección interna de residuos, carros de comida, instrumental, entre otros.', 'medium'),
  ('TSDOT-039', '39', 'Modalidad extramural', 'simple'),
  ('TSDOT-040', '40', '16. Adicional a los criterios enunciados del presente estándar, que le apliquen, el prestador de servicios de salud cuenta con:', 'medium'),
  ('TSDOT-041', '41', '16.1. Sistemas de telecomunicaciones de doble vía.', 'simple'),
  ('TSDOT-042', '42', '16.2. Cuando se realicen pruebas para la detección de eventos de interés en salud pública, cuenta con:', 'simple'),
  ('TSDOT-043', '43', '16.2.1. Microscopio', 'simple'),
  ('TSDOT-044', '44', '16.2.2. Cinta métrica', 'simple'),
  ('TSDOT-045', '45', '16.2.3. Báscula', 'simple'),
  ('TSDOT-046', '46', 'Modalidad telemedicina', 'simple'),
  ('TSDOT-047', '47', '17. El prestador de servicios de salud realiza el mantenimiento de la tecnología de información y de comunicaciones para avalar la calidad de la información, y adicionalmente cuenta con:', 'medium'),
  ('TSDOT-048', '48', '17.1. Prestador remisor', 'simple'),
  ('TSDOT-049', '49', '17.1.1. Documento firmado por un ingeniero biomédico con tarjeta profesional vigente, que certifique que:', 'simple'),
  ('TSDOT-050', '50', '17.1.1.1. Los dispositivos periféricos necesarios, de acuerdo con el tipo de servicios ofertados, garantizan la obtención de la información requerida por el prestador de referencia.', 'medium'),
  ('TSDOT-051', '51', '17.1.1.2. Los equipos de captura utilizados por  el prestador de servicios de salud garantizan que la información obtenida es equivalente a la original, de manera que al ser reproducida se garantice su calidad y confiabilidad.', 'medium'),
  ('TSDOT-052', '52', '17.1.1.3. Los parámetros de digitalización y compresión seleccionados en los equipos durante la captura de datos o imágenes garantizan la resolución necesaria para permitir el diagnóstico.', 'medium'),
  ('TSDOT-053', '53', '17.1.1.4. Si el prestador de servicios  de salud realiza consulta dermatológica en la modalidad de telemedicina cuenta con cámara digital de alta resolución que permita un fácil enfoque de las lesiones de piel y revisión de las imágenes capturadas previo a la transmisión al dermatólogo.', 'medium'),
  ('TSDOT-054', '54', '17.1.2. Documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, que certifique que:', 'simple'),
  ('TSDOT-055', '55', '17.1.2.1. Los dispositivos utilizados para transferencia de información sincrónica por videoconferencia garantizan óptima fidelidad y calidad del video y sonido para el prestador remisor y para e! prestador de referencia.', 'medium'),
  ('TSDOT-056', '56', '17.1.2.2. El software utilizado se adapta al cambio en la disponibilidad del ancho de banda sin perder conexión. En el caso que la videoconferencia sea grabada se deberán contemplar todos criterios de seguridad informática, que permita resguardar adecuadamente la confidencialidad y privacidad del paciente.', 'medium'),
  ('TSDOT-057', '57', '17.1.2.3. Las pantallas o monitores grado médico utilizados para el despliegue de imágenes cuentan con una distancia máxima de 0.25 milímetros entre píxeles
(dot pitch), para garantizar la interpretación adecuada de la información recibida.', 'medium'),
  ('TSDOT-058', '58', '17.2. Prestador de referencia.', 'simple'),
  ('TSDOT-059', '59', '17.2.1. Documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, que certifique que:', 'simple'),
  ('TSDOT-060', '60', '17.2.1.1. Los dispositivos utilizados para transferencia de información sincrónica por videoconferencia garantizan una óptima fidelidad y calidad del video y sonido tanto para el prestador remisor como para el prestador de referencia.', 'medium'),
  ('TSDOT-061', '61', '17.2.1.2. El software utilizado se adapta al cambio de la disponibilidad del ancho de banda sin perder la conexión.', 'simple'),
  ('TSDOT-062', '62', '17.2.1.3. En el caso que la videoconferencia sea grabada se deberán contemplar todos los criterios de seguridad informática, que permita resguardar adecuadamente la confidencialidad y privacidad del paciente.', 'medium'),
  ('TSDOT-063', '63', '17.2.2. Las pantallas o monitores grado médico utilizados para el despliegue de imágenes cuentan con una distancia máxima de 0.19 milímetros entre pixeles (dot pitch), resolución mínima de 1024 x 768 pixeles, como mínimo un ratio de contraste de 500:1 y mínimo de luminancia (brillo) de 250 cd/m2 que permita garantizar la interpretación adecuada de la información recibida.', 'medium')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSMD: Medicamentos, Dispositivos Médicos e Insumos (56 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSMD' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSMD-001', '1', '1. El prestador de servicios de salud lleva registros con la información de todos los medicamentos para uso humano requeridos en la prestación de los servicios que oferte; dichos registros cuentan con la siguiente información:', 'medium'),
  ('TSMD-002', '2', '1.1. Principio activo.', 'simple'),
  ('TSMD-003', '3', '1.2. Forma farmacéutica.', 'simple'),
  ('TSMD-004', '4', '1.3. Concentración', 'simple'),
  ('TSMD-005', '5', '1.4. Lote.', 'simple'),
  ('TSMD-006', '6', '1.5. Fecha de vencimiento.', 'simple'),
  ('TSMD-007', '7', '1.6. Presentación comercial.', 'simple'),
  ('TSMD-008', '8', '1.7. Unidad de medida.', 'simple'),
  ('TSMD-009', '9', '1.8. Registro sanitario vigente o permiso cuando se autorice, expedido por el Invima.', 'simple'),
  ('TSMD-010', '10', '2. Los dispositivos médicos de uso humano requeridos para la prestación de los servicios de salud cuentan con información documentada que dé cuenta de la verificación y seguimiento de la siguiente información:', 'medium'),
  ('TSMD-011', '11', '2.1. Descripción.', 'simple'),
  ('TSMD-012', '12', '2.2. Marca del dispositivo.', 'simple'),
  ('TSMD-013', '13', '2.3. Serie (cuando le aplique).', 'simple'),
  ('TSMD-014', '14', '2.4. Presentación comercial.', 'simple'),
  ('TSMD-015', '15', '2.5. Registro sanitario vigente o permiso de comercialización expedido por el Invima.', 'simple'),
  ('TSMD-016', '16', '2.6. Clasificación por riesgo (información consignada en el registro sanitario o permiso de comercialización).', 'simple'),
  ('TSMD-017', '17', '2.7. Vida útil, cuando le aplique.', 'simple'),
  ('TSMD-018', '18', '2.8. Lote', 'simple'),
  ('TSMD-019', '19', '2.9. Fecha de vencimiento', 'simple'),
  ('TSMD-020', '20', '3. Los reactivos de diagnóstico in vitro requeridos para la prestación de los servicios de salud cuentan con la información documentada que dé cuenta de la verificación y seguimiento de la siguiente información:', 'medium'),
  ('TSMD-021', '21', '3.1. Nombre', 'simple'),
  ('TSMD-022', '22', '3.2. Marca', 'simple'),
  ('TSMD-023', '23', '3.3. Presentación comercial', 'simple'),
  ('TSMD-024', '24', '3.4. Registro sanitario vigente o permiso de comecialización expedido por el Invima.', 'simple'),
  ('TSMD-025', '25', '3.5. Clasificación del riesgo santario', 'simple'),
  ('TSMD-026', '26', '3.6. Vida útil, cuando aplique', 'simple'),
  ('TSMD-027', '27', '3.7. Fecha de vencimiento y lote.', 'simple'),
  ('TSMD-028', '28', '4. El prestador de servicios de salud cuenta con información documentada de los procesos generales según aplique, para:', 'complex'),
  ('TSMD-029', '29', '4.1. Selección', 'simple'),
  ('TSMD-030', '30', '4.2. Adquisición', 'simple'),
  ('TSMD-031', '31', '4.3. Transporte', 'simple'),
  ('TSMD-032', '32', '4.4. Recepción', 'simple'),
  ('TSMD-033', '33', '4.5. Almacenamiento', 'simple'),
  ('TSMD-034', '34', '4.6. Conservación', 'simple'),
  ('TSMD-035', '35', '4.7. Control de fechas de vencimiento', 'simple'),
  ('TSMD-036', '36', '4.8. Control de cadena de frío, manejo de contingencias con la cadena de frío', 'simple'),
  ('TSMD-037', '37', '4.9. Distribución', 'simple'),
  ('TSMD-038', '38', '4.10. Dispensación', 'simple'),
  ('TSMD-039', '39', '4.11. Devolución', 'simple'),
  ('TSMD-040', '40', '4.12. Disposición final', 'simple'),
  ('TSMD-041', '41', '4.13. Seguimiento al uso de medicamentos, homeopáticos, fitoterapéuticos, medicamentos biológicos, componentes anatómicos, dispositivos médicos (incluso los sobre medida, elementos de rayos X y de uso odontológico), reactivos de diagnóstico in vitro; así como de los demás insumos asistenciales que se utilicen incluidos los que se encuentran en los depósitos o almacenes del prestador de servicios de salud y en la modalidad extramural.', 'medium'),
  ('TSMD-042', '42', '5. El prestador de servicios de salud que realice algún tipo de actividad con medicamentos de control especial para la prestación de servicios de salud cuenta con la resolución de autorización vigente, expedida por el Fondo Nacional de Estupefacientes o la entidad que haga sus veces.', 'medium'),
  ('TSMD-043', '43', '6. El prestador de servicios de salud cuenta con información documentada de la planeación y ejecución de los programas de farmacovigilancia, tecnovigilancia y reactivovigilancia, que garanticen el seguimiento al uso de medicamentos, dispositivos médicos (incluidos los sobre medida) y reactivos de diagnóstico in vitro, cuando aplique.', 'complex'),
  ('TSMD-044', '44', '7. El prestador de servicios de salud que cuente con reservas de medicamentos, homeopáticos, fititerapéuticos, medicamentos biológicos, componentes anatómicos, dispositivos médicos (incluidos los sobre medida), reactivos de diagnóstico in vitro, y demás insumos asistenciales, debe garantizar que se almacenen en condiciones apropiadas de temperatura, humedad, ventilación segregación y seguridad de acuerdo con las condiciones definidas por el fabricante o el banco del componente anatómico, según aplique, y contar con instrumento para medir humedad reltiva y temperatura y evidencia su registro, control y gestión.', 'complex'),
  ('TSMD-045', '45', '8. Para la aplicación del protocolo de lavado de manos o higienización, los servicios de salud cuentan con los insumos de aseo, limpieza y secado que garanticen su cumplimiento.', 'complex'),
  ('TSMD-046', '46', '9. La suficiencia de dispositivos médicos está relacionada con la frecuencia de uso de los mismos, incluyendo los tiempos del proceso de esterililización, cuando aplique.', 'complex'),
  ('TSMD-047', '47', '10. El prestador de servicios de salud cuenta con paquete para el manejo de derrames y rupturas de medicamentos, ubicado en un lugar de fácil acceso, visible y con adecuada señalización, disponible para su uso en los servicios y ambientes donde se requieran. El prestador de servicios de salud define su contenido de acuerdo con los medicamentos utilizados y lo sugerido por el fabricante en las fichas técnicas.', 'medium'),
  ('TSMD-048', '48', '11. En los servicios donde se requiera carro de paro, adicional a la dotación definida en el presente manual, los medicamentos, dispositivos médicos e insumos deber ser definidos por el prestador de servicios de salud de acuerdo con la morbilidad. riesgos de complicaciones más frecuentes y lo documentado para el procedimiento de reanimación cerebro cardio pulmonar.', 'medium'),
  ('TSMD-049', '49', '12. El prestador debe mantener condiciones de almacenamiento, conservación, control de fechas de vencimiento, uso y custodia de los medicamentos, dispositivos médicos e insumos contenidos en los carros de paro.', 'medium'),
  ('TSMD-050', '50', '13. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre transfusional, pero realiza procedimientos de transfusión, cuenta con convenio o contrato vigente con un banco de sangre certificado por la autoridad competente para el suministro de sangre, componentes sanguíneos y la realización de las pruebas pre transfusionales cuando el prestador de servicios de salud no las realice', 'complex'),
  ('TSMD-051', '51', '14. Cuando el prestador de servicios de salud fabrique en su institución gases medicinales, cuenta con la certificación vigente de Buenas Prácticas de Manufactura expedida por el Invima o la entidad que haga sus veces.', 'medium'),
  ('TSMD-052', '52', '15. En los servicios de transporte asistencial, atención prehospitalaria y urgencias cuenta con kit de emergencias para la atención a víctimas de ataques con agentes químicos.', 'medium'),
  ('TSMD-053', '53', '16. Adicional a los criterios enunciados de presente estándar, que le aplique a estas modalidades, el prestador de servicios en salud cuenta con:', 'medium'),
  ('TSMD-054', '54', '16.1. Dispositivos médicos e insumos asistenciales según la patalogía del paciente o eventos de interés en salud pública cuando se requiera.', 'medium'),
  ('TSMD-055', '55', '16.2. Medicamentos de acuerdo con inventario establecido por el prestador acorde a lo documentado en sus procesos prioritarios, cuando se requiera.', 'complex'),
  ('TSMD-056', '56', '17. El prestador de servicio de salud cumple con los criterios que le apliquen del presente estándar.', 'simple')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSPP: Procesos Prioritarios (109 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSPP' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSPP-001', '1', '1. El prestador de servicios de salud cuenta con una política de seguridad del paciente acorde con los lineamientos expedidos por el Ministerio de Salud y Protección Social.', 'complex'),
  ('TSPP-002', '2', '2. El prestador de servicios de salud realiza actividades encaminadas a gestionar la seguridad del paciente.', 'simple'),
  ('TSPP-003', '3', '3. El prestador de servicios de salud cuenta con un comité o instancia que orienta y promueve la política de seguridad del paciente, el control de infecciones y ta optimización del uso de antibióticos, cuando tos prescriba o administre. En el caso de profesionales independientes de salud podrá ser el mismo prestador.', 'complex'),
  ('TSPP-004', '4', '4. El prestador de servicios de salud adopta y realiza las siguientes prácticas seguras, según aplique a su servicio de salud y cuenta con información documentada para:', 'medium'),
  ('TSPP-005', '5', '4.1. Asegurar la correcta identificación del paciente en los procesos asistenciales. (que incluya como mínimo dos identificadores: nombre completo y número de identificación)', 'complex'),
  ('TSPP-006', '6', '4.2. Gestionar y desarrollar una adecuada comunicación entre las personas que atienden y cuidan a los pacientes que incluyan enfoques diferenciales.', 'medium'),
  ('TSPP-007', '7', '4.3. Detectar, prevenir y reducir infecciones asociadas con la atención en salud (que incluya protocolo de higiene de manos o higienización con soluciones a base de alcohol).', 'complex'),
  ('TSPP-008', '8', '4.4. Detectar, ana!izar y gestionar eventos adversos.', 'simple'),
  ('TSPP-009', '9', '4.5. Garantizar la funcionalidad de los procedimientos de consentimiento  informado.', 'simple'),
  ('TSPP-010', '10', '4.6. Mejorar la seguridad en la utilización de medicamentos, en los servicios donde aplique.', 'simple'),
  ('TSPP-011', '11', '4.7. Prevenir y reducir la frecuencia de caídas, en los servicios donde aplique.', 'simple'),
  ('TSPP-012', '12', '4.8. Garantizar la atención segura de ta gestante y el recién nacido, en los servicios donde aplique.', 'simple'),
  ('TSPP-013', '13', '4.9. Prevenir complicaciones asociadas a disponibilidad y manejo de sangre, componentes y a la transfusión sanguínea, en los servicios donde aplique.', 'medium'),
  ('TSPP-014', '14', '4.10. Prevenir úlceras por presión, en los servicios donde aplique.', 'simple'),
  ('TSPP-015', '15', '4.11. Mejorar la seguridad en los procedimientos quirúrgicos, en los servicios donde aplique.', 'simple'),
  ('TSPP-016', '16', '5. El prestador de servicios de salud promueve la cultura de seguridad del paciente que involucra a todo el personal de manera sistemática con un enfoque educativo no punitivo mediante:', 'medium'),
  ('TSPP-017', '17', '5.1. Capacitación del personal en el tema de seguridad del paciente y en los principales riesgos de la atención.', 'simple'),
  ('TSPP-018', '18', '5.2. Actividades donde se ilustra al paciente y sus allegados en el autocuidado de su seguridad.', 'simple'),
  ('TSPP-019', '19', '6. El prestador de servicios de salud cuenta con información documentada de las actividades y procedimientos que se realizan en el servicio acordes con su objeto, alcance y enfoque diferencial, mediante guías de práctica clínica- GPC, procedimientos de atención, protocolos de atención y otros documentos que el prestador de servicios de salud determine, dicha  información  incluye talento humano, equipos biomédicos, medicamentos y dispositivos médicos e insumos requeridos.', 'complex'),
  ('TSPP-020', '20', '7. La información documentada es conocida mediante acciones de formación continua por el talento humano encargado y responsable de su aplicación, incluyendo el talento humano en entrenamiento, y existe evidencia de su socialización.', 'medium'),
  ('TSPP-021', '21', '8. Las guías de práctica clínica y protocolos a adoptar son en primera medida los que disponga el Ministerio de Salud y Protección Social. En caso de no estar disponibles, o si existe nueva evidencia científica que actualice alguna o algunas de las recomendaciones de las guías de práctica clínica o requerimientos de los protocolos, el prestador de servicios de salud adopta, adapta o desarrolla guías de práctica clínica o protocolos basados en evidencia científica, publicados nacional o internacionalmente.', 'complex'),
  ('TSPP-022', '22', '9. El prestador de servicios de salud de acuerdo con las patologías más frecuentes en el servicio define la guía o guías de práctica clínica a adoptar, o adaptar o desarrollar.', 'medium'),
  ('TSPP-023', '23', '10. El prestador de servicios de salud cuenta con información documentada de la adopción, o adaptación o desarrollo de guías práctica clínica o protocolos basados en evidencia científica.', 'complex'),
  ('TSPP-024', '24', '11. Los servicios de salud donde se atiendan pacientes con enfermedades terminales, crónicas, degenerativas e irreversibles, a los cuales se determine el manejo del dolor y cuidado paliativo, cuentan con información documentada para su manejo.', 'medium'),
  ('TSPP-025', '25', '12. El prestador de servicios de salud cuenta con la siguiente información documentada:', 'simple'),
  ('TSPP-026', '26', '12.1. Detección, prevención y disminución del riesgo de accidentes e incidentes de carácter radiológico, en los servicios donde aplique.', 'medium'),
  ('TSPP-027', '27', '12.2. Aseo, limpieza y desinfección de áreas y superficies.', 'simple'),
  ('TSPP-028', '28', '12.3. Procedimiento de reanimación cerebro cardio pulmonar, en los servicios donde se realice.', 'simple'),
  ('TSPP-029', '29', '12.4. Acciones para prevenir las flebitis infecciosas, químicas y mecánicas en los servicios donde se realicen procedimientos de venopunción.', 'medium'),
  ('TSPP-030', '30', '12.5. Aspectos de bioseguridad acordes con las condiciones y características del servicio.', 'simple'),
  ('TSPP-031', '31', '12.6. Descontaminación por derrames de sangre u otros fluidos corporales.', 'simple'),
  ('TSPP-032', '32', '12.7. Manejo de gases medicinales que incluya como mínimo la atención de emergencias y sistema de alarma, cuando se utilicen.', 'complex'),
  ('TSPP-033', '33', '13. El prestador de servicios de salud que realice el proceso de esterilización cuenta con la siguiente información  documentada:', 'complex'),
  ('TSPP-034', '34', '13.1. Buenas prácticas de esterilización de acuerdo con los procedimientos y técnicas que se utilicen, que describa como mínimo los siguientes aspectos:', 'medium'),
  ('TSPP-035', '35', '13.1.1 Recibo de productos contaminados y entrega de material estéril.', 'simple'),
  ('TSPP-036', '36', '13.1.2. Transporte', 'simple'),
  ('TSPP-037', '37', '13.1.3. Lavado, secado y lubricación.', 'simple'),
  ('TSPP-038', '38', '13.1.4. Empaque.', 'simple'),
  ('TSPP-039', '39', '13.1.5. Etiquetado.', 'simple'),
  ('TSPP-040', '40', '13.1.6. Esterilización.', 'simple'),
  ('TSPP-041', '41', '13.1.7. Almacenamiento.', 'simple'),
  ('TSPP-042', '42', '13.1.8. Verificación de la integridad del material estéril', 'simple'),
  ('TSPP-043', '43', '13.1.9. Control de calidad que incluya el análisis de los reportes de dicho control, para la toma de medidas preventivas y correctivas.', 'medium'),
  ('TSPP-044', '44', '14. Cuando un prestador de servicios de salud contrate el proceso de esterilización con un tercero, cuenta con un contrato, convenio o acuerdo escrito entre las partes, el cual debe incluir como mínimo las características de calidad de los productos, la supervisión del estado de las instalaciones y la aplicación de los procedimientos del tercero para realizar el proceso. No obstante, el prestador de servicios de salud que requiere el proceso de esterilización es el responsable de garantizar la esterilidad y el desempeño del producto final.', 'complex'),
  ('TSPP-045', '45', '15. Los prestadores de servicios de salud tienen definidos procedimientos que garanticen el cumplimiento del no reúso de dispositivos médicos cuando el fabricante así lo haya establecido.', 'medium'),
  ('TSPP-046', '46', '16. Hasta tanto el Ministerio de Salud y Protección Social regule la materia, el prestador de servicios de salud podrá reusar dispositivos médicos, siempre y cuando el fabricante de dichos dispositivos autorice su reúso. En tal caso, el prestador de servicios de salud cuenta con información documentada que defina:', 'medium'),
  ('TSPP-047', '47', '16.1. Los procedimientos, siguiendo las recomendaciones del fabricante, para el reprocesamiento y control de calidad que demuestren la eficacia, desempeño y esterilidad del producto.', 'medium'),
  ('TSPP-048', '48', '16.2. Acciones de seguimiento a través de los comités de infecciones, de seguridad del paciente y del programa de tecnovigilancia, que garanticen que el dispositivo no ha perdido la eficacia y desempeño para el cual fue diseñado, ni exponga al riesgo de infecciones o complicaciones al usuario.', 'complex'),
  ('TSPP-049', '49', '16.3. Los profesionales independientes de salud realizarán el seguimiento a través del programa de tecnovigilancia.', 'complex'),
  ('TSPP-050', '50', '17. Para la referencia de pacientes, el prestador de servicios de salud cuenta con la siguiente información documentada:', 'simple'),
  ('TSPP-051', '51', '17.1. Estabilización del paciente antes del traslado.', 'simple'),
  ('TSPP-052', '52', '17.2. Medidas para el traslado.', 'simple'),
  ('TSPP-053', '53', '17.3. Lista de chequeo de los documentos necesarios para el traslado que incluya:', 'simple'),
  ('TSPP-054', '54', '17.3.1. Diligenciamiento del formato de referencia de pacientes.', 'simple'),
  ('TSPP-055', '55', '17.3.2. Resultados de apoyos diagnósticos realizados al paciente.', 'simple'),
  ('TSPP-056', '56', '17.3.3. Resumen de historia clínica.', 'simple'),
  ('TSPP-057', '57', '17.3.4. Mecanismos tecnológicos que le permitan realizar el proceso (software, correo, entre otros).', 'complex'),
  ('TSPP-058', '58', '17.3.5. Talento humano que debe responsabilizarse de cada una de las etapas del proceso.', 'complex'),
  ('TSPP-059', '59', '17.3.6. La referencia de pacientes que se detecten como víctimas de violencia sexual debe hacerse a un servicio de urgencias.', 'medium'),
  ('TSPP-060', '60', '18. Cuando se realicen procedimientos bajo sedación fuera de salas cirugía, el prestador de servicios de salud cuenta con información documentada para:', 'medium'),
  ('TSPP-061', '61', '18.1. Realizar la sedación', 'simple'),
  ('TSPP-062', '62', '18.2. Definición de la atención por médico especialista en anestesiología cuando se identifiquen riesgos para el paciente relacionados con la sedación', 'medium'),
  ('TSPP-063', '63', '18.3. Manejo de emergencias.', 'simple'),
  ('TSPP-064', '64', '18.4. Seguimiento al riesgo, que incluya fichas técnicas de indicadores de complicaciones terapéuticas y medicamentosas, relacionadas con la sedación, medición, seguimiento y planes de mejoramiento.', 'medium'),
  ('TSPP-065', '65', '18.5. Lista de chequeo, consignada en la historia clínica del paciente, que incluya la verificación de:', 'simple'),
  ('TSPP-066', '66', '18.5.1. Evaluación de la vía aérea.', 'simple'),
  ('TSPP-067', '67', '18.5.2. Determinación del tiempo de ayuno.', 'simple'),
  ('TSPP-068', '68', '18.5.3. Registro de monitoreo del nivel de conciencia, la saturación de oxígeno, frecuencia cardíaca, tensión arterial y frecuencia respiratoria.', 'medium'),
  ('TSPP-069', '69', '18.5.4. Registro de las variables hemodinámicas y respiratorias, a intervalos regulares', 'simple'),
  ('TSPP-070', '70', '18.6. Observación bajo la supervisión del profesional que realiza la sedación.', 'simple'),
  ('TSPP-071', '71', '18.7. Todos estos registros se deben realizar antes, durante la intervención y hasta el momento del egreso del paciente.', 'simple'),
  ('TSPP-072', '72', '18.8. Recomendaciones de egreso suministradas al acompañante o acudiente.', 'simple'),
  ('TSPP-073', '73', '19. Si el prestador de servicios de salud no tiene habilitado el servicio de gestión pre transfusional, pero realiza procedimientos de transfusión sanguínea en alguno de sus servicios de salud habilitados, cuenta con la siguiente información documentada:', 'complex'),
  ('TSPP-074', '74', '19.1. Transporte, conservación, embalaje y remisión de muestras al banco de sangre para la realización de pruebas pre transfusionales.', 'medium'),
  ('TSPP-075', '75', '19.2. Manejo, investigación y análisis de las reacciones adversas a las transfusiones sanguíneas y procesos de hemovigilancia.', 'complex'),
  ('TSPP-076', '76', '19.3. Guía de práctica clínica para el uso de componentes sanguíneos.', 'simple'),
  ('TSPP-077', '77', '20. La Institución Prestadora de Servicios de Salud que cuenten con servicios de salud de los grupos de consulta externa, internación o el servicio de urgencias, cuenta con:', 'medium'),
  ('TSPP-078', '78', '20.1. Documento del proceso institucional que orienta la atención en salud de las víctimas de violencias sexuales.', 'complex'),
  ('TSPP-079', '79', '20.2. Documento que dé cuenta la conformación del equipo institucional para la atención integral en salud para las víctimas de violencias sexuales', 'medium'),
  ('TSPP-080', '80', '21. El Profesional Independiente de Salud y las Entidades con Objeto Social Diferente que oferten y presten servicios de salud de los grupos de consulta externa y los prestadores de servicios de salud de Transporte Especial de Pacientes cuentan con documento del proceso que orienta la atención en salud de las víctimas de violencias sexuales.', 'complex'),
  ('TSPP-081', '81', '22. En los servicios de transporte asistencial, atención prehospitalaria y urgencias, se cuenta con documento del proceso que orienta la atención en salud a victimas de ataques con agentes químicos.', 'complex'),
  ('TSPP-082', '82', '23. Los prestadores de servicios de salud cuentan con información documentada de las condiciones de almacenamiento, conservación, control de fechas de vencimiento, uso y custodia de los medicamentos, dispositivos médicos e insumos contenidos en los kits de derrames de medicamentos, ataque con agentes químicos y de violencias sexuales, según su contenido.', 'medium'),
  ('TSPP-083', '83', '24. Las Instituciones Prestadoras de Servicios de  Salud con servicios de hospitalización, hospitalización de paciente crónico con y sin ventilador, cuidado intensivo neonatal, pediátrico y adulto, urgencias y del grupo quirúrgico, en la modalidad intramural, cuentan con la siguiente Información documentada:', 'medium'),
  ('TSPP-084', '84', '24.1. Manejo de la enfermedad cerebro vascular.', 'simple'),
  ('TSPP-085', '85', '24.2. Manejo del Trauma Craneoencefálico.', 'simple'),
  ('TSPP-086', '86', '24.3. Detección de donantes de componentes anatómicos', 'simple'),
  ('TSPP-087', '87', '24.4. Mantenimiento del donante de componentes anatómicos', 'simple'),
  ('TSPP-088', '88', '25. Las Instituciones Prestadoras de Servicios de Salud, con servicios de cuidado intensivo pediátrico y adulto que cuenten con servicios quirúrgicos de neurocirugía de alta complejidad, cuentan con información documentada del procedimiento para el diagnóstico de muerte encefálica y muerte en asistolia.', 'medium'),
  ('TSPP-089', '89', '26. Los servicios de salud que realicen pruebas de interés en salud pública deben inscribirse en el Registro de Laboratorios- RELAB.', 'medium'),
  ('TSPP-090', '90', '27. Cuando el prestador de servicios de salud realice "pruebas en el punto de atención del paciente - (Point of Care Testing - POCT)" en un servicio habilitado cuenta con:', 'medium'),
  ('TSPP-091', '91', '27.1. Información documentada sobre la toma, procesamiento, control de calidad y entrega de resultados.', 'simple'),
  ('TSPP-092', '92', '27.2. Controles de calidad realizados por un servicio de laboratorio clínico que puede ser propio o contratado para tal fin. cuando aplique, de acuerdo a las especificaciones del fabricante.', 'medium'),
  ('TSPP-093', '93', '27.3. Análisis de los reportes del control de calidad y toma de medidas preventivas y correctivas.', 'simple'),
  ('TSPP-094', '94', 'Adicional a los criterios enunciados que le aplique, para las siguientes modalidades el prestador de servicios de salud cuenta con la siguiente información documentada:', 'medium'),
  ('TSPP-095', '95', 'Modalidad extramural jornadas en salud y unidad móvil', 'simple'),
  ('TSPP-096', '96', '28. Orientación a los usuarios sobre las condiciones, requisitos y restricciones de acceso, permanencia y salida del vehículo, en condiciones de rutina o en condiciones de emergencia. a cargo del conductor del vehículo y el talento humano en salud.', 'medium'),
  ('TSPP-097', '97', '29. Mecanismos que garanticen comunicación para el seguimiento de los pacientes que lo requieran.', 'simple'),
  ('TSPP-098', '98', '30. Mecanismos de supervisión de las actividades realizadas en el marco de los eventos de interés en salud pública, cuando aplique.', 'medium'),
  ('TSPP-099', '99', 'Modalidad telemedicina - Prestador Remísor', 'simple'),
  ('TSPP-100', '100', '31. Información documentada de la prestación de servicios en esta modalidad que evidencie:', 'simple'),
  ('TSPP-101', '101', '31.1. La o las categorías de tetemedicina que se ofrece(n) en cada uno de  los servicios habilitados en dicha modalidad y si se presta el servicio como prestador remisor o como prestador de referencia.', 'medium'),
  ('TSPP-102', '102', '31.2. Los flujos de la información', 'simple'),
  ('TSPP-103', '103', '31.3.Los responsables de la atención', 'simple'),
  ('TSPP-104', '104', '31.4. El método de comunicación que se utiliza (sincrónico o asincrónico) para la atención y los criterios para la identificación de los casos en los cuales se debe transferir y recibir la información en tiempo real (sincrónico) o mediante almacenamiento - envio (asincrónico).', 'medium'),
  ('TSPP-105', '105', '31.5. Las caracteristicas y formas de relacionamiento entre prestadores de telemedicina (remisar y de referencia) cuando aplique, definiendo los tiempos de respuesta.', 'medium'),
  ('TSPP-106', '106', '31.6. Procedimiento para la captura, almacenamiento y transmisión de la información.', 'simple'),
  ('TSPP-107', '107', '31.7. Parámetros para la digitalización y compresión durante la captura de datos o imágenes que garanticen la resolución necesaria para permitir el diagnóstico.', 'medium'),
  ('TSPP-108', '108', 'Modalidad telemedicina - Prestador de referencia', 'simple'),
  ('TSPP-109', '109', '32. Adicional a los criterios solicitados para el prestador remisor, cuenta con información documentada de las actividades y procedimientos de los servicios que oferte, acordes con su objeto, alcance y enfoque diferencial, mediante guías de práctica clínica- GPC, procedimientos de atención, protocolos de atención y otros documentos que el prestador de servicios de salud determine, dicha información incluye talento humano, equipos biomédicos, medicamentos y dispositivos médicos e insumos  requeridos.', 'complex')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSHCR: Historia Clínica y Registros (56 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSHCR' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSHCR-001', '1', '1. Toda atención de primera vez a un usuario debe incluir el proceso de apertura de historia clínica. Todos los pacientes atendidos cuentan con historia clínica.', 'complex'),
  ('TSHCR-002', '2', '2. El prestador de servicios de salud cuenta con procedimientos para utilizar una historia única y para el registro de entrada y salida de historias del archivo físico. Ello implica que el prestador de servicios de salud cuente con un mecanismo para unificar la información de cada paciente y su disponibilidad para el equipo de salud.', 'medium'),
  ('TSHCR-003', '3', '3. Los medios electrónicos para la gestión de la historia clínica garantizan la confidencialidad y seguridad, así como el carácter permanente de registrar en ésta y en otros registros asistenciales, sin que se puedan modificar los datos una vez se guarden los registros.', 'complex'),
  ('TSHCR-004', '4', '4. Las historias clínicas cuentan con los componentes y los contenidos mínimos definidos en la normatividad que regula la materia', 'medium'),
  ('TSHCR-005', '5', '5. La historia clínica y los registros asistenciales se diligencian en forma clara, legible, sin tachones, enmendaduras, intercalaciones, sin dejar espacios en blanco y sin utilizar siglas.', 'medium'),
  ('TSHCR-006', '6', '6. Cada anotación lleva la fecha y hora en la que se realiza, con el nombre completo y firma del autor de la misma.', 'simple'),
  ('TSHCR-007', '7', '7. El diligenciamiento de los registros de atención de la historia clínica se realiza simultánea o inmediatamente después de la atención en salud.', 'medium'),
  ('TSHCR-008', '8', '8. La historia clínica y demás registros son conservados en archivo único garantizando la custodia y confidencialidad de los documentos o registros protegidos legalmente por reserva.', 'medium'),
  ('TSHCR-009', '9', '9. El prestador de servicios de salud cuenta con un procedimiento de consentimiento informado que incluye mecanismos para verificar su aplicación, para que el paciente o su responsable, aprueben o no documentalmente, el procedimiento e intervención en salud a que va a ser sometido, previa información de los beneficios, riesgos, alternativas e implicaciones del acto asistencial', 'medium'),
  ('TSHCR-010', '10', '10. Cuando el prestador de servicios de salud utilice mecanismos electrónicos, ópticos o similares para generar, recibir, almacenar, o disponer datos de la historia clínica y para conservarlos, debe avalar que el mecanismo utilizado cumple con características de: autenticidad, fiabilidad, integridad y disponibilidad del documento, de acuerdo con lo establecido en la normatividad vigente expedida por el Archivo General de la Nación, la Superintendencia de Industria y Comercio y el Ministerio de Tecnologías de información y Comunicaciones, para lo cual, el prestador presentará un documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, certificando que el mecanismo usado por el prestador cumple con la normatividad mencionada', 'medium'),
  ('TSHCR-011', '11', 'Cuenta con los siguientes registros, cuando los prestadores de servicios de salud realicen el proceso de esterilización dentro del servicio y fuera de centrales de esterilización:', 'complex'),
  ('TSHCR-012', '12', '11.1. Actividades documentadas y realizadas en el procedimiento de reúso de dispositivos médicos acorde con las recomendaciones del fabricante, incluyendo el número de reúsos por cada dispositivo esterilizado.', 'medium'),
  ('TSHCR-013', '13', '11.2. Registro de cargas.', 'simple'),
  ('TSHCR-014', '14', '11.3. Resultados del control de calidad.', 'simple'),
  ('TSHCR-015', '15', '11.4. Listas del contenido de los paquetes que se esterilizan.', 'simple'),
  ('TSHCR-016', '16', '11.5. Etiquetado de cada paquete que permita la trazabilidad de la esterilización.', 'simple'),
  ('TSHCR-017', '17', '12. Cuando se realicen procedimientos de transfusión de sangre o sus componentes, cuenta con los siguientes registros:', 'simple'),
  ('TSHCR-018', '18', '12.1. Información de los componentes sanguíneos.', 'simple'),
  ('TSHCR-019', '19', '12.2. Solicitud de los componentes sanguíneos.', 'simple'),
  ('TSHCR-020', '20', '12.3. Muestras tomadas para la realización de pruebas pre transfusionales.', 'simple'),
  ('TSHCR-021', '21', '12.4. Muestras remitidas al Banco de Sangre y resultado de las pruebas pre transfusionales con el nombre del Banco de Sangre que las realizó, cuando el prestador no cuente con el servicio de gestión pre transfusional.', 'complex'),
  ('TSHCR-022', '22', '12.5. Información post-transfusional.', 'simple'),
  ('TSHCR-023', '23', '12.6. Informe ante la secretaria departamental o distrital, o la entidad que tenga a cargo dichas competencias, sobre la estadistica mensual de componentes sanguineos trasfundidos.', 'medium'),
  ('TSHCR-024', '24', '12.7. Temperaturas de los equipos biomédicos que lo requieran.', 'simple'),
  ('TSHCR-025', '25', '12.8. Entrega para incineración de bolsas de sangre y de las unidades de sangre o componentes sanguíneos descartados.', 'simple'),
  ('TSHCR-026', '26', '12.9. Transfusiones en la historia clínica del paciente, que incluya como mínimo la razón para la transfusión, el producto y volumen que fue transfundido y la hora de la transfusión.', 'medium'),
  ('TSHCR-027', '27', '13. Las instituciones prestadoras de servicios de salud con servicios en la modalidad intramural para hospitalización, hospitalización paciente crónico con y sin ventilador, cuidados intensivos neonatales, pediatricos y adultos, urgencias y servicios del grupo quirurgico, cuentan con:', 'medium'),
  ('TSHCR-028', '28', '13.1. Registro de donantes detectados', 'simple'),
  ('TSHCR-029', '29', '13.3. Registros en la historia clínica de la información sobre el proceso de donación efectuado por los profesionales de salud inscritos ante el Instituto Nacional de Salud', 'complex'),
  ('TSHCR-030', '30', 'Modalidad Extramural', 'simple'),
  ('TSHCR-031', '31', '14. La historia clínica utilizada en la modalidad extramural es custodiada por el prestador de servicios de salud que oferta y presta el servicio de salud en la modalidad extramural y cuenta con los siguientes registros:', 'medium'),
  ('TSHCR-032', '32', 'Modalidad Extramural Domiciliaria', 'simple'),
  ('TSHCR-033', '33', '14.1. Valoración de ingreso con el respectivo plan de tratamiento', 'complex'),
  ('TSHCR-034', '34', '14.2. Nombre de los pacientes atendidos', 'simple'),
  ('TSHCR-035', '35', '14.3. Registros de referencia y contrarreferencia, cuando se requieran', 'simple'),
  ('TSHCR-036', '36', '14.4. Cuidados por parte del personal de salud', 'simple'),
  ('TSHCR-037', '37', '14.5. Cuidados encargados a la familia cuando aplique', 'simple'),
  ('TSHCR-038', '38', 'Modalidad Extramural Jornada de Salud y Unidad Móvil', 'simple'),
  ('TSHCR-039', '39', '14.6. Registro de rutas, horarios y frecuencias de la prestación de los servicios ofertados', 'simple'),
  ('TSHCR-040', '40', '14.7. Nombre de los pacientes atendidos.', 'simple'),
  ('TSHCR-041', '41', '14.8. Nombre de los pacientes trasladados', 'simple'),
  ('TSHCR-042', '42', '14.9. Fecha y hora de ingreso al servicio', 'simple'),
  ('TSHCR-043', '43', '14.10. Cuidados por parte del personal de salud', 'simple'),
  ('TSHCR-044', '44', '14.11. Cuidados encargados a la familia cuando aplique', 'simple'),
  ('TSHCR-045', '45', '14.12. Registros de las fechas de llegada y de salida, cuando aplique', 'simple'),
  ('TSHCR-046', '46', '14.13. Registros de las actividades realizadas.', 'simple'),
  ('TSHCR-047', '47', 'Modalidad Telemedicina - Prestador remisor  - Prestador de referencia 
Cuenta con:', 'simple'),
  ('TSHCR-048', '48', '15. Documento firmado por un ingeniero de sistemas con tarjeta profesional vigente, que certifique:', 'simple'),
  ('TSHCR-049', '49', '15.1. Los mecanismos que garanticen la custodia, seguridad confidencialidad y conservación integral, durante la transmisión y almacenamiento de la información contenida en la historia clínica y demás registros asistenciales y la reproducibilidad de la información de acuerdo con la legislación vigente', 'medium'),
  ('TSHCR-050', '50', '15.2. Los mecanismos de compresión utilizados por el prestador garantizan que la información recuperada corresponda al dato, imagen o señal original (compresión sin pérdidas).', 'medium'),
  ('TSHCR-051', '51', '15.3. El método utilizado para el uso de la firma electrónica o digital', 'simple'),
  ('TSHCR-052', '52', '15.4. La encriptación de la información para su transmisión y mecanismos de acceso a la misma de acuerdo con lo definido por el prestador de servicios de salud.', 'medium'),
  ('TSHCR-053', '53', '15.5. Los sistemas de seguridad y control de acceso a la aplicación, según tipo de usuario cuando se utilizan sistemas de información compartidos o de acceso remoto', 'medium'),
  ('TSHCR-054', '54', '16. Plan de contingencia en caso de fallas del sistema activo o pérdida de datos', 'complex'),
  ('TSHCR-055', '55', '17. Todos los eventos y transacciones que se realicen con ocasión de la prestación de servicios en la modalidad de telemedicina son documentados y almacenados, y son parte integral de la historia clínica', 'medium'),
  ('TSHCR-056', '56', '18. Registro de las atenciones realizadas en la modalidad de telemedicina', 'simple')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- TSINT: Interdependencia de Servicios (6 criterios)
INSERT INTO evaluation_criteria (code, number, name, description, complexity, standard_id, is_mandatory, status)
SELECT c.code, c.number, c.name, c.name, c.complexity,
  (SELECT id FROM evaluation_standards WHERE evaluation_standards.code = 'TSINT' LIMIT 1),
  TRUE, 'active'
FROM (VALUES
  ('TSINT-001', '1', '1. Cuando el servicio interdependiente sea contratado, debe mediar un contrato o un acuerdo escrito entre las dos partes, en el que se establezca que el servicio interdependiente apoya el servicio principal, estableciendo como mínimo:', 'medium'),
  ('TSINT-002', '2', '1.1 Calidad en la entrega de los productos', 'simple'),
  ('TSINT-003', '3', '1.2. Procedimientos documentados de atención en cada servicio independiente', 'simple'),
  ('TSINT-004', '4', '1.3 Tiempos de entrega de los productos', 'simple'),
  ('TSINT-005', '5', '1.4 Supervisión al contratista que garantice la seguridad del resultado del producto contratado.', 'simple'),
  ('TSINT-006', '6', '2. Cuando fuera de salas de cirugía, se realicen procedimientos bajo sedación y monitorización electroencelfalografica con video y radio; el prestador de servicios de salud tendrá disponibilidad del servicio de transporte asistencial', 'medium')
) AS c(code, number, name, complexity)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.name;

-- Re-vincular a todos los cuestionarios maestros publicados
INSERT INTO questionnaire_criteria (questionnaire_id, criterion_id)
SELECT q.id, ec.id
FROM questionnaires q CROSS JOIN evaluation_criteria ec
WHERE q.service_id IS NULL AND q.status = 'published'
ON CONFLICT DO NOTHING;

UPDATE questionnaires SET total_criteria = (
  SELECT COUNT(*) FROM questionnaire_criteria WHERE questionnaire_id = questionnaires.id
) WHERE service_id IS NULL;

-- Total: 512 criterios
SELECT COUNT(*) AS total FROM evaluation_criteria;
COMMIT;