-- ============================================================
-- Migración: Calidad Laboratorio (Res. 1619) en Gestión Documental
-- 56 slots de documentos por tipo de prestador (IPS e Independiente)
-- Fuente: Res. 1619 de 2015 — Estándares de calidad para laboratorios clínicos
-- Secciones: Organización y Gestión (42) | Talento Humano (9) | Infraestructura y Dotación (5)
-- ============================================================

-- ── IPS ──────────────────────────────────────────────────────
INSERT INTO document_catalog
  (code, name, description, category, standard_reference, is_mandatory, applies_to_all, provider_type)
VALUES
  -- Organización y Gestión
  ('IPS-L19-001', 'Copia del distintivo de habilitación',
   'Copia del certificado o distintivo de habilitación vigente del laboratorio como prestador de servicios de salud.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-002', 'Certificado de representación legal',
   'Certificado de representación legal actualizado (no mayor a 30 días de expedición).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-003', 'Organigrama institucional y acto administrativo',
   'Organigrama de la entidad o del laboratorio con su acto administrativo de aprobación. El laboratorio debe estar claramente identificado en la estructura funcional.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-004', 'Portafolio de Servicios',
   'Portafolio de servicios del laboratorio aprobado y vigente.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-005', 'Portafolio de pruebas que procesa',
   'Listado actualizado de las pruebas o ensayos de laboratorio que el laboratorio está autorizado para procesar.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-006', 'Sistema de control de documentos y registros (SGC)',
   'Documento aprobado que describe el sistema de elaboración, aprobación y control de documentos y registros del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-007', 'Listado maestro de documentos',
   'Listado maestro actualizado de todos los documentos controlados del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-008', 'Listado maestro de registros',
   'Listado maestro actualizado de todos los registros controlados del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-009', 'Manual de calidad',
   'Manual de calidad o gestión del laboratorio aprobado. Debe incluir: alcance, responsabilidades, política y objetivos de calidad, estructura documental, seguimiento, análisis de datos y control de registros.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-010', 'Política de calidad',
   'Política de calidad del laboratorio emitida por la alta dirección, apropiada al objeto de la entidad e incluyendo compromiso de mejora continua y cumplimiento de requisitos del cliente.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-011', 'Registros de socialización de la política de calidad',
   'Listados de asistencia de socialización de la política de calidad a todo el personal. Incluir copia de la última socialización realizada.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-012', 'Procedimiento de auditoría interna',
   'Procedimiento documentado e implementado de auditorías internas del laboratorio con plan, cronograma y registro de hallazgos, acciones preventivas y correctivas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-013', 'Cronograma de auditoría del año en curso',
   'Cronograma aprobado de auditorías internas para la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-014', 'Informe de la última auditoría interna',
   'Informe de la última auditoría interna realizada al laboratorio con sus hallazgos, acciones preventivas y correctivas identificadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-015', 'Plan de acción sobre hallazgos de la última auditoría',
   'Plan de acción formulado y en seguimiento sobre los hallazgos de la última auditoría interna realizada.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-016', 'Tablas de retención documental',
   'Tablas de retención documental aprobadas. Para entidades públicas: evidencia del traslado documental del último año (Ley 594 de 2000, Decreto 2578 de 2012).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-017', 'POA del laboratorio con seguimiento',
   'Plan Operativo Anual (POA) del laboratorio de la vigencia en curso con su respectivo seguimiento periódico. Debe incluir plan de necesidades de reactivos, equipos, insumos y capacitaciones.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-018', 'Procedimiento de gestión de insumos, reactivos y equipos',
   'Procedimiento documentado de recepción, almacenamiento, control y gestión de insumos, reactivos, materiales y equipos del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-019', 'Actas de evaluación de proveedores de insumos y reactivos',
   'Actas de evaluación técnica de proveedores de insumos, reactivos y materiales consumibles utilizados en el laboratorio. Remitir mínimo dos (2) actas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-020', 'Inventario de insumos actualizado (Kardex)',
   'Control de inventario actualizado (Kardex) de reactivos, insumos y materiales empleados en los ensayos, con verificación de vigencias.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-021', 'Último reporte de Reactivovigilancia',
   'Copia del último reporte de Reactivovigilancia de reactivos de diagnóstico in vitro presentado ante el INVIMA con sus soportes.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-022', 'Último reporte de Tecnovigilancia',
   'Copia del último reporte de Tecnovigilancia presentado ante el INVIMA con sus soportes.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-023', 'Manual de Procedimientos del laboratorio',
   'Manual de procedimientos técnicos y administrativos del laboratorio, por cada área y/o prueba que procesa (incluyendo pruebas especiales y todas las secciones).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-024', 'Registros de socialización de procedimientos técnicos',
   'Listados de asistencia de socialización de los procedimientos técnicos del laboratorio dirigidos al personal de laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-025', 'Matriz de indicadores',
   'Matriz de indicadores de gestión del laboratorio con fichas técnicas que incluyan definición, fórmula, responsable y periodicidad de medición.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-026', 'Fichas técnicas de indicadores',
   'Fichas técnicas detalladas (hoja de vida) de cada indicador de gestión del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-027', 'Indicadores de los últimos 3 meses',
   'Medición y registro de todos los indicadores correspondientes a los últimos tres períodos de medición.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-028', 'Seguimiento y análisis de indicadores',
   'Análisis de resultados de indicadores con las acciones tomadas ante desviaciones o incumplimientos de las metas definidas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-029', 'Procedimiento de acciones preventivas y de mejora',
   'Procedimiento documentado e implementado de identificación, seguimiento y cierre de acciones preventivas, correctivas y de mejora (incluyendo resultados de auditorías, producto no conforme, autocontrol y riesgos).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-030', 'Matriz de Riesgos',
   'Matriz de riesgos técnicos, sanitarios y ambientales del laboratorio identificados, clasificados y actualizados.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-031', 'Seguimiento y plan de control a Riesgos',
   'Seguimiento actualizado al control y plan de mitigación de los riesgos identificados en la matriz, con acciones preventivas asociadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-032', 'Plan de contingencias',
   'Plan de contingencias para emergencias sanitarias, catástrofes o situaciones de interrupción del servicio. Incluye: designación de suplentes para funciones clave, cadena de llamadas y articulación con otros laboratorios de la red para garantizar operación 24/7.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-033', 'Procedimiento de control de calidad',
   'Procedimiento de control de calidad que describe los esquemas de control interno y externo para todas las pruebas que realiza el laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-034', 'Registros y/o convenios de confidencialidad firmados',
   'Registros o convenios de confidencialidad firmados por el personal con acceso a la información generada por el laboratorio, incluyendo registros de socialización.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-035', 'Certificados de material de referencia y controles',
   'Certificados de análisis y fichas técnicas de los materiales de referencia y controles utilizados en los ensayos del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-036', 'Certificados de verificación de equipos',
   'Certificados de verificación metrológica (calibración o calificación) de los equipos del laboratorio emitidos por proveedor acreditado con alcance NTC-ISO/IEC 17025.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-037', 'Certificados de verificación de métodos',
   'Informes de estandarización, verificación o validación de métodos analíticos conforme a los lineamientos del laboratorio nacional de referencia o de la OPS/OMS, para cada prueba del portafolio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-038', 'Cartas control de los métodos de todas las pruebas',
   'Cartas control con el análisis y seguimiento del control de calidad interno, por cada sección y prueba que procesa el laboratorio (controles internos, controles de kit, muestras caracterizadas, análisis de duplicados).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-039', 'Certificados de participación en control externo',
   'Certificados de participación y resultados en programas de evaluación externa de desempeño (PICCAP, interlaboratorio, 3ª opinión) para todas las pruebas realizadas, con mínimo una participación por prueba por evento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-040', 'Informe de análisis del control de calidad externo',
   'Informe de análisis y seguimiento del control de calidad externo con las acciones documentadas ante resultados no satisfactorios o cuestionables.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-041', 'Procedimiento de control de datos',
   'Procedimiento de custodia, transferencia y control de datos: verificación de cálculos, diligenciamiento de formatos, registro, emisión y validación de resultados. Incluye lineamientos de legibilidad, cifras significativas y niveles de acceso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-042', 'Procedimiento de reporte de resultados de laboratorio',
   'Procedimiento que define el contenido, responsabilidades y canales para la generación, emisión, aprobación y entrega de informes de resultados (impreso, electrónico y telefónico), incluyendo emisión de copias.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  -- Talento Humano
  ('IPS-L19-043', 'Manual de perfiles de puestos de trabajo',
   'Manual de perfiles de puestos de trabajo del laboratorio: profesionales (bacteriólogo, biólogo, microbiólogo), auxiliares de laboratorio, auxiliar de servicios generales y líder de calidad. Competencias conforme a Ley 841 de 2003 y Decreto 1785 de 2014.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-044', 'Hojas de vida del personal del laboratorio',
   'Hojas de vida del personal: profesionales del laboratorio, auxiliares, auxiliar de servicios generales, líder de calidad, líder de gestión ambiental e Ingeniero Biomédico que firma mantenimientos. Incluir títulos y certificaciones de experiencia.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-045', 'Plan de formación y capacitación del año en curso',
   'Plan de formación y capacitación del laboratorio para la vigencia en curso, incluyendo temas técnicos relacionados con el SGC y las pruebas que procesa.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-046', 'Cronograma de capacitaciones',
   'Cronograma detallado de capacitaciones del laboratorio con seguimiento y evaluación de eficacia del plan de la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-047', 'Registros de asistencia a capacitaciones',
   'Listados de asistencia de las últimas tres (3) capacitaciones realizadas (técnicas y del SGC), verificando participación del personal del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-048', 'Plan de inducción y reinducción',
   'Plan documentado de inducción y reinducción técnica para el personal que ingresa o cambia de actividad, con definición de responsables, procedimientos, tiempos asignados y evaluación de resultados.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-049', 'Cronograma de reinducción y registros de asistencia',
   'Cronograma de reinducción del personal del laboratorio y listados de asistencia de las reinducciones realizadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-050', 'Procedimiento de evaluación del personal',
   'Procedimiento implementado de evaluación del desempeño y competencia técnica del personal (profesional y asistencial), con la frecuencia definida y evaluación de eficacia.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-051', 'Certificados de evaluación del personal del laboratorio',
   'Certificados o registros de la evaluación de desempeño y competencia técnica del personal del laboratorio, conforme a la frecuencia definida en el procedimiento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  -- Infraestructura y Dotación
  ('IPS-L19-052', 'Certificado de construcción sismo resistente',
   'Constancias emitidas por autoridad competente que certifican que la edificación fue construida bajo las normas de sismoresistencia vigentes (Ley 400 de 1997 y NSR 2010), o documentos del Ministerio de Salud aprobando adecuaciones realizadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-053', 'Plan Metrológico',
   'Plan metrológico anual implementado con las operaciones de confirmación metrológica (OCM) aplicables a cada equipo del laboratorio y su respectivo seguimiento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-054', 'Hojas de vida de equipos del laboratorio',
   'Hojas de vida de los equipos del laboratorio que incluyen: identificación, datos del fabricante, número de serie, fecha de recepción, puesta en servicio, historial de OCM, ubicación (área/sección) y manuales de operación.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-055', 'Certificados de mantenimiento de los equipos',
   'Certificados y registros de mantenimiento preventivo y correctivo de los equipos del laboratorio para la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips'),
  ('IPS-L19-056', 'Certificados de calibración de los equipos',
   'Certificados de calibración de los equipos del laboratorio emitidos por proveedor acreditado con alcance NTC-ISO/IEC 17025, con vigencia y resultados verificables.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'ips')
ON CONFLICT (code) DO NOTHING;

-- ── INDEPENDIENTE ─────────────────────────────────────────────
INSERT INTO document_catalog
  (code, name, description, category, standard_reference, is_mandatory, applies_to_all, provider_type)
VALUES
  -- Organización y Gestión
  ('IND-L19-001', 'Copia del distintivo de habilitación',
   'Copia del certificado o distintivo de habilitación vigente del laboratorio como prestador de servicios de salud.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-002', 'Certificado de representación legal',
   'Certificado de representación legal actualizado (no mayor a 30 días de expedición).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-003', 'Organigrama institucional y acto administrativo',
   'Organigrama de la entidad o del laboratorio con su acto administrativo de aprobación. El laboratorio debe estar claramente identificado en la estructura funcional.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-004', 'Portafolio de Servicios',
   'Portafolio de servicios del laboratorio aprobado y vigente.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-005', 'Portafolio de pruebas que procesa',
   'Listado actualizado de las pruebas o ensayos de laboratorio que el laboratorio está autorizado para procesar.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-006', 'Sistema de control de documentos y registros (SGC)',
   'Documento aprobado que describe el sistema de elaboración, aprobación y control de documentos y registros del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-007', 'Listado maestro de documentos',
   'Listado maestro actualizado de todos los documentos controlados del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-008', 'Listado maestro de registros',
   'Listado maestro actualizado de todos los registros controlados del sistema de gestión de calidad.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-009', 'Manual de calidad',
   'Manual de calidad o gestión del laboratorio aprobado. Debe incluir: alcance, responsabilidades, política y objetivos de calidad, estructura documental, seguimiento, análisis de datos y control de registros.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-010', 'Política de calidad',
   'Política de calidad del laboratorio emitida por la alta dirección, apropiada al objeto de la entidad e incluyendo compromiso de mejora continua y cumplimiento de requisitos del cliente.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-011', 'Registros de socialización de la política de calidad',
   'Listados de asistencia de socialización de la política de calidad a todo el personal. Incluir copia de la última socialización realizada.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-012', 'Procedimiento de auditoría interna',
   'Procedimiento documentado e implementado de auditorías internas del laboratorio con plan, cronograma y registro de hallazgos, acciones preventivas y correctivas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-013', 'Cronograma de auditoría del año en curso',
   'Cronograma aprobado de auditorías internas para la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-014', 'Informe de la última auditoría interna',
   'Informe de la última auditoría interna realizada al laboratorio con sus hallazgos, acciones preventivas y correctivas identificadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-015', 'Plan de acción sobre hallazgos de la última auditoría',
   'Plan de acción formulado y en seguimiento sobre los hallazgos de la última auditoría interna realizada.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-016', 'Tablas de retención documental',
   'Tablas de retención documental aprobadas. Para entidades públicas: evidencia del traslado documental del último año (Ley 594 de 2000, Decreto 2578 de 2012).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-017', 'POA del laboratorio con seguimiento',
   'Plan Operativo Anual (POA) del laboratorio de la vigencia en curso con su respectivo seguimiento periódico. Debe incluir plan de necesidades de reactivos, equipos, insumos y capacitaciones.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-018', 'Procedimiento de gestión de insumos, reactivos y equipos',
   'Procedimiento documentado de recepción, almacenamiento, control y gestión de insumos, reactivos, materiales y equipos del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-019', 'Actas de evaluación de proveedores de insumos y reactivos',
   'Actas de evaluación técnica de proveedores de insumos, reactivos y materiales consumibles utilizados en el laboratorio. Remitir mínimo dos (2) actas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-020', 'Inventario de insumos actualizado (Kardex)',
   'Control de inventario actualizado (Kardex) de reactivos, insumos y materiales empleados en los ensayos, con verificación de vigencias.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-021', 'Último reporte de Reactivovigilancia',
   'Copia del último reporte de Reactivovigilancia de reactivos de diagnóstico in vitro presentado ante el INVIMA con sus soportes.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-022', 'Último reporte de Tecnovigilancia',
   'Copia del último reporte de Tecnovigilancia presentado ante el INVIMA con sus soportes.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-023', 'Manual de Procedimientos del laboratorio',
   'Manual de procedimientos técnicos y administrativos del laboratorio, por cada área y/o prueba que procesa (incluyendo pruebas especiales y todas las secciones).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-024', 'Registros de socialización de procedimientos técnicos',
   'Listados de asistencia de socialización de los procedimientos técnicos del laboratorio dirigidos al personal de laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-025', 'Matriz de indicadores',
   'Matriz de indicadores de gestión del laboratorio con fichas técnicas que incluyan definición, fórmula, responsable y periodicidad de medición.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-026', 'Fichas técnicas de indicadores',
   'Fichas técnicas detalladas (hoja de vida) de cada indicador de gestión del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-027', 'Indicadores de los últimos 3 meses',
   'Medición y registro de todos los indicadores correspondientes a los últimos tres períodos de medición.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-028', 'Seguimiento y análisis de indicadores',
   'Análisis de resultados de indicadores con las acciones tomadas ante desviaciones o incumplimientos de las metas definidas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-029', 'Procedimiento de acciones preventivas y de mejora',
   'Procedimiento documentado e implementado de identificación, seguimiento y cierre de acciones preventivas, correctivas y de mejora (incluyendo resultados de auditorías, producto no conforme, autocontrol y riesgos).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-030', 'Matriz de Riesgos',
   'Matriz de riesgos técnicos, sanitarios y ambientales del laboratorio identificados, clasificados y actualizados.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-031', 'Seguimiento y plan de control a Riesgos',
   'Seguimiento actualizado al control y plan de mitigación de los riesgos identificados en la matriz, con acciones preventivas asociadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-032', 'Plan de contingencias',
   'Plan de contingencias para emergencias sanitarias, catástrofes o situaciones de interrupción del servicio. Incluye: designación de suplentes para funciones clave, cadena de llamadas y articulación con otros laboratorios de la red para garantizar operación 24/7.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-033', 'Procedimiento de control de calidad',
   'Procedimiento de control de calidad que describe los esquemas de control interno y externo para todas las pruebas que realiza el laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-034', 'Registros y/o convenios de confidencialidad firmados',
   'Registros o convenios de confidencialidad firmados por el personal con acceso a la información generada por el laboratorio, incluyendo registros de socialización.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-035', 'Certificados de material de referencia y controles',
   'Certificados de análisis y fichas técnicas de los materiales de referencia y controles utilizados en los ensayos del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-036', 'Certificados de verificación de equipos',
   'Certificados de verificación metrológica (calibración o calificación) de los equipos del laboratorio emitidos por proveedor acreditado con alcance NTC-ISO/IEC 17025.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-037', 'Certificados de verificación de métodos',
   'Informes de estandarización, verificación o validación de métodos analíticos conforme a los lineamientos del laboratorio nacional de referencia o de la OPS/OMS, para cada prueba del portafolio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-038', 'Cartas control de los métodos de todas las pruebas',
   'Cartas control con el análisis y seguimiento del control de calidad interno, por cada sección y prueba que procesa el laboratorio (controles internos, controles de kit, muestras caracterizadas, análisis de duplicados).',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-039', 'Certificados de participación en control externo',
   'Certificados de participación y resultados en programas de evaluación externa de desempeño (PICCAP, interlaboratorio, 3ª opinión) para todas las pruebas realizadas, con mínimo una participación por prueba por evento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-040', 'Informe de análisis del control de calidad externo',
   'Informe de análisis y seguimiento del control de calidad externo con las acciones documentadas ante resultados no satisfactorios o cuestionables.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-041', 'Procedimiento de control de datos',
   'Procedimiento de custodia, transferencia y control de datos: verificación de cálculos, diligenciamiento de formatos, registro, emisión y validación de resultados. Incluye lineamientos de legibilidad, cifras significativas y niveles de acceso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-042', 'Procedimiento de reporte de resultados de laboratorio',
   'Procedimiento que define el contenido, responsabilidades y canales para la generación, emisión, aprobación y entrega de informes de resultados (impreso, electrónico y telefónico), incluyendo emisión de copias.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  -- Talento Humano
  ('IND-L19-043', 'Manual de perfiles de puestos de trabajo',
   'Manual de perfiles de puestos de trabajo del laboratorio: profesionales (bacteriólogo, biólogo, microbiólogo), auxiliares de laboratorio, auxiliar de servicios generales y líder de calidad. Competencias conforme a Ley 841 de 2003 y Decreto 1785 de 2014.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-044', 'Hojas de vida del personal del laboratorio',
   'Hojas de vida del personal: profesionales del laboratorio, auxiliares, auxiliar de servicios generales, líder de calidad, líder de gestión ambiental e Ingeniero Biomédico que firma mantenimientos. Incluir títulos y certificaciones de experiencia.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-045', 'Plan de formación y capacitación del año en curso',
   'Plan de formación y capacitación del laboratorio para la vigencia en curso, incluyendo temas técnicos relacionados con el SGC y las pruebas que procesa.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-046', 'Cronograma de capacitaciones',
   'Cronograma detallado de capacitaciones del laboratorio con seguimiento y evaluación de eficacia del plan de la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-047', 'Registros de asistencia a capacitaciones',
   'Listados de asistencia de las últimas tres (3) capacitaciones realizadas (técnicas y del SGC), verificando participación del personal del laboratorio.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-048', 'Plan de inducción y reinducción',
   'Plan documentado de inducción y reinducción técnica para el personal que ingresa o cambia de actividad, con definición de responsables, procedimientos, tiempos asignados y evaluación de resultados.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-049', 'Cronograma de reinducción y registros de asistencia',
   'Cronograma de reinducción del personal del laboratorio y listados de asistencia de las reinducciones realizadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-050', 'Procedimiento de evaluación del personal',
   'Procedimiento implementado de evaluación del desempeño y competencia técnica del personal (profesional y asistencial), con la frecuencia definida y evaluación de eficacia.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-051', 'Certificados de evaluación del personal del laboratorio',
   'Certificados o registros de la evaluación de desempeño y competencia técnica del personal del laboratorio, conforme a la frecuencia definida en el procedimiento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  -- Infraestructura y Dotación
  ('IND-L19-052', 'Certificado de construcción sismo resistente',
   'Constancias emitidas por autoridad competente que certifican que la edificación fue construida bajo las normas de sismoresistencia vigentes (Ley 400 de 1997 y NSR 2010), o documentos del Ministerio de Salud aprobando adecuaciones realizadas.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-053', 'Plan Metrológico',
   'Plan metrológico anual implementado con las operaciones de confirmación metrológica (OCM) aplicables a cada equipo del laboratorio y su respectivo seguimiento.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-054', 'Hojas de vida de equipos del laboratorio',
   'Hojas de vida de los equipos del laboratorio que incluyen: identificación, datos del fabricante, número de serie, fecha de recepción, puesta en servicio, historial de OCM, ubicación (área/sección) y manuales de operación.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-055', 'Certificados de mantenimiento de los equipos',
   'Certificados y registros de mantenimiento preventivo y correctivo de los equipos del laboratorio para la vigencia en curso.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente'),
  ('IND-L19-056', 'Certificados de calibración de los equipos',
   'Certificados de calibración de los equipos del laboratorio emitidos por proveedor acreditado con alcance NTC-ISO/IEC 17025, con vigencia y resultados verificables.',
   'Calidad Laboratorio (Res. 1619)', 'LAB19', true, true, 'independiente')
ON CONFLICT (code) DO NOTHING;
