-- Migración: reemplazar 157 servicios ficticios por los 157 servicios oficiales REPS (Resolución 3100/2019)
-- Primero nullificar FKs que no tienen ON DELETE SET NULL, luego eliminar servicios

UPDATE findings SET service_id = NULL WHERE service_id IS NOT NULL;
DELETE FROM services WHERE code NOT IN (
  '105','106','107','108','109','110','120','129','130','131','132','133','134','135','138',
  '201','202','203','204','205','207','208','209','210','211','212','213','214','215','217','218','227','231','232','233','234','235','237','245',
  '301','302','303','304','306','308','309','310','311','312','313','316','317','318','320','321','323','324','325','326','327','328','329','330','331','332','333','334','335','336','337','338','339','340','342',
  '343','344','345','346','347','348','349','350','351','352','353','354','355','356','357','358','359','360','361','362','363','364','365','366','367','368','369','370','371','372','373','374','375','376','377','378','379','380','381','382','383','384','385','386','387','388','389','390','391','392','393','394','395','396','397','398','399',
  '401','402','403','404','405','406','407','408','409','410','411','412','413','414','415','416','417','418','419','420','421','422','423','424','425','426','427','428','429','430','431','432','433','434','435',
  '501','502','503','504','505','506','507','508','509','510','511','512','513','514','515','516','517','518','519','520','521','522','523','524','525','526','527','528','529','530','531'
);
DELETE FROM services;

INSERT INTO services (code, name, category) VALUES
  ('105', 'CUIDADO INTERMEDIO NEONATAL', 'Internación'),
  ('106', 'CUIDADO INTERMEDIO PEDIÁTRICO', 'Internación'),
  ('107', 'CUIDADO INTERMEDIO ADULTOS', 'Internación'),
  ('108', 'CUIDADO INTENSIVO NEONATAL', 'Internación'),
  ('109', 'CUIDADO INTENSIVO PEDIÁTRICO', 'Internación'),
  ('110', 'CUIDADO INTENSIVO ADULTOS', 'Internación'),
  ('120', 'CUIDADO BÁSICO NEONATAL', 'Internación'),
  ('129', 'HOSPITALIZACIÓN ADULTOS', 'Internación'),
  ('130', 'HOSPITALIZACIÓN PEDIÁTRICA', 'Internación'),
  ('131', 'HOSPITALIZACIÓN EN SALUD MENTAL', 'Internación'),
  ('132', 'HOSPITALIZACIÓN PARCIAL', 'Internación'),
  ('133', 'HOSPITALIZACIÓN PACIENTE CRÓNICO CON VENTILADOR', 'Internación'),
  ('134', 'HOSPITALIZACIÓN PACIENTE CRÓNICO SIN VENTILADOR', 'Internación'),
  ('135', 'HOSPITALIZACIÓN EN  CONSUMO DE SUSTANCIAS PSICOACTIVAS', 'Internación'),
  ('138', 'CUIDADO BÁSICO DEL CONSUMO DE SUSTANCIAS PSICOACTIVAS', 'Internación'),
  ('201', 'CIRUGÍA DE CABEZA Y CUELLO', 'Quirúrgicos'),
  ('202', 'CIRUGÍA CARDIOVASCULAR', 'Quirúrgicos'),
  ('203', 'CIRUGÍA GENERAL', 'Quirúrgicos'),
  ('204', 'CIRUGÍA GINECOLÓGICA', 'Quirúrgicos'),
  ('205', 'CIRUGÍA MAXILOFACIAL', 'Quirúrgicos'),
  ('207', 'CIRUGÍA ORTOPÉDICA', 'Quirúrgicos'),
  ('208', 'CIRUGÍA OFTALMOLÓGICA', 'Quirúrgicos'),
  ('209', 'CIRUGÍA OTORRINOLARINGOLOGÍA', 'Quirúrgicos'),
  ('210', 'CIRUGÍA ONCOLÓGICA', 'Quirúrgicos'),
  ('211', 'CIRUGÍA ORAL', 'Quirúrgicos'),
  ('212', 'CIRUGÍA PEDIÁTRICA', 'Quirúrgicos'),
  ('213', 'CIRUGÍA PLÁSTICA Y ESTTICA', 'Quirúrgicos'),
  ('214', 'CIRUGÍA VASCULAR Y ANGIOLGICA', 'Quirúrgicos'),
  ('215', 'CIRUGÍA UROLÓGICA', 'Quirúrgicos'),
  ('217', 'OTRAS CIRUGÍAS', 'Quirúrgicos'),
  ('218', 'CIRUGÍA ENDOVASCULAR NEUROLÓGICA', 'Quirúrgicos'),
  ('227', 'CIRUGÍA ONCOLÓGICA PEDIÁTRICA', 'Quirúrgicos'),
  ('231', 'CIRUGÍA DE LA MANO', 'Quirúrgicos'),
  ('232', 'CIRUGÍA DE MAMA Y TUMORES TEJIDOS BLANDOS', 'Quirúrgicos'),
  ('233', 'CIRUGÍA DERMATOLÓGICA', 'Quirúrgicos'),
  ('234', 'CIRUGÍA DE TÓRAX', 'Quirúrgicos'),
  ('235', 'CIRUGÍA GASTROINTESTINAL', 'Quirúrgicos'),
  ('237', 'CIRUGÍA PLÁSTICA ONCOLÓGICA', 'Quirúrgicos'),
  ('245', 'NEUROCIRUGÍA', 'Quirúrgicos'),
  ('301', 'ANESTESIA', 'Consulta Externa'),
  ('302', 'CARDIOLOGÍA', 'Consulta Externa'),
  ('303', 'CIRUGÍA CARDIOVASCULAR', 'Consulta Externa'),
  ('304', 'CIRUGÍA GENERAL', 'Consulta Externa'),
  ('306', 'CIRUGÍA PEDIÁTRICA', 'Consulta Externa'),
  ('308', 'DERMATOLOGÍA', 'Consulta Externa'),
  ('309', 'DOLOR Y CUIDADOS PALIATIVOS', 'Consulta Externa'),
  ('310', 'ENDOCRINOLOGÍA', 'Consulta Externa'),
  ('311', 'ENDODONCIA', 'Consulta Externa'),
  ('312', 'ENFERMERÍA', 'Consulta Externa'),
  ('313', 'ESTOMATOLOGÍA', 'Consulta Externa'),
  ('316', 'GASTROENTEROLOGÍA', 'Consulta Externa'),
  ('317', 'GENÉTICA', 'Consulta Externa'),
  ('318', 'GERIATRÍA', 'Consulta Externa'),
  ('320', 'GINECOBSTETRICIA', 'Consulta Externa'),
  ('321', 'HEMATOLOGÍA', 'Consulta Externa'),
  ('323', 'INFECTOLOGÍA', 'Consulta Externa'),
  ('324', 'INMUNOLOGÍA', 'Consulta Externa'),
  ('325', 'MEDICINA FAMILIAR', 'Consulta Externa'),
  ('326', 'MEDICINA FÍSICA Y DEL DEPORTE', 'Consulta Externa'),
  ('327', 'MEDICINA FÍSICA Y REHABILITACIÓN', 'Consulta Externa'),
  ('328', 'MEDICINA GENERAL', 'Consulta Externa'),
  ('329', 'MEDICINA INTERNA', 'Consulta Externa'),
  ('330', 'NEFROLOGÍA', 'Consulta Externa'),
  ('331', 'NEUMOLOGÍA', 'Consulta Externa'),
  ('332', 'NEUROLOGÍA', 'Consulta Externa'),
  ('333', 'NUTRICIÓN Y DIETÉTICA', 'Consulta Externa'),
  ('334', 'ODONTOLOGA GENERAL', 'Consulta Externa'),
  ('335', 'OFTALMOLOGÍA', 'Consulta Externa'),
  ('336', 'ONCOLOGÍA CLNICA', 'Consulta Externa'),
  ('337', 'OPTOMETRÍA', 'Consulta Externa'),
  ('338', 'ORTODONCIA', 'Consulta Externa'),
  ('339', 'ORTOPEDIA Y/O TRAUMATOLOGÍA', 'Consulta Externa'),
  ('340', 'OTORRINOLARINGOLOGÍA', 'Consulta Externa'),
  ('342', 'PEDIATRÍA', 'Consulta Externa'),
  ('343', 'PERIODONCIA', 'Consulta Externa'),
  ('344', 'PSICOLOGA', 'Consulta Externa'),
  ('345', 'PSIQUIATRÍA', 'Consulta Externa'),
  ('346', 'REHABILITACIÓN ONCOLÓGICA', 'Consulta Externa'),
  ('347', 'REHABILITACIÓN ORAL', 'Consulta Externa'),
  ('348', 'REUMATOLOGÍA', 'Consulta Externa'),
  ('354', 'TOXICOLOGA', 'Consulta Externa'),
  ('355', 'UROLOGA', 'Consulta Externa'),
  ('356', 'OTRAS CONSULTAS DE ESPECIALIDAD', 'Consulta Externa'),
  ('361', 'CARDIOLOGÍA PEDIÁTRICA', 'Consulta Externa'),
  ('362', 'CIRUGÍA DE CABEZA Y CUELLO', 'Consulta Externa'),
  ('363', 'CIRUGÍA DE MANO', 'Consulta Externa'),
  ('364', 'CIRUGÍA DE MAMA Y TUMORES TEJIDOS BLANDOS', 'Consulta Externa'),
  ('365', 'CIRUGÍA DERMATOLÓGICA', 'Consulta Externa'),
  ('366', 'CIRUGÍA DE TÓRAX', 'Consulta Externa'),
  ('367', 'CIRUGÍA GASTROINTESTINAL', 'Consulta Externa'),
  ('368', 'CIRUGÍA GINECOLÓGICA LAPAROSCPICA', 'Consulta Externa'),
  ('369', 'CIRUGÍA PLÁSTICA Y ESTTICA', 'Consulta Externa'),
  ('370', 'CIRUGÍA PLÁSTICA ONCOLÓGICA', 'Consulta Externa'),
  ('371', 'OTRAS CONSULTAS GENERALES', 'Consulta Externa'),
  ('372', 'CIRUGÍA VASCULAR', 'Consulta Externa'),
  ('373', 'CIRUGÍA ONCOLÓGICA', 'Consulta Externa'),
  ('374', 'CIRUGÍA ONCOLÓGICA PEDIÁTRICA', 'Consulta Externa'),
  ('375', 'DERMATOLOGÍA ONCOLÓGICA', 'Consulta Externa'),
  ('377', 'COLOPROCTOLOGA', 'Consulta Externa'),
  ('379', 'GINECOLOGA ONCOLÓGICA', 'Consulta Externa'),
  ('383', 'MEDICINA NUCLEAR', 'Consulta Externa'),
  ('384', 'NEFROLOGÍA PEDIÁTRICA', 'Consulta Externa'),
  ('385', 'NEONATOLOGÍA', 'Consulta Externa'),
  ('386', 'NEUMOLOGÍA PEDIÁTRICA', 'Consulta Externa'),
  ('387', 'NEUROCIRUGÍA', 'Consulta Externa'),
  ('388', 'NEUROPEDIATRÍA', 'Consulta Externa'),
  ('390', 'OFTALMOLOGÍA ONCOLÓGICA', 'Consulta Externa'),
  ('391', 'ONCOLOGÍA Y HEMATOLOGÍA PEDIÁTRICA', 'Consulta Externa'),
  ('393', 'ORTOPEDIA ONCOLÓGICA', 'Consulta Externa'),
  ('395', 'UROLOGA ONCOLÓGICA', 'Consulta Externa'),
  ('396', 'ODONTOPEDIATRÍA', 'Consulta Externa'),
  ('397', 'MEDICINA ESTTICA', 'Consulta Externa'),
  ('406', 'HEMATOLOGÍA ONCOLÓGICA', 'Consulta Externa'),
  ('407', 'MEDICINA DEL TRABAJO Y MEDICINA LABORAL', 'Consulta Externa'),
  ('408', 'RADIOTERAPIA', 'Consulta Externa'),
  ('409', 'ORTOPEDIA PEDIÁTRICA', 'Consulta Externa'),
  ('410', 'CIRUGÍA ORAL', 'Consulta Externa'),
  ('411', 'CIRUGÍA MAXILOFACIAL', 'Consulta Externa'),
  ('412', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - HOMEOPTICA', 'Consulta Externa'),
  ('413', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - AYURVDICA', 'Consulta Externa'),
  ('414', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - TRADICIONAL CHINA', 'Consulta Externa'),
  ('415', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - NATUROPTICA', 'Consulta Externa'),
  ('416', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - NEURALTERAPUTICA', 'Consulta Externa'),
  ('417', 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - BIOENERGTICA', 'Consulta Externa'),
  ('418', 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - TERAPIA CON FILTROS', 'Consulta Externa'),
  ('419', 'TERAPIAS ALTERNATIVAS Y COMPLEMENTARIAS - TERAPIAS MANUALES', 'Consulta Externa'),
  ('420', 'VACUNACIN', 'Consulta Externa'),
  ('421', 'PATOLOGÍA', 'Consulta Externa'),
  ('422', 'MEDICINA ALTERNATIVA Y COMPLEMENTARIA - OSTEOPTICA', 'Consulta Externa'),
  ('423', 'SEGURIDAD Y SALUD EN EL TRABAJO', 'Consulta Externa'),
  ('706', 'LABORATORIO CLNICO', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('709', 'QUIMIOTERAPIA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('711', 'RADIOTERAPIA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('712', 'TOMA DE MUESTRAS DE LABORATORIO CLNICO', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('714', 'SERVICIO FARMACUTICO', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('715', 'MEDICINA NUCLEAR', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('717', 'LABORATORIO CITOLOGAS CERVICO-UTERINAS', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('728', 'TERAPIA OCUPACIONAL', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('729', 'TERAPIA RESPIRATORIA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('731', 'LABORATORIO DE HISTOTECNOLOGA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('733', 'HEMODIÁLISIS', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('734', 'DIÁLISIS PERITONEAL', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('739', 'FISIOTERAPIA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('740', 'FONOAUDIOLOGÍA Y/O TERAPIA DEL LENGUAJE', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('742', 'DIAGNSTICO VASCULAR', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('743', 'HEMODINAMIA E INTERVENCIONISMO', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('744', 'IMGENES DIAGNOSTICAS - IONIZANTES', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('745', 'IMGENES DIAGNOSTICAS - NO IONIZANTES', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('746', 'GESTION PRE-TRANSFUSIONAL', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('747', 'PATOLOGÍA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('748', 'RADIOLOGÍA ODONTOLGICA', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('749', 'TOMA DE MUESTRAS DE CUELLO UTERINO Y GINECOLÓGICAS', 'Apoyo Diagnóstico y Complementación Terapéutica'),
  ('1101', 'ATENCIN DEL PARTO', 'Atención Inmediata'),
  ('1102', 'URGENCIAS', 'Atención Inmediata'),
  ('1103', 'TRANSPORTE ASISTENCIAL BASICO', 'Atención Inmediata'),
  ('1104', 'TRANSPORTE ASISTENCIAL MEDICALIZADO', 'Atención Inmediata'),
  ('1105', 'ATENCIN PREHOSPITALARIA', 'Atención Inmediata');

SELECT COUNT(*) AS total_servicios_reps FROM services;