-- Insertar los 34 tipos de servicio de la Resolución 3100/2019
-- Estos códigos corresponden a los grupos de servicios con estándares específicos de habilitación

INSERT INTO services (code, name, category, description, status) VALUES ('CEG', 'Consulta Externa General', 'Consulta Externa', 'Consulta Externa General - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CEE', 'Consulta Externa Especializada', 'Consulta Externa', 'Consulta Externa Especializada - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CEV', 'Consulta Externa Virtual', 'Consulta Externa', 'Consulta Externa Virtual - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CES', 'Consulta Externa SS en el Trabajo', 'Consulta Externa', 'Consulta Externa Seguridad Social en el Trabajo - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('TRF', 'Terapia Fisica', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Terapia Fisica - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('RXO', 'Rayos X Odontologicos', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Rayos X Odontologicos - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('IDX', 'Imagenes Diagnosticas', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Imagenes Diagnosticas - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('RDT', 'Radioterapia', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Radioterapia - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('QMT', 'Quimioterapia', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Quimioterapia - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('DVX', 'Diagnostico Vascular', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Diagnostico Vascular - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('HTR', 'Hematologia', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Hematologia - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('GNT', 'Genetica', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Genetica - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('TLC', 'Tecnicas Minimamente Invasivas Laparoscopicas', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Tecnicas Minimamente Invasivas Laparoscopicas - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('LAB', 'Laboratorio Clinico', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Laboratorio Clinico - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('LAC', 'Laboratorio Clinico Urgencias', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Laboratorio Clinico Urgencias - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('LHT', 'Laboratorio de Hematologia', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Laboratorio de Hematologia - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('LPT', 'Laboratorio de Patologia', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Laboratorio de Patologia - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('DLS', 'Dialisis', 'Apoyo Diagnostico y Complementacion Terapeutica', 'Dialisis - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('HGP', 'Hospitalizacion General', 'Internacion', 'Hospitalizacion General - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('HPP', 'Hospitalizacion Pediatria', 'Internacion', 'Hospitalizacion Pediatria - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('OBN', 'Obstetricia Neonatal', 'Internacion', 'Obstetricia Neonatal - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CII', 'Cuidado Intermedio Neonatal', 'Internacion', 'Cuidado Intermedio Neonatal - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CIP', 'Cuidado Intensivo Pediatrico', 'Internacion', 'Cuidado Intensivo Pediatrico - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CIM', 'Cuidado Intermedio Pediatrico', 'Internacion', 'Cuidado Intermedio Pediatrico - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CIA', 'Cuidado Intensivo Adulto', 'Internacion', 'Cuidado Intensivo Adulto - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CIMA', 'Cuidado Intermedio Adulto', 'Internacion', 'Cuidado Intermedio Adulto - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('HSC', 'Hospitalizacion Salud Mental', 'Internacion', 'Hospitalizacion Salud Mental - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('HSP', 'Hospitalizacion Psiquiatrica', 'Internacion', 'Hospitalizacion Psiquiatrica - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('CPC', 'Cuidado Basico Psiquiatrico', 'Internacion', 'Cuidado Basico Psiquiatrico - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('QRG', 'Quirurgico', 'Quirurgicos', 'Quirurgico - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('URG', 'Urgencias', 'Atencion Inmediata', 'Urgencias - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('TAS', 'Transporte Asistencial', 'Atencion Inmediata', 'Transporte Asistencial - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('APH', 'Atencion Prehospitalaria', 'Atencion Inmediata', 'Atencion Prehospitalaria - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
INSERT INTO services (code, name, category, description, status) VALUES ('APR', 'Atencion del Parto', 'Atencion Inmediata', 'Atencion del Parto - Res. 3100/2019', 'available') ON CONFLICT (code) DO NOTHING;
